### PR TITLE
Add DNS provider for Core-Networks

### LINKED ISSUE #1989: Support for provider: Core-Networks
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Binary

### Link to the DNS provider

https://www.core-networks.de/

### Link to the API documentation

https://beta.api.core-networks.de/doc/

### Additional Notes

German hoster with DNSSEC support.

### PR DESCRIPTION
**Pull request by ldez**
- [x] add a description to your PR
- [x] have a homogeneous design with the other providers
- [x] add tests (units)
- [x] add tests ("live")
- [x] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [x] generate CLI help, documentation, and readme.
- [x] be able to do: _(and put the output of this command to a comment)_
  ```bash
  make build
  rm -rf .lego

  CORENETWORKS_LOGIN="xxxx" \
  CORENETWORKS_PASSWORD="yyyy" \
  ./dist/lego -m your@email.com --dns corenetworks -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
  ```
  **Note the wildcard domain is important.**
- [x] pass the linter
- [x] do `go mod tidy`

Ping @renne, can you run the command (with your domain, email, and credentials)?

Closes #1989

### CODE REVIEW

**Comment by ldez** [comment]
@renne do you need help to run the command?

**Comment by heliax01** [comment]
Hi, i would like to step in here, because i would like to see this provider in go-acme.

`root@webserver:~/lego# HOSTINGNL_API_KEY="sYWZzTyJji8xxxxxxxxxxxxGjzy3nBDifbYrPK0kbiSAT4SzUpi7c4mqBkpuvak" ./dist/lego -m corenetworks@example.de --dns corenetworks -d *.example.de -d example.de -s https://acme-staging-v02.api.letsencrypt.org/directory run
2024/10/24 16:13:57 No key found for account corenetworks@example.de. Generating a P256 key.
2024/10/24 16:13:57 Saved key to /root/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/corenetworks@example.de/keys/corenetworks@example.de.key
2024/10/24 16:13:58 corenetworks: some credentials information are missing: CORENETWORKS_LOGIN,CORENETWORKS_PASSWORD
root@webserver:~/lego#`

The API Token is working.
`root@webserver:~/lego# curl -H "Authorization: Bearer sYWZzTyJji8xxxxxxxxxxxxGjzy3nBDifbYrPK0kbiSAT4SzUpi7c4mqBkpuvak" https://beta.api.core-networks.de/dnszones/
[{"name":"example.de","type":"master"}]
root@webserver:~/lego#`

**Comment by ldez** [comment]
@heliax01 It was an error in the command, I updated the description.

**Comment by heliax01** [comment]
Looks better..
```console
root@webserver:~/lego# CORENETWORKS_LOGIN="xxxxxxxxxxxx" CORENETWORKS_PASSWORD="xxxxxxxxxxxxx" ./dist/lego -m corenetworks@example.de --dns corenetworks -d grafi.example.de -d example.de -s https://acme-staging-v02.api.letsencrypt.org/directory run
2024/10/24 21:14:33 No key found for account corenetworks@example.de. Generating a P256 key.
2024/10/24 21:14:33 Saved key to /root/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/corenetworks@example.de/keys/corenetworks@example.de.key
2024/10/24 21:14:34 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf
Do you accept the TOS? Y/n
y
2024/10/24 21:14:39 [INFO] acme: Registering account for corenetworks@example.de
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/root/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2024/10/24 21:14:39 [INFO] [grafi.example.de, example.de] acme: Obtaining bundled SAN certificate
2024/10/24 21:14:40 [INFO] [grafi.example.de] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/14577724973
2024/10/24 21:14:40 [INFO] [example.de] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/14577724983
2024/10/24 21:14:40 [INFO] [grafi.example.de] acme: Could not find solver for: tls-alpn-01
2024/10/24 21:14:40 [INFO] [grafi.example.de] acme: Could not find solver for: http-01
2024/10/24 21:14:40 [INFO] [grafi.example.de] acme: use dns-01 solver
2024/10/24 21:14:40 [INFO] [example.de] acme: Could not find solver for: tls-alpn-01
2024/10/24 21:14:40 [INFO] [example.de] acme: Could not find solver for: http-01
2024/10/24 21:14:40 [INFO] [example.de] acme: use dns-01 solver
2024/10/24 21:14:40 [INFO] [grafi.example.de] acme: Preparing to solve DNS-01
2024/10/24 21:14:40 [INFO] [example.de] acme: Preparing to solve DNS-01
2024/10/24 21:14:41 [INFO] [grafi.example.de] acme: Cleaning DNS-01 challenge
2024/10/24 21:14:41 [WARN] [grafi.example.de] acme: cleaning up failed: corenetworks: delete records: unexpected status code: [status code: 404] body: Invalid zone
2024/10/24 21:14:41 [INFO] [example.de] acme: Cleaning DNS-01 challenge
2024/10/24 21:14:41 [WARN] [example.de] acme: cleaning up failed: corenetworks: delete records: unexpected status code: [status code: 404] body: Invalid zone
2024/10/24 21:14:41 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/14577724973
2024/10/24 21:14:41 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/14577724983
2024/10/24 21:14:42 Could not obtain certificates:
        error: one or more domains had a problem:
[grafi.example.de] [grafi.example.de] acme: error presenting token: corenetworks: add record: unexpected status code: [status code: 404] body: Not Found
[example.de] [example.de] acme: error presenting token: corenetworks: add record: unexpected status code: [status code: 404] body: Not Found
root@webserver:~/lego#
```

**Comment by ldez** [comment]
can you run again with the env var `LEGO_DEBUG_CLIENT_VERBOSE_ERROR` set to `true`?

**Comment by ldez** [comment]
I updated the PR, I think the problem was related to the apex handling.

I also change the "mode" of the provider because, based on the translated doc, the provider doesn't support multiple records for the same domain at the same time.

> Beim Hinzufügen eines bereits existierenden Records, wird kein zweiter erstellt, aber auch kein Fehler gemeldet.

> When adding an existing record, no second one is created and no error is reported.

**Comment by ldez** [comment]
> I am not really sure if i have used the LEGO_DEBUG_CLIENT_VERBOSE_ERROR=true variable correctly.

You should remove the `;`

```bash
LEGO_DEBUG_CLIENT_VERBOSE_ERROR=true CORENETWORKS_LOGIN="apiexample" CORENETWORKS_PASSWORD="mypassword" ./dist/lego -m corenetworks@example.de --dns corenetworks -d *.example.de -d example.de -s https://acme-staging-v02.api.letsencrypt.org/directory run
```

**Comment by heliax01** [comment]
Ok, sorry. I did run the same command again, without ";" and the output looks exactly the same.

**Comment by ldez** [comment]
Are you using CNAME?

**Comment by ldez** [comment]
I updated the PR can you try again?

**Comment by heliax01** [comment]
Looks good this time

```console
root@cachehost ~/lego # gh pr checkout 2101
remote: Enumerating objects: 61, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 61 (delta 35), reused 53 (delta 35), pack-reused 7 (from 1)
Unpacking objects: 100% (61/61), 9.80 KiB | 557.00 KiB/s, done.
From https://github.com/go-acme/lego
 * [new ref]           refs/pull/2101/head -> feat/corenetworks
Switched to branch 'feat/corenetworks'
root@cachehost ~/lego # make build
BIN_OUTPUT: dist/lego
rm -rf dist/ builds/ cover.out
Version: de7e82bcf01fef8b7058936a1022367e2757428d
go build -trimpath -ldflags '-X "main.version=de7e82bcf01fef8b7058936a1022367e2757428d"' -o  dist/lego ./cmd/lego/
root@cachehost ~/lego # rm -rf .lego
root@cachehost ~/lego # LEGO_DEBUG_CLIENT_VERBOSE_ERROR=true CORENETWORKS_LOGIN="apiexample" CORENETWORKS_PASSWORD="xxxxxxx" ./dist/lego -m corenetworks@example.de --dns corenetworks -d testdomain.example.de -d example.de -s https://acme-staging-v02.api.letsencrypt.org/directory run
2024/10/25 10:48:53 No key found for account corenetworks@example.de. Generating a P256 key.
2024/10/25 10:48:53 Saved key to /root/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/corenetworks@example.de/keys/corenetworks@example.de.key
2024/10/25 10:48:53 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf
Do you accept the TOS? Y/n
Y
2024/10/25 10:48:55 [INFO] acme: Registering account for corenetworks@example.de
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/root/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2024/10/25 10:48:56 [INFO] [testdomain.example.de, example.de] acme: Obtaining bundled SAN certificate
2024/10/25 10:48:56 [INFO] [testdomain.example.de] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/14587035213
2024/10/25 10:48:56 [INFO] [example.de] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/14587035223
2024/10/25 10:48:56 [INFO] [testdomain.example.de] acme: Could not find solver for: tls-alpn-01
2024/10/25 10:48:56 [INFO] [testdomain.example.de] acme: Could not find solver for: http-01
2024/10/25 10:48:56 [INFO] [testdomain.example.de] acme: use dns-01 solver
2024/10/25 10:48:56 [INFO] [example.de] acme: Could not find solver for: tls-alpn-01
2024/10/25 10:48:56 [INFO] [example.de] acme: Could not find solver for: http-01
2024/10/25 10:48:56 [INFO] [example.de] acme: use dns-01 solver
2024/10/25 10:48:56 [INFO] [testdomain.example.de] acme: Preparing to solve DNS-01
2024/10/25 10:48:57 [INFO] [testdomain.example.de] acme: Trying to solve DNS-01
2024/10/25 10:48:57 [INFO] [testdomain.example.de] acme: Checking DNS record propagation. [nameservers=185.12.64.1:53,[2a01:4ff:ff00::add:2]:53,185.12.64.2:53]
2024/10/25 10:48:59 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2024/10/25 10:49:04 [INFO] [testdomain.example.de] The server validated our request
2024/10/25 10:49:04 [INFO] [testdomain.example.de] acme: Cleaning DNS-01 challenge
2024/10/25 10:49:05 [INFO] sequence: wait for 1m0s
2024/10/25 10:50:05 [INFO] [example.de] acme: Preparing to solve DNS-01
2024/10/25 10:50:05 [INFO] [example.de] acme: Trying to solve DNS-01
2024/10/25 10:50:05 [INFO] [example.de] acme: Checking DNS record propagation. [nameservers=185.12.64.1:53,[2a01:4ff:ff00::add:2]:53,185.12.64.2:53]
2024/10/25 10:50:07 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2024/10/25 10:50:11 [INFO] [example.de] The server validated our request
2024/10/25 10:50:11 [INFO] [example.de] acme: Cleaning DNS-01 challenge
2024/10/25 10:50:11 [INFO] [testdomain.example.de, example.de] acme: Validations succeeded; requesting certificates
2024/10/25 10:50:11 [INFO] Wait for certificate [timeout: 30s, interval: 500ms]
2024/10/25 10:50:14 [INFO] [testdomain.example.de] Server responded with a certificate.
```

**Comment by ldez** [comment]
I need a run with a wildcard (not a subdomain) + domain for the same root domain.

```
-d *.example.de -d example.de
```

**Comment by heliax01** [comment]
No problem, here you go

```console
root@cachehost ~/lego # LEGO_DEBUG_CLIENT_VERBOSE_ERROR=true CORENETWORKS_LOGIN="apiexample" CORENETWORKS_PASSWORD="xxxxxxx" ./dist/lego -m corenetworks@example.de --dns corenetworks -d *.example.de -d example.de -s https://acme-staging-v02.api.letsencrypt.org/directory run
2024/10/25 11:23:41 [INFO] [*.example.de, example.de] acme: Obtaining bundled SAN certificate
2024/10/25 11:23:42 [INFO] [*.example.de] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/14587035223
2024/10/25 11:23:42 [INFO] [example.de] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/14587436183
2024/10/25 11:23:42 [INFO] [example.de] acme: authorization already valid; skipping challenge
2024/10/25 11:23:42 [INFO] [*.example.de] acme: use dns-01 solver
2024/10/25 11:23:42 [INFO] [*.example.de] acme: Preparing to solve DNS-01
2024/10/25 11:23:42 [INFO] [*.example.de] acme: Trying to solve DNS-01
2024/10/25 11:23:42 [INFO] [*.example.de] acme: Checking DNS record propagation. [nameservers=185.12.64.1:53,[2a01:4ff:ff00::add:2]:53,185.12.64.2:53]
2024/10/25 11:23:44 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2024/10/25 11:23:50 [INFO] [*.example.de] The server validated our request
2024/10/25 11:23:50 [INFO] [*.example.de] acme: Cleaning DNS-01 challenge
2024/10/25 11:23:50 [INFO] [*.example.de, example.de] acme: Validations succeeded; requesting certificates
2024/10/25 11:23:51 [INFO] Wait for certificate [timeout: 30s, interval: 500ms]
2024/10/25 11:23:52 [INFO] [*.example.de] Server responded with a certificate.
```

**Review by dmke — APPROVED** [review]
LGTM

**Pull request merged**
