### PR TITLE
Add DNS provider for VK Cloud

### LINKED ISSUE #1705: Support for provider: VK Cloud
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [X] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Through Traefik

### Link to the DNS provider

https://mcs.mail.ru/

### Link to the API documentation

https://mcs.mail.ru/docs/ru/networks/vnet/networks/publicdns/api

### Additional Notes

I am employee of VK. 
English API documentation is still work in progress.
Pull Request #1706

### PR DESCRIPTION
**Pull request by kluevandrew**
DNS Provider for VK Cloud. Closes #1705

* [x]  add a description to your PR
* [x]  be able to maintain this provider
* [x]  have a homogeneous design with the other providers
* [x]  add tests (units)
* [x]  add tests ("live")
* [x]  add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
* [x]  generate CLI help, documentation, and readme.
* [x]  be able to do `./lego -m your@email.com --dns YOUR_PROVIDER_NAME ....`
* [x]  pass the linter
* [x]  do `go mod tidy`

Stdout of example 
<details>

```bash
$ export VK_CLOUD_PROJECT_ID=<sensetive_information_truncated>
$ export VK_CLOUD_USERNAME=andrey.klyuev@vk.team
$ export VK_CLOUD_PASSWORD=<sensetive_information_truncated>
$ rm -rf .lego && ./lego --email andrey.klyuev@vk.team --dns vkcloud --domains "bet-statistic.ru" --domains "*.bet-statistic.ru"  -s https://acme-staging-v02.api.letsencrypt.org/directory run
2022/08/30 20:09:17 No key found for account andrey.klyuev@vk.team. Generating a P256 key.
2022/08/30 20:09:17 Saved key to /Users/andrey.klyuev/Projects/go-acme/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/andrey.klyuev@vk.team/keys/andrey.klyuev@vk.team.key
2022/08/30 20:09:18 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017-w-v1.3-notice.pdf
Do you accept the TOS? Y/n
Y
2022/08/30 20:09:22 [INFO] acme: Registering account for andrey.klyuev@vk.team
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/Users/andrey.klyuev/Projects/go-acme/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2022/08/30 20:09:22 [INFO] [bet-statistic.ru, *.bet-statistic.ru] acme: Obtaining bundled SAN certificate
2022/08/30 20:09:23 [INFO] [*.bet-statistic.ru] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/3485466163
2022/08/30 20:09:23 [INFO] [bet-statistic.ru] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/3485466173
2022/08/30 20:09:23 [INFO] [*.bet-statistic.ru] acme: use dns-01 solver
2022/08/30 20:09:23 [INFO] [bet-statistic.ru] acme: Could not find solver for: tls-alpn-01
2022/08/30 20:09:23 [INFO] [bet-statistic.ru] acme: Could not find solver for: http-01
2022/08/30 20:09:23 [INFO] [bet-statistic.ru] acme: use dns-01 solver
2022/08/30 20:09:23 [INFO] [*.bet-statistic.ru] acme: Preparing to solve DNS-01
2022/08/30 20:09:24 [INFO] [bet-statistic.ru] acme: Preparing to solve DNS-01
2022/08/30 20:09:24 [INFO] [*.bet-statistic.ru] acme: Trying to solve DNS-01
2022/08/30 20:09:24 [INFO] [*.bet-statistic.ru] acme: Checking DNS record propagation using [100.99.0.231:53 100.99.0.230:53]
2022/08/30 20:09:26 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2022/08/30 20:09:26 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/08/30 20:09:28 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/08/30 20:09:30 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/08/30 20:09:32 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/08/30 20:09:34 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/08/30 20:09:36 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/08/30 20:09:38 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/08/30 20:09:40 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/08/30 20:09:42 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/08/30 20:09:45 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/08/30 20:09:47 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/08/30 20:09:49 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/08/30 20:09:51 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/08/30 20:10:00 [INFO] [*.bet-statistic.ru] The server validated our request
2022/08/30 20:10:00 [INFO] [bet-statistic.ru] acme: Trying to solve DNS-01
2022/08/30 20:10:00 [INFO] [bet-statistic.ru] acme: Checking DNS record propagation using [100.99.0.231:53 100.99.0.230:53]
2022/08/30 20:10:02 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2022/08/30 20:10:09 [INFO] [bet-statistic.ru] The server validated our request
2022/08/30 20:10:09 [INFO] [*.bet-statistic.ru] acme: Cleaning DNS-01 challenge
2022/08/30 20:10:11 [INFO] [bet-statistic.ru] acme: Cleaning DNS-01 challenge
2022/08/30 20:10:14 [INFO] [bet-statistic.ru, *.bet-statistic.ru] acme: Validations succeeded; requesting certificates
2022/08/30 20:10:15 [INFO] [bet-statistic.ru] Server responded with a certificate.
Exiting.
```

</details>

### CODE REVIEW

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests (units)
```shell
make test
```
- [ ] add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help, documentation, and readme.
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`

**Comment by ldez** [comment]
As I changed the code, I will ask you to run again the command:
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```

**Comment by kluevandrew** [comment]
> As I changed the code, I will ask you to run again the command:

ok, i will make it today

**Comment by kluevandrew** [comment]
Unfortunately it stopped working, VK Cloud has not good API which works strange with trailing slash in URL, it required for each request except txt record deletion, i will fix it soon

**Comment by kluevandrew** [comment]
I fixed a bug with trailing slash, merged actual changes from master and now it works

<details>

```
2022/09/02 11:58:57 No key found for account andrey.klyuev@vk.team. Generating a P256 key.
2022/09/02 11:58:57 Saved key to /Users/andrey.klyuev/Projects/go-acme/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/andrey.klyuev@vk.team/keys/andrey.klyuev@vk.team.key
2022/09/02 11:58:57 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017-w-v1.3-notice.pdf
Do you accept the TOS? Y/n
Y
2022/09/02 11:59:00 [INFO] acme: Registering account for andrey.klyuev@vk.team
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/Users/andrey.klyuev/Projects/go-acme/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2022/09/02 11:59:00 [INFO] [bet-statistic.ru, *.bet-statistic.ru] acme: Obtaining bundled SAN certificate
2022/09/02 11:59:01 [INFO] [*.bet-statistic.ru] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/3512654573
2022/09/02 11:59:01 [INFO] [bet-statistic.ru] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/3512654583
2022/09/02 11:59:01 [INFO] [*.bet-statistic.ru] acme: use dns-01 solver
2022/09/02 11:59:01 [INFO] [bet-statistic.ru] acme: Could not find solver for: tls-alpn-01
2022/09/02 11:59:01 [INFO] [bet-statistic.ru] acme: Could not find solver for: http-01
2022/09/02 11:59:01 [INFO] [bet-statistic.ru] acme: use dns-01 solver
2022/09/02 11:59:01 [INFO] [*.bet-statistic.ru] acme: Preparing to solve DNS-01
2022/09/02 11:59:05 [INFO] [bet-statistic.ru] acme: Preparing to solve DNS-01
2022/09/02 11:59:05 [INFO] [*.bet-statistic.ru] acme: Trying to solve DNS-01
2022/09/02 11:59:05 [INFO] [*.bet-statistic.ru] acme: Checking DNS record propagation using [10.73.0.1:53 77.37.251.33:53 77.37.255.30:53]
2022/09/02 11:59:07 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2022/09/02 11:59:07 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/09/02 11:59:09 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/09/02 11:59:11 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/09/02 11:59:14 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/09/02 11:59:16 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/09/02 11:59:18 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/09/02 11:59:20 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/09/02 11:59:22 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/09/02 11:59:24 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/09/02 11:59:26 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/09/02 11:59:31 [INFO] [*.bet-statistic.ru] The server validated our request
2022/09/02 11:59:31 [INFO] [bet-statistic.ru] acme: Trying to solve DNS-01
2022/09/02 11:59:31 [INFO] [bet-statistic.ru] acme: Checking DNS record propagation using [10.73.0.1:53 77.37.251.33:53 77.37.255.30:53]
2022/09/02 11:59:33 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2022/09/02 11:59:40 [INFO] [bet-statistic.ru] The server validated our request
2022/09/02 11:59:40 [INFO] [*.bet-statistic.ru] acme: Cleaning DNS-01 challenge
2022/09/02 11:59:40 [INFO] [bet-statistic.ru] acme: Cleaning DNS-01 challenge
2022/09/02 11:59:41 [INFO] [bet-statistic.ru, *.bet-statistic.ru] acme: Validations succeeded; requesting certificates
2022/09/02 11:59:42 [INFO] [bet-statistic.ru] Server responded with a certificate.
Exiting.
```

</details>

**Comment by ldez** [comment]
I implemented a simpler solution.

the only case that can be a problem is on the delete.

**Comment by ldez** [comment]
I rethought the problem again and mimicked the go1.19 API.

**Comment by kluevandrew** [comment]
> I rethought the problem again and mimicked the go1.19 API.

Great solution, shall i test it again?

PS. I going to push trailing slash problem into DNS API team, hope they can fix it fast

**Comment by ldez** [comment]
> Great solution, shall i test it again?

It's the same code as previously so I think you don't need to test it again.
I was just waiting for your feedback.

> I going to push trailing slash problem into DNS API team, hope they can fix it fast

I will merge now unless you think that we have to wait for your DNS API team.

**Comment by kluevandrew** [comment]
> It's the same code as previously so I think you don't need to test it again. I was just waiting for your feedback.

It's not, something went wrong) I will check and fix it

```
[*.bet-statistic.ru] [*.bet-statistic.ru] acme: error presenting token: vkcloud: unable to fetch dns zones: request: Get "/public-dns/v2/dns/": unsupported protocol scheme ""
```

> I will merge now unless you think that we have to wait for your DNS API team.

I think you can merge it after fix and not wait for DNS API team, when they fix api i will open new pull request with updates

**Comment by kluevandrew** [comment]
Now it works, problem was in BaseURL parsing, it looses scheme and domain on second parse 

<details>

```
2022/09/02 22:55:08 [INFO] [bet-statistic.ru, *.bet-statistic.ru] acme: Obtaining bundled SAN certificate
2022/09/02 22:55:09 [INFO] [*.bet-statistic.ru] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/3517180543
2022/09/02 22:55:09 [INFO] [bet-statistic.ru] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/3517180553
2022/09/02 22:55:09 [INFO] [*.bet-statistic.ru] acme: use dns-01 solver
2022/09/02 22:55:09 [INFO] [bet-statistic.ru] acme: Could not find solver for: tls-alpn-01
2022/09/02 22:55:09 [INFO] [bet-statistic.ru] acme: Could not find solver for: http-01
2022/09/02 22:55:09 [INFO] [bet-statistic.ru] acme: use dns-01 solver
2022/09/02 22:55:09 [INFO] [*.bet-statistic.ru] acme: Preparing to solve DNS-01
2022/09/02 22:55:25 [INFO] [bet-statistic.ru] acme: Preparing to solve DNS-01
2022/09/02 22:55:27 [INFO] [*.bet-statistic.ru] acme: Trying to solve DNS-01
2022/09/02 22:55:27 [INFO] [*.bet-statistic.ru] acme: Checking DNS record propagation using [10.73.0.1:53 77.37.251.33:53 77.37.255.30:53]
2022/09/02 22:55:29 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2022/09/02 22:55:29 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/09/02 22:55:31 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/09/02 22:55:33 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/09/02 22:55:35 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/09/02 22:55:37 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/09/02 22:55:39 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/09/02 22:55:41 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/09/02 22:55:43 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/09/02 22:55:45 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/09/02 22:55:47 [INFO] [*.bet-statistic.ru] acme: Waiting for DNS record propagation.
2022/09/02 22:55:53 [INFO] [*.bet-statistic.ru] The server validated our request
2022/09/02 22:55:53 [INFO] [bet-statistic.ru] acme: Trying to solve DNS-01
2022/09/02 22:55:53 [INFO] [bet-statistic.ru] acme: Checking DNS record propagation using [10.73.0.1:53 77.37.251.33:53 77.37.255.30:53]
2022/09/02 22:55:55 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2022/09/02 22:55:55 [INFO] [bet-statistic.ru] The server validated our request
2022/09/02 22:55:55 [INFO] [*.bet-statistic.ru] acme: Cleaning DNS-01 challenge
2022/09/02 22:57:20 [INFO] [bet-statistic.ru] acme: Cleaning DNS-01 challenge
2022/09/02 22:57:23 [INFO] [bet-statistic.ru, *.bet-statistic.ru] acme: Validations succeeded; requesting certificates
2022/09/02 22:57:23 [INFO] [bet-statistic.ru] Server responded with a certificate.
Exiting.
```

</details>

**Review by ldez — APPROVED** [review]
LGTM :+1:

**Pull request merged**
