### PR TITLE
Migrate to go module (v3.0.0) 

### LINKED ISSUE #938: Converting project to modules
Recently, it's been tough in the [Terraform ACME provider](https://github.com/terraform-providers/terraform-provider-acme) to maintain properly synced dependencies with lego on part of the project has not converted to modules yet.

This leads to issues at times where the DNS providers will update to a dependency past a version later than is currently specified in our `go.mod`, which will lead met to having to hunt down the right dependency in the lego `Gopkg.lock` and fixing the issue manually. This, of course, does not also help when working with dependency issues that don't cause build errors.

I recently tried to convert the project to modules and have the result in https://github.com/vancluever/lego/commit/e633c88103424190b27b8a7c9a1296024d64bbae. The process was actually very painless, only entailing the steps outlined in the commit (init, change the package name from the old location, add one replace line, and run tidy).

There also does not seem to be much in the way of CI tooling that depends on dep, so I don't think anything else needs to be modified. Modules may need to be vendored (and an exported `GOFLAGS=-mod=vendor` added as well) to help with rate-limiting on CI, however.

If there's no other issues, or any other reason why #706 stalled (aside from the last comment which mentions some issues with auroadns, which I did not run into - it seems that dependency has changed so that's no longer an issue?), can we look into getting this done? I would be able to help make the changes necessary to get it done and put in the PR.

Incidentally, it looks like there's some issues that I need to unpack in Terraform itself before this is 100% fixed, on part to Azure fun, so there's probably not a huge rush on my part as I will probably just continue with what we have kept doing for now.

### PR DESCRIPTION
**Pull request by ldez**
Migrate to go module.
Create a v3.

The new import path is `github.com/go-acme/lego/v3/`

Closes #706
Fixes #938

----
**IMPORTANT**

The 2 commits must be kept: the merge be done with a **rebase** (neither merge commit nor squash)

2 commits:
- one for the future tagged version
- one for after the release (`detach`)

### CODE REVIEW

**Comment by mholt** [comment]
I can't leave a review because my browser tab crashes, but what I've seen of the code LGTM.

**Comment by wyattjoh** [comment]
Maybe I'm not too familiar with modules yet, but after running `make build` from this branch, it seems to have modified the `go.sum` file:

```diff
diff --git a/go.sum b/go.sum
index c7f21a7..ea0a2f9 100644
--- a/go.sum
+++ b/go.sum
@@ -4,18 +4,28 @@ cloud.google.com/go v0.38.0 h1:ROfEUZz+Gh5pa62DJWXSaonyu3StP6EA6lPEXPI6mCo=
 cloud.google.com/go v0.38.0/go.mod h1:990N+gfupTy94rShfmMCWGDn0LpTmnzTp2qbd1dvSRU=
 contrib.go.opencensus.io/exporter/ocagent v0.4.12 h1:jGFvw3l57ViIVEPKKEUXPcLYIXJmQxLUh6ey1eJhwyc=
 contrib.go.opencensus.io/exporter/ocagent v0.4.12/go.mod h1:450APlNTSR6FrvC3CTRqYosuDstRB9un7SOx2k/9ckA=
+github.com/Azure/azure-sdk-for-go v32.0.0+incompatible h1:lkD8YqWFj4DVw65CHwtjOtTnlMD2LLy9z/f8I+BBsVM=
 github.com/Azure/azure-sdk-for-go v32.0.0+incompatible/go.mod h1:9XXNKU+eRnpl9moKnB4QOLf1HestfXbmab5FXxiDBjc=
 github.com/Azure/go-autorest/autorest v0.1.0/go.mod h1:AKyIcETwSUFxIcs/Wnq/C+kwCtlEYGUVd7FPNb2slmg=
+github.com/Azure/go-autorest/autorest v0.5.0 h1:Mlm9qy2fpQ9MvfyI41G2Zf5B4CsgjjNbLOWszfK6KrY=
 github.com/Azure/go-autorest/autorest v0.5.0/go.mod h1:9HLKlQjVBH6U3oDfsXOeVc56THsLPw1L03yban4xThw=
 github.com/Azure/go-autorest/autorest/adal v0.1.0/go.mod h1:MeS4XhScH55IST095THyTxElntu7WqB7pNbZo8Q5G3E=
+github.com/Azure/go-autorest/autorest/adal v0.2.0 h1:7IBDu1jgh+ADHXnEYExkV9RE/ztOOlxdACkkPRthGKw=
 github.com/Azure/go-autorest/autorest/adal v0.2.0/go.mod h1:MeS4XhScH55IST095THyTxElntu7WqB7pNbZo8Q5G3E=
+github.com/Azure/go-autorest/autorest/azure/auth v0.1.0 h1:YgO/vSnJEc76NLw2ecIXvXa8bDWiqf1pOJzARAoZsYU=
 github.com/Azure/go-autorest/autorest/azure/auth v0.1.0/go.mod h1:Gf7/i2FUpyb/sGBLIFxTBzrNzBo7aPXXE3ZVeDRwdpM=
+github.com/Azure/go-autorest/autorest/azure/cli v0.1.0 h1:YTtBrcb6mhA+PoSW8WxFDoIIyjp13XqJeX80ssQtri4=
 github.com/Azure/go-autorest/autorest/azure/cli v0.1.0/go.mod h1:Dk8CUAt/b/PzkfeRsWzVG9Yj3ps8mS8ECztu43rdU8U=
+github.com/Azure/go-autorest/autorest/date v0.1.0 h1:YGrhWfrgtFs84+h0o46rJrlmsZtyZRg470CqAXTZaGM=
 github.com/Azure/go-autorest/autorest/date v0.1.0/go.mod h1:plvfp3oPSKwf2DNjlBjWF/7vwR+cUD/ELuzDCXwHUVA=
 github.com/Azure/go-autorest/autorest/mocks v0.1.0/go.mod h1:OTyCOPRA2IgIlWxVYxBee2F5Gr4kF2zd2J5cFRaIDN0=
+github.com/Azure/go-autorest/autorest/to v0.2.0 h1:nQOZzFCudTh+TvquAtCRjM01VEYx85e9qbwt5ncW4L8=
 github.com/Azure/go-autorest/autorest/to v0.2.0/go.mod h1:GunWKJp1AEqgMaGLV+iocmRAJWqST1wQYhyyjXJ3SJc=
+github.com/Azure/go-autorest/autorest/validation v0.1.0 h1:ISSNzGUh+ZSzizJWOWzs8bwpXIePbGLW4z/AmUFGH5A=
 github.com/Azure/go-autorest/autorest/validation v0.1.0/go.mod h1:Ha3z/SqBeaalWQvokg3NZAlQTalVMtOIAs1aGK7G6u8=
+github.com/Azure/go-autorest/logger v0.1.0 h1:ruG4BSDXONFRrZZJ2GUXDiUyVpayPmb1GnWeHDdaNKY=
 github.com/Azure/go-autorest/logger v0.1.0/go.mod h1:oExouG+K6PryycPJfVSxi/koC6LSNgds39diKLz7Vrc=
+github.com/Azure/go-autorest/tracing v0.1.0 h1:TRBxC5Pj/fIuh4Qob0ZpkggbfT8RC0SubHbpV3p4/Vc=
 github.com/Azure/go-autorest/tracing v0.1.0/go.mod h1:ROEEAFwXycQw7Sn3DXNtEedEvdeRAgDr0izn4z5Ij88=
 github.com/BurntSushi/toml v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
 github.com/BurntSushi/toml v0.3.1/go.mod h1:xHWCNGjB5oqiDr8zfno3MHue2Ht5sIBksp03qcyfWMU=
```

Is this expected?

**Comment by mholt** [comment]
Actually yes, that seems correct: `go mod tidy` should ensure that the `go.sum` file has checkums for both the module code and the go.mod file. (I'm not sure what causes half the checksums to go missing...)

**Comment by ldez** [comment]
@wyattjoh are you using go1.11 or go1.12?

**Comment by wyattjoh** [comment]
```bash
$ go version
go version go1.12.7 darwin/amd64
```

**Comment by ldez** [comment]
:thinking: I don't reproduce with:
```
$ go version
go version go1.12.7 linux/amd64
```

I also try with go1.11.12 same results: no diff.

**Comment by ldez** [comment]
I cleaned my module cache and now I reproduce :tada:

**Comment by wyattjoh** [comment]
Looks like there is still some build errors, not sure how to resolve

**Comment by ldez** [comment]
It's because I tried to use https://proxy.golang.org/

I reverted.

**Comment by ldez** [comment]
Travis have some problem: https://www.traviscistatus.com/

> We are receiving reports of Linux and Windows builds where network connectivity is unreliable, intermittently working or slow. We are opening this incident to acknowledge the issue and also keep you posted on our work to solve it. Thank you for your patience.

**Pull request merged**
