### PR TITLE
Add DNS provider for LuaDNS

### PR DESCRIPTION
**Pull request by wezm**
This PR adds a `challenge.Provider` implementation for [LuaDNS](https://luadns.com/). I've tested the implementation against my own account and successfully created certificates against the Let's Encrypt staging server.

### CODE REVIEW

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests (units)
```shell
make test
```
- [ ] add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add the provider to the [readme.md](https://github.com/go-acme/lego#dns-providers)
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help and documentation
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`

**Comment by wezm** [comment]
Thanks for the review. Sorry if I missed this checklist. I read through CONTRIBUTING.md before opening the PR but didn't see it referenced there.

* I'm happy to maintain the provider.
* I already ran `make generate-dns` and committed the changes.
* The linter complains about package names of the tests and some comments in other packages not ending in full-stop. The same errors were reported before my changes.
* It looks like I need to tweak it to handle wildcard domains. I probably won't be able to get to this until the weekend.

**Comment by ldez** [comment]
If the DNS provider doesn't support multiple records for one domain, you will have an issue with wildcard. In this case (and only in this case) you have to add the following lines in your provider:

```go
// Sequential All DNS challenges for this provider will be resolved sequentially.
// Returns the interval between each iteration.
func (d *DNSProvider) Sequential() time.Duration {
	return d.config.SequenceInterval
}
```

**Comment by wezm** [comment]
I’m pretty confident it supports multiple records. Just need to do some more testing.

**Comment by wezm** [comment]
Righto I tweaked it and verified that issuing wildcard + toplevel domain works simultaneously; CI build is passing.

```
$ rm -r .lego
$ LUADNS_API_USERNAME=wes@binarytrance.com LUADNS_API_TOKEN_FILE=luadns_api_key dist/lego --server=https://acme-staging-v02.api.letsencrypt.org/directory -a -d \*.linkedlist.org -d linkedlist.org --dns luadns --email wes@binarytrance.com run
2020/05/10 09:42:59 No key found for account wes@binarytrance.com. Generating a P384 key.
2020/05/10 09:42:59 Saved key to /home/wmoore/Source/Go/src/github.com/go-acme/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/wes@binarytrance.com/keys/wes@binarytrance.com.key
2020/05/10 09:42:59 [INFO] acme: Registering account for wes@binarytrance.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/home/wmoore/Source/Go/src/github.com/go-acme/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2020/05/10 09:43:00 [INFO] [*.linkedlist.org, linkedlist.org] acme: Obtaining bundled SAN certificate
2020/05/10 09:43:01 [INFO] [*.linkedlist.org] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/55454503
2020/05/10 09:43:01 [INFO] [linkedlist.org] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/55454504
2020/05/10 09:43:01 [INFO] [*.linkedlist.org] acme: use dns-01 solver
2020/05/10 09:43:01 [INFO] [linkedlist.org] acme: Could not find solver for: tls-alpn-01
2020/05/10 09:43:01 [INFO] [linkedlist.org] acme: Could not find solver for: http-01
2020/05/10 09:43:01 [INFO] [linkedlist.org] acme: use dns-01 solver
2020/05/10 09:43:01 [INFO] [*.linkedlist.org] acme: Preparing to solve DNS-01
2020/05/10 09:43:02 [INFO] [linkedlist.org] acme: Preparing to solve DNS-01
2020/05/10 09:43:03 [INFO] [*.linkedlist.org] acme: Trying to solve DNS-01
2020/05/10 09:43:03 [INFO] [*.linkedlist.org] acme: Checking DNS record propagation using [10.0.0.1:53]
2020/05/10 09:43:03 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
2020/05/10 09:43:03 [INFO] [*.linkedlist.org] acme: Waiting for DNS record propagation.
2020/05/10 09:43:10 [INFO] [*.linkedlist.org] The server validated our request
2020/05/10 09:43:10 [INFO] [linkedlist.org] acme: Trying to solve DNS-01
2020/05/10 09:43:10 [INFO] [linkedlist.org] acme: Checking DNS record propagation using [10.0.0.1:53]
2020/05/10 09:43:10 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
2020/05/10 09:43:10 [INFO] [linkedlist.org] The server validated our request
2020/05/10 09:43:10 [INFO] [*.linkedlist.org] acme: Cleaning DNS-01 challenge
2020/05/10 09:43:11 [INFO] [linkedlist.org] acme: Cleaning DNS-01 challenge
2020/05/10 09:43:12 [INFO] [*.linkedlist.org, linkedlist.org] acme: Validations succeeded; requesting certificates
2020/05/10 09:43:13 [INFO] [*.linkedlist.org] Server responded with a certificate.
```

**Pull request merged**
