### PR TITLE
Add support for DNS-challenge for Scaleway

### PR DESCRIPTION
**Pull request by remyleone**
This PR adds support for Online DNS : https://console.online.net/en/api/
Disclaimer: I work for Online.net (Scaleway)

### CODE REVIEW

**Comment by sieben** [comment]
@ldez Thanks a lot. I'm working on it.

**Comment by sieben** [comment]
What do you mean when you say that " have a homogeneous design with the other providers" is there a list of requirements?

**Comment by ldez** [comment]
@sieben any news?

**Comment by sieben** [comment]
I'm working on it, I'm a golang beginner at the moment so sorry I'm not going very fast...

**Comment by ldez** [comment]
@sieben If you need help I can do the Go code (tests and provider) and you will execute the tests and the commands, WDYT?

**Comment by sieben** [comment]
@ldez Thanks a lot for your support :D I will keep you updated when I got something working and internally approved. :muscle:

**Comment by ldez** [comment]
@sieben any news?

**Comment by sieben** [comment]
Got a lot of work in parallel. Thanks for your attention. Still working on it with my colleagues.

**Comment by ldez** [comment]
@sieben any news?

The new list of requirements:
- [x] add a description to your PR
- [x] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests ("live" and units)
```shell
make test
```
- [ ] add the provider to the [readme.md](https://github.com/xenolf/lego#dns-providers)
- [ ] add a [provider descriptor](https://github.com/xenolf/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help and documentation
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf ./lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```

**Comment by ldez** [comment]
@sieben any news?

**Comment by ldez** [comment]
@remyleone No progress after 7 months, then are you or your colleagues able to complete this PR?

Ask me if you need help.

**Comment by remyleone** [comment]
@vanonox @jerjako What do you think? Do you have go code for the online API console?

**Comment by ldez** [comment]
@remyleone @vanonox @jerjako last call before closing this PR :wave:

**Comment by vanonox** [comment]
@ldez hi , thx for the remind, didn't see the previous message from @remyleone 
i will do it this week

**Comment by vanonox** [comment]
hi @ldez , i have open a PR on my name here https://github.com/go-acme/lego/pull/1047
you may close this one

**Pull request closed without merging**
