### PR TITLE
Add support for building snaps

### PR DESCRIPTION
**Pull request by igorljubuncic**
I've opened this PR to request support for building a snap package of lego.

To give you a bit more context, snaps are cross-distro Linux software packages, supported on LTS and non-LTS Ubuntus from 14.04, as well as Debian, Manjaro, Fedora, OpenSUSE, Arch, and many others distributions. Snaps come with automatic updates, which could be quite useful for applications with focus on security and privacy, like lego. Also, we have a considerable audience of users in the Snap Store (snapcraft.io/store), so this could give extra exposure to your project.

Snaps can be built locally using the snapcraft cli tool, build/CI systems (e.g. Travis) or online via build.snapcraft.io, which is a free service for snap users.

Now, the technobabble to get a snap built locally with snapcraft:

1. Install snapcraft tool and checkout the forked repo that has the snapcraft.yaml file for building the snap.

```bash
snap install snapcraft --classic --beta

git clone https://github.com/igorljubuncic/lego.git
cd lego
git checkout add-snapcraft

snapcraft
```

This command will generate a `<lego-version>.snap` file, something like `lego_1.0_amd64.snap`.

2. Test the snap.

Lego can be installed and tested locally with:

```bash
snap install lego_1.0_amd64.snap --dangerous
```

The `--dangerous` flag is necessary because the snap isn't in the store yet, and isn't signed.

Once installed, the lego command can be executed, e.g.: `snap run lego <options>`

3. Register snap name and upload snap to the store.

- Register a developer account in the snap store https://snapcraft.io/account.
- Register the lego name in the store. 

```bash
snapcraft login
snapcraft register
```

- Upload a built snap to the store. We use channels to differentiate risk levels - edge, beta, candidate, stable. Edge is typically used to host the latest build from git master. You can promote to other channels once you're happy with the tests/

```bash
snapcraft push lego_1.0_amd64.snap --release edge
```

4. Clean test install.

You can do this on a clean machine (install from store and run). No need for the --dangerous flag anymore.

```bash
snap install lego --edge
```

Once (and if) you are happy, you can push a stable release to the stable channel, update the store page, and promote the application online. We can help there, and we'd be glad to feature your application in our store. We can also help with any questions or issues you may have.

### CODE REVIEW

**Comment by ldez** [comment]
Hi, we use Goreleaser, maybe you can integrate this into our release system https://goreleaser.com/snapcraft/ ?

**Comment by igorljubuncic** [comment]
I will check. There's this guide from the Go Releaser creator:
https://carlosbecker.com/posts/goreleaser-snap-travis/

But I do have some questions around that, and I want clarify them first.

**Comment by ldez** [comment]
I tried your current file:
```bash
docker run --rm -v "$PWD":/build -w /build snapcore/snapcraft bash -c "apt update && snapcraft"
```
[ref:Build on Docker](https://docs.snapcraft.io/build-on-docker/4158)

### Problems:

#### Pull

It failed to pull (it's not a real pull but a `go get`), because the lego command is into `cmd/lego/`
```
Failed to run 'go get -t -d ./github.com/xenolf/lego/...' for 'lego': Exited with code 1.
```

#### Go version

In the Docker image, the Go version is 1.6...

I tried to use `go-channel` but:
```
Failed to load plugin: properties failed to load for lego: Additional properties are not allowed ('go-channel' was unexpected)
```
[ref: section Parts](https://snapcraft.io/first-snap/golang/linux/package)
[ref: Go plugin](https://docs.snapcraft.io/the-go-plugin/8505)

Another way is to use the community part `[go]`, but this part build/compile Go from sources...  Seems not a good idea.

#### Build command

To build lego, you have to call `make build`, or at least a specific Go command, to add the version into the binary.

### Conclusion

In my opinion, the Go plugin is obsolete/inappropriate because it uses some erroneous abstractions and does not have enough customizable options.

The best way to do this now is to build the snap as if it was not a Go program, it is possible but not very simple.

Maybe goreleaser creates a better abstraction and solve those issues.

So, **for now**, my conclusions are: snap is a good idea but some problems need to be resolved before easily building snap for Go programs.

**Comment by ldez** [comment]
I tested Snap and Goreleaser on a side project and it's a better abstraction than Snapcraft Go plugin.
The confinement is the major issue, we need to evaluate which [interfaces](https://docs.snapcraft.io/interface-management/6154) we need (if they are available) or if we need a ["classic" Confinement](https://snapcraft.io/blog/demystifying-snap-confinement)

**Comment by ldez** [comment]
I close for now.

**Pull request closed without merging**
