### PR TITLE
bunny: fix zone detection

### LINKED ISSUE #2011: Bunny Provider for the DNS challenge is non-functional
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

A working certificate message.

### What did you see instead?

```
root@dev:~/docker-services# docker run -e BUNNY_API_KEY=[removed] goacme/lego --email [removed] --dns bunny --domains [removed] --server "https://acme-staging-v02.api.letsencrypt.org/directory" --accept-tos --dns-timeout=90  --dns.resolvers=1.1.1.1 run
2023/09/03 13:28:13 No key found for account [removed]. Generating a P256 key.
2023/09/03 13:28:13 Saved key to /.lego/accounts/acme-staging-v02.api.letsencrypt.org/[removed]/keys/[removed].key
2023/09/03 13:28:13 [INFO] acme: Registering account for [removed]
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2023/09/03 13:28:13 [INFO] [[removed]] acme: Obtaining bundled SAN certificate
2023/09/03 13:28:13 [INFO] [[removed]] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/8081289974
2023/09/03 13:28:13 [INFO] [[removed]] acme: Could not find solver for: tls-alpn-01
2023/09/03 13:28:13 [INFO] [[removed]] acme: Could not find solver for: http-01
2023/09/03 13:28:13 [INFO] [[removed]] acme: use dns-01 solver
2023/09/03 13:28:13 [INFO] [[removed]] acme: Preparing to solve DNS-01
2023/09/03 13:28:14 [INFO] [[removed]] acme: Cleaning DNS-01 challenge
2023/09/03 13:28:14 [WARN] [[removed]] acme: cleaning up failed: bunny: could not find DNSZone zone=_acme-challenge.[removed] 
2023/09/03 13:28:14 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/8081289974
2023/09/03 13:28:14 Could not obtain certificates:
	error: one or more domains had a problem:
[[removed]] [[removed]] acme: error presenting token: bunny: could not find DNSZone zone=_acme-challenge.[removed]
```

### How do you use lego?

Binary

### Reproduction steps

See What did you see instead as it has reproduction steps.

Bunny.net provides a free trial of 14 days if you want to test yourself.

### Version of lego

```console
root@dev:~/docker-services# docker run goacme/lego --version
lego version 4.14.0 linux/amd64
```

### Logs

<details>

Refer to what you see instead section
</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

### PR DESCRIPTION
**Pull request by ldez**
fixes #2011

### CODE REVIEW

**Comment by TECHNOFAB11** [comment]
Quick feedback, tried this but it errors out with 
```
[test.tecf.de] [test.tecf.de] acme: error presenting token: bunny: could not find DNSZone zone=_acme-challenge.test
```

**Comment by ldez** [comment]
> Quick feedback, tried this but it errors out with

yes, my fault, I updated the code.

**Comment by TECHNOFAB11** [comment]
It seems to work, the TXT records are set and it's waiting for dns propagation

**Comment by ldez** [comment]
the fix should be good now.

**Comment by TECHNOFAB11** [comment]
The propagation timed out but I think thats because I'm currently having some funky DNS stuff going on :D

**Comment by ldez** [comment]
I didn't see your answer :smile:

So I waiting for your approval.

**Review by TECHNOFAB11 — APPROVED** [review]
lgtm :)

**Comment by ldez** [comment]
Github refresh is random: my answer was about [this message](https://github.com/go-acme/lego/pull/2012#issuecomment-1704321923) but when I posted my message you already posted another message :smile:

**Comment by ldez** [comment]
@kengodwin is it OK for you?

We always find solutions, you will not need to use the exec provider :smile:

**Comment by kengodwin** [comment]
> @kengodwin is it OK for you?
> 
> We always find solutions, you will not need to use the exec provider 😄

I'm still waiting on DNS propagation.

**Comment by TECHNOFAB11** [comment]
Hmm, the propagation detection seems to be broken aswell. `dig` shows the TXT records for me but lego does not seem to detect them

**Comment by kengodwin** [comment]
Yeah I'm experiencing the same. The txt record is in Bunny.net and dig but not being detected by lego.

**Comment by ldez** [comment]
can you check manually with TXT query?

**Comment by TECHNOFAB11** [comment]
> can you check manually with TXT query?

`dig _acme-challenge.test.tecf.de TXT` shows the entries fine if thats what you mean. Feel free to try yourself on that domain if you mean something different, it's just for testing anyways :)

**Comment by kengodwin** [comment]
> can you check manually with TXT query?

µ dig _acme-challenge.test.dev-ops.minfra.space @1.1.1.1 TXT                                                                                                                    [0] : 0.062s 

; <<>> DiG 9.18.12-0ubuntu0.22.04.2-Ubuntu <<>> _acme-challenge.test.dev-ops.minfra.space @1.1.1.1 TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27926
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;_acme-challenge.test.dev-ops.minfra.space. IN TXT

;; ANSWER SECTION:
_acme-challenge.test.dev-ops.minfra.space. 20 IN TXT "ygXATbU3UKOifVkPG7OWVFLAVS5c-M1PTaJIW0HigFo"

;; Query time: 15 msec
;; SERVER: 1.1.1.1#53(1.1.1.1) (UDP)
;; WHEN: Sun Sep 03 10:51:56 EDT 2023
;; MSG SIZE  rcvd: 126

**Comment by ldez** [comment]
can you provide the error message?

**Comment by kengodwin** [comment]
> can you provide the error message?

[test.dev-ops.minfra.space] propagation: time limit exceeded: last error: could not determine authoritative nameservers

I can bypass this like I do for my traefik setup if that is the solution I believe.

**Comment by ldez** [comment]
@TECHNOFAB11 have you the same error?

**Comment by TECHNOFAB11** [comment]
> @TECHNOFAB11 have you the same error?

just reran it,  yes its the same error

**Comment by ldez** [comment]
It's because the DNS server has an unexpected behavior: it's authoritative but doesn't have NS...

Cleary it's a Bunny DNS problem.

```console
$ drill test.dev-ops.minfra.space NS    
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 9552
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; test.dev-ops.minfra.space.   IN      NS

;; ANSWER SECTION:

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 39 msec
;; SERVER: 192.168.1.1
;; WHEN: Sun Sep  3 16:57:21 2023
;; MSG SIZE  rcvd: 43
```

```
$ drill _acme-challenge.test.tecf.de NS 
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 21436
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; _acme-challenge.test.tecf.de.        IN      NS

;; ANSWER SECTION:

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 14 msec
;; SERVER: 2a02:842b:5a8:b601::1
;; WHEN: Sun Sep  3 16:57:54 2023
;; MSG SIZE  rcvd: 46
```

**Comment by kengodwin** [comment]
Yeah there is a reason I only use BunnyDNS and other "low end" providers for personal stuff with no commercial viability lol

**Comment by TECHNOFAB11** [comment]
Weird that it randomly changed though, worked fine for a long time

**Comment by kengodwin** [comment]
> Weird that it randomly changed though, worked fine for a long time

I feel the same way about the people I switched off of before using Bunny for DNS. Unfortunately, this get broken from time to time.

**Comment by ldez** [comment]
> Are we just bypassing the search for the authoritative NS and calling it a day with the command line flag?

I'm not sure what you mean, but you can disable the propagation check, this can lead to an error related to slow propagation (the TXT records will not be present when LE checks the record).

**Comment by kengodwin** [comment]
> > Are we just bypassing the search for the authoritative NS and calling it a day with the command line flag?
> 
> I'm not sure what you mean, but you can disable the propagation check, this can lead to an error related to slow propagation (the TXT records will not be present when LE checks the record).

Yeah that is how I've been dealing with it since I switched to Bunny yesterday.

**Comment by ldez** [comment]
So we will say it's OK because I'm not able to fix a problem related to Bunny DNS itself :smile_cat:

**Comment by kengodwin** [comment]
> So we will say it's OK because I'm not able to fix a problem related to Bunny DNS itself 😸

Seems fair. Do you want me to raise an issue with Bunny support and see what they say?

**Comment by ldez** [comment]
Thank you @TECHNOFAB11 for the tests and be present to maintain this provider :heart:

**Comment by kengodwin** [comment]
> yes, it can be a good idea. Keep us informed about their answer.

Will do.

**Comment by kengodwin** [comment]
Bunny support says they will fix something I noted that is possibly a fix for this but with no ETA.

**Comment by dmke** [comment]
Soo... do we want to wait for the response of Bunny, or merge this PR, or both?

**Comment by ldez** [comment]
I don't know I have the same questions.
Maybe I can create a conditional behavior: if the domain is equal to the zone then split the zone.

**Comment by ldez** [comment]
any news from Bunny?

If not we will merge the PR.

**Comment by kengodwin** [comment]
> any news from Bunny?
> 
> If not we will merge the PR.

No news other than the promise they'll fix it at some point. Feel free to merge.

**Comment by ldez** [comment]
so @dmke will merge the PR.

**Review by dmke — APPROVED** [review]
LGTM

**Pull request merged**
