### PR TITLE
namedotcom: get the actual registered domain so we can remove just that from the hostname to be created

### LINKED ISSUE #543: namedotcom backend removing subdomains when it shouldn't?
I wonder if https://github.com/containous/traefik/issues/3306 is an issue in lego?

when using traefik to request certs for `tower.ona.im,traefik.tower.ona.im,port.tower.ona.im,kibana.tower.ona.im` it fails, as the code is checking for DNS records on `_acme-challenge.traefik.tower.ona.im`, but the TXT records are all on `_acme-challenge.ona.im`.

```
infra_traefik.1.2m6q8iyogej8@TOWER-SL    | time="2018-05-11T05:13:40Z" level=error msg="Unable to obtain ACME certificate for domains \"traefik.tower.ona.im\" detected thanks to rule \"Host:traefik.tower.ona.im\" : cannot obtain certificates map[traefik.tower.ona.im:acme: Error 403 - urn:ietf:params:acme:error:unauthorized - No TXT record found at _acme-challenge.traefik.tower.ona.im]"
```

```
_acme-challenge.ona.im.	300	IN	TXT	"HOTLkE6PtlvX3LXaD0CgQ0FONdvLag7KPsmWp9tGXdM"
_acme-challenge.ona.im.	300	IN	TXT	"jpdEr5mFP50n6GpxoJOz5oQ39_c-zufbILqZ0sjd97s"
_acme-challenge.ona.im.	300	IN	TXT	"ME7CeT50yrcWeAW2tOFuHAZ19DSdMLg5NBsXYY9SZO4"
_acme-challenge.ona.im.	300	IN	TXT	"KtcmyVvM7vq9_-FFV1Gkr1pvo6jfJ97LNxHXX7NfbcU"

```

### PR DESCRIPTION
**Pull request by SvenDowideit**
Fixes #543
Closes #886

### CODE REVIEW

**Comment by mholt** [comment]
Thanks -- have you tested this? And does it fix 543?

**Comment by SvenDowideit** [comment]
I'm having a horror time with DNS lag today - I'll try again tomorrow - or maybe @patramsey can help out

**Comment by SvenDowideit** [comment]
@mholt yes, and no :)

https://github.com/namedotcom/go/issues/2#issuecomment-389994918 made me add a 4 minute delay to the challenge - and then... yes, it does finally work.

so this PR is what's needed for name.com's API to set the TXT on the right hostname, but their update delay means that lego needs a `delay-challenge-test` cmdline option :/

so my hacked version ==

```
diff --git a/acme/dns_challenge.go b/acme/dns_challenge.go
index bad520b..8d5e7d5 100644
--- a/acme/dns_challenge.go
+++ b/acme/dns_challenge.go
@@ -97,6 +97,10 @@ func (s *dnsChallenge) Solve(chlng challenge, domain string) error {
 
        fqdn, value, _ := DNS01Record(domain, keyAuth)
 
+       delayCheck := time.Second * 4 * 60;
+       logf("Delaying DNS Record check for %v", delayCheck)
+       time.Sleep(delayCheck)
+
        logf("[INFO][%s @ %s] Checking DNS record propagation using %+v", fqdn, domain, RecursiveNameservers)
 
        var timeout, interval time.Duration
```

results in:

```
dow184@TOWER-SL:~/go/src/github.com/xenolf/lego$ ./lego --email="sven@home.org.au" --domains="qwerty.qwerty.ona.im" --dns=namedotcom run
2018/05/18 10:08:43 [INFO][qwerty.qwerty.ona.im] acme: Obtaining bundled SAN certificate
2018/05/18 10:08:44 [INFO][qwerty.qwerty.ona.im] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/QqljdFWb6f94uDySLHPmlcL2jbH0g0C7bTbjpAq0-0E
2018/05/18 10:08:44 [INFO][qwerty.qwerty.ona.im] acme: Could not find solver for: http-01
2018/05/18 10:08:44 [INFO][qwerty.qwerty.ona.im] acme: Trying to solve DNS-01

---
TEST: /v4/domains/qwerty.qwerty.ona.im/records
{"domainName":"qwerty.qwerty.ona.im","host":"_acme-challenge.qwerty.qwerty","type":"TXT","answer":"qPwB93_BbUFzV8VPgjzBWAQP-u0oF5RoPmdlpu1woPo","ttl":120}

---
2018/05/18 10:08:45 Delaying DNS Record check for 4m0s
2018/05/18 10:12:45 [INFO][_acme-challenge.qwerty.qwerty.ona.im. @ qwerty.qwerty.ona.im] Checking DNS record propagation using [127.0.0.53:53]
2018/05/18 10:12:48 [INFO][qwerty.qwerty.ona.im] The server validated our request
2018/05/18 10:12:49 [INFO][qwerty.qwerty.ona.im] acme: Validations succeeded; requesting certificates
2018/05/18 10:12:50 [INFO] acme: Requesting issuer cert from https://acme-v01.api.letsencrypt.org/acme/issuer-cert
2018/05/18 10:12:50 [INFO][qwerty.qwerty.ona.im] Server responded with a certificate.

```

**Comment by mholt** [comment]
I think I better let @xenolf or a second collaborator look at this to make an assessment; I don't have the bandwidth to do so right now.

**Comment by coopernurse** [comment]
@mholt @SvenDowideit Are you looking for folks to test this?  I use name.com and hit this bug so I'm interested in getting a fix merged.  I opened a separate PR before I saw this fix.

If you need testers I can pull this branch and test with my domain.

**Comment by coopernurse** [comment]
Yes, I can confirm this patch solves my `name.com` problems.  This patch will fix the merge conflict (and is what I tested with):

```
diff --git a/providers/dns/namedotcom/namedotcom.go b/providers/dns/namedotcom/namedotcom.go
index 25d7900..5d79a45 100644
--- a/providers/dns/namedotcom/namedotcom.go
+++ b/providers/dns/namedotcom/namedotcom.go
@@ -94,7 +94,7 @@ func NewDNSProviderConfig(config *Config) (*DNSProvider, error) {
 func (d *DNSProvider) Present(domain, token, keyAuth string) error {
        fqdn, value := dns01.GetRecord(domain, keyAuth)
 
-       domainDetails, err := c.client.GetDomain(&namecom.GetDomainRequest{DomainName: domain})
+       domainDetails, err := d.client.GetDomain(&namecom.GetDomainRequest{DomainName: domain})
        if err != nil {
                return fmt.Errorf("namedotcom API call failed: %v", err)
        }
@@ -107,7 +107,7 @@ func (d *DNSProvider) Present(domain, token, keyAuth string) error {
                Answer:     value,
        }
 
-       _, err := d.client.CreateRecord(request)
+       _, err = d.client.CreateRecord(request)
        if err != nil {
                return fmt.Errorf("namedotcom: API call failed: %v", err)
        }
```

I can open a new PR with the above applied if desired, or @SvenDowideit can update his branch on this PR.

Let me know if there's anything else I can do to help get this merged.

**Comment by SvenDowideit** [comment]
@mholt @coopernurse ouch. I just found this :/ I've updated it as suggested - though I did also move my stuff off name.com - so testing is harder for me.

**Comment by ldez** [comment]
@coopernurse can you test this PR?

**Comment by jflattery** [comment]
If someone could guide me to how to test this in a traefik docker container I would love to try. I use name.com and I'm having this issue.

**Comment by ldez** [comment]
@jflattery as you are asking the question I think that you don' know Go, I will not explain how to test with Traefik because it can be complex for you.

But I will explain you how to build and test with lego.

- install Golang

```bash
mkdir -p $GOPATH/src/github.com/go-acme
cd $GOPATH/src/github.com/go-acme

# clone the fork related to this PR
git clone git@github.com:SvenDowideit/lego.git
cd lego

git checkout namedotcom_subdomain

# build the binary
make build

# first test: wildcard
NAMECOM_USERNAME=xxxxxxxx \
NAMECOM_API_TOKEN=xxxxxxxx \
./dist/lego -m your@email.com --dns namedotcom -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run

# second test: sub domain
NAMECOM_USERNAME=xxxxxxxx \
NAMECOM_API_TOKEN=xxxxxxxx \
./dist/lego -m your@email.com --dns namedotcom -d sub.example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```

**Comment by jflattery** [comment]
```bash
jflattery@myhost:~/go/src/github.com/go-acme/lego $ make build
BIN_OUTPUT: dist/lego
rm -rf dist/ builds/ cover.out
Version: cd413944af00ec1c4890399a137148cd1be85ee2
go build -v -trimpath -ldflags '-X "main.version=cd413944af00ec1c4890399a137148cd1be85ee2"' -o  dist/lego ./cmd/lego/
flag provided but not defined: -trimpath
usage: go build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
make: *** [Makefile:25: build] Error 2
```

**Comment by ldez** [comment]
you have to use go1.14

**Comment by jflattery** [comment]
````bash
# first test: wildcard
2020/03/18 16:03:27 No key found for account me@myemail.com. Generating a P384 key.
2020/03/18 16:03:27 Saved key to /home/jflattery/go/src/github.com/go-acme/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/me@myemail.com/keys/me@myemail.com.key
2020/03/18 16:03:27 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
y
2020/03/18 16:03:30 [INFO] acme: Registering account for r4-node001@datc.it
!!!! HEADS UP !!!!

		Your account credentials have been saved in your Let's Encrypt
		configuration directory at "/home/jflatte/go/src/github.com/go-acme/lego/.lego/accounts".
		You should make a secure backup	of this folder now. This
		configuration directory will also contain certificates and
		private keys obtained from Let's Encrypt so making regular
		backups of this folder is ideal.2020/03/18 16:03:30 [INFO] [*.mydomain.com, mydomain.com] acme: Obtaining bundled SAN certificate
2020/03/18 16:03:31 [INFO] [*.mydomain.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/44407329
2020/03/18 16:03:31 [INFO] [mydomain.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/44407330
2020/03/18 16:03:31 [INFO] [*.mydomain.com] acme: use dns-01 solver
2020/03/18 16:03:31 [INFO] [mydomain.com] acme: Could not find solver for: tls-alpn-01
2020/03/18 16:03:31 [INFO] [mydomain.com] acme: Could not find solver for: http-01
2020/03/18 16:03:31 [INFO] [mydomain.com] acme: use dns-01 solver
2020/03/18 16:03:31 [INFO] [*.mydomain.com] acme: Preparing to solve DNS-01
2020/03/18 16:03:32 [INFO] [mydomain.com] acme: Preparing to solve DNS-01
2020/03/18 16:03:33 [INFO] [*.mydomain.com] acme: Trying to solve DNS-01
2020/03/18 16:03:33 [INFO] [*.mydomain.com] acme: Checking DNS record propagation using [mylocaldnsresolver:53]
2020/03/18 16:03:33 [INFO] Wait for propagation [timeout: 15m0s, interval: 20s]
2020/03/18 16:03:43 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:04:13 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:04:43 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:05:13 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:05:43 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:06:13 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:06:43 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:07:13 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:07:43 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:08:13 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:08:43 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:09:13 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:09:43 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:10:13 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:10:43 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:11:13 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:11:43 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:12:13 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:12:43 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:13:13 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:13:43 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:14:13 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:14:43 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:15:13 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:15:43 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:16:13 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:16:43 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:17:13 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:17:43 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:18:13 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:18:33 [INFO] [mydomain.com] acme: Trying to solve DNS-01
2020/03/18 16:18:33 [INFO] [mydomain.com] acme: Checking DNS record propagation using [mylocaldnsresolver:53]
2020/03/18 16:18:33 [INFO] Wait for propagation [timeout: 15m0s, interval: 20s]
2020/03/18 16:18:43 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:19:13 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:19:43 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:20:13 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:20:43 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:21:13 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:21:43 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:22:13 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:22:43 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:23:13 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:23:43 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:24:13 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:24:43 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:25:13 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:25:43 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:26:13 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:26:43 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:27:13 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:27:43 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:28:13 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:28:43 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:29:13 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:29:43 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:30:13 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:30:43 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:31:13 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:31:43 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:32:13 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:32:43 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:33:13 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:33:33 [INFO] [*.mydomain.com] acme: Cleaning DNS-01 challenge
2020/03/18 16:33:35 [INFO] [mydomain.com] acme: Cleaning DNS-01 challenge
2020/03/18 16:33:35 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/44407329
2020/03/18 16:33:36 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/44407330
2020/03/18 16:33:36 Could not obtain certificates:
	acme: Error -> One or more domains had a problem:
[*.mydomain.com] time limit exceeded: last error: read udp 192.168.7.206:39890->mylocaldnsresolver:53: i/o timeout
[mydomain.com] time limit exceeded: last error: read udp 192.168.7.206:55681->mylocaldnsresolver:53: i/o timeout
jflattery@myhost:~/go/src/github.com/go-acme/lego $

# second test: sub domain
2020/03/18 16:51:31 [INFO] [sub.mydomain.com] acme: Obtaining bundled SAN certificate
2020/03/18 16:51:32 [INFO] [sub.mydomain.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/44412931
2020/03/18 16:51:32 [INFO] [sub.mydomain.com] acme: Could not find solver for: tls-alpn-01
2020/03/18 16:51:32 [INFO] [sub.mydomain.com] acme: Could not find solver for: http-01
2020/03/18 16:51:32 [INFO] [sub.mydomain.com] acme: use dns-01 solver
2020/03/18 16:51:32 [INFO] [sub.mydomain.com] acme: Preparing to solve DNS-01
2020/03/18 16:51:33 [INFO] [sub.mydomain.com] acme: Trying to solve DNS-01
2020/03/18 16:51:33 [INFO] [sub.mydomain.com] acme: Checking DNS record propagation using [mylocaldnsresolver:53]
2020/03/18 16:51:33 [INFO] Wait for propagation [timeout: 15m0s, interval: 20s]
2020/03/18 16:51:43 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:52:13 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:52:43 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:53:13 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:53:43 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:54:13 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:54:43 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:55:13 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:55:43 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:56:13 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:56:43 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:57:13 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:57:43 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:58:13 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:58:43 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:59:13 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 16:59:43 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:00:13 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:00:43 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:01:13 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:01:43 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:02:13 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:02:43 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:03:13 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:03:43 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:04:13 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:04:43 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:05:13 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:05:43 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:06:13 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:06:33 [INFO] [sub.mydomain.com] acme: Cleaning DNS-01 challenge
2020/03/18 17:06:34 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/44412931
2020/03/18 17:06:34 Could not obtain certificates:
	acme: Error -> One or more domains had a problem:
[sub.mydomain.com] time limit exceeded: last error: read udp 192.168.7.206:45453->mylocaldnsresolver:53: i/o timeout
jflattery@myhost:~/go/src/github.com/go-acme/lego $
````

**Comment by ldez** [comment]
It seems to be a problem with your `mylocaldnsresolver` because this PR don't change this behavior.

**Comment by jflattery** [comment]
During the first test it created two txt entries with name.com for " _acme-challenge.mydomain.com" with different answers/keys. And for the second test it created a txt entry of " _acme-challenge.sub.mydomain.com" with its own answer/key.

**Comment by jflattery** [comment]
> It seems to be a problem with your `mylocaldnsresolver` because this PR don't change this behavior.
> 
> Could you test it without this `mylocaldnsresolver`?

What role could my resolver be playing? It isn't providing the IP address to LE is it?

**Comment by ldez** [comment]
> During the first test it created two txt entries with name.com for " _acme-challenge.mydomain.com" with different answers/keys. And for the second test it created a txt entry of " _acme-challenge.sub.mydomain.com" with its own answer/key.

It's expected.

> What role could my resolver be playing? It isn't providing the IP address to LE is it

It's not an information used by LE, it's used by lego to check the availability of the records before asking to LE to solve the challenge.

**Comment by jflattery** [comment]
> It's not an information used by LE, it's used by lego to check the availability of the records before asking to LE to solve the challenge.

Got it! So perhaps it is caching for too long?

**Comment by ldez** [comment]
> So perhaps it is caching for too long?

Lego don't use cache.

**Comment by jflattery** [comment]
Hmm so I just did a "dig -t txt _acme-challenge.sub.mydomain.com" and my resolver is responding with the expected key/answer.

**Comment by jflattery** [comment]
And now it just worked! 

```bash
2020/03/18 17:36:49 [INFO] [sub.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:37:17 [INFO] [sub.mydomain.com] The server validated our request
2020/03/18 17:37:17 [INFO] [sub.mydomain.com] acme: Cleaning DNS-01 challenge
2020/03/18 17:37:18 [INFO] [sub.mydomain.com] acme: Validations succeeded; requesting certificates
2020/03/18 17:37:18 [INFO] [sub.mydomain.com] Server responded with a certificate.
```
So I clearly need to resolve my issue with my local resolver, however your change works for the second test. I'll try the first test again.

**Comment by jflattery** [comment]
Does this look right for the first test?

```bash
jflattery@host2:~ $ dig -t txt _acme-challenge.mydomain.com

; <<>> DiG 9.9.5-9+deb8u18-Raspbian <<>> -t txt _acme-challenge.mydomain.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 46485
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_acme-challenge.mydomain.com.	IN	TXT

;; AUTHORITY SECTION:
mydomain.com.		134	IN	SOA	ns1cmt.name.com. support.name.com. 1584567438 10800 3600 604800 3600

;; Query time: 7 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Mar 18 17:45:35 EDT 2020
;; MSG SIZE  rcvd: 115

```

**Comment by ldez** [comment]
could you retry, but do the following command before:

```
rm -rf .lego
```

and provide me the full log.

dig don't provide information related to this PR.

**Comment by jflattery** [comment]
Ok the first test just finally passed before I saw your message. Would you still like me to "rm -rf .lego" and run again?

```bash
2020/03/18 17:40:46 [INFO] [*.mydomain.com, mydomain.com] acme: Obtaining bundled SAN certificate
2020/03/18 17:40:46 [INFO] [*.mydomain.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/44415635
2020/03/18 17:40:46 [INFO] [mydomain.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/44415636
2020/03/18 17:40:46 [INFO] [*.mydomain.com] acme: use dns-01 solver
2020/03/18 17:40:46 [INFO] [mydomain.com] acme: Could not find solver for: tls-alpn-01
2020/03/18 17:40:46 [INFO] [mydomain.com] acme: Could not find solver for: http-01
2020/03/18 17:40:46 [INFO] [mydomain.com] acme: use dns-01 solver
2020/03/18 17:40:46 [INFO] [*.mydomain.com] acme: Preparing to solve DNS-01
2020/03/18 17:40:48 [INFO] [mydomain.com] acme: Preparing to solve DNS-01
2020/03/18 17:40:48 [INFO] [*.mydomain.com] acme: Trying to solve DNS-01
2020/03/18 17:40:48 [INFO] [*.mydomain.com] acme: Checking DNS record propagation using [mylocaldnsresolver:53]
2020/03/18 17:40:48 [INFO] Wait for propagation [timeout: 15m0s, interval: 20s]
2020/03/18 17:40:48 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:41:08 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:41:29 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:41:49 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:42:09 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:42:29 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:42:49 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:43:09 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:43:29 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:43:49 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:44:09 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:44:29 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:44:49 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:45:09 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:45:29 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:45:49 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:46:09 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:46:29 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:46:49 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:47:09 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:47:29 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:47:49 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:48:09 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:48:29 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:48:50 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:49:10 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:49:30 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:49:50 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:50:10 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:50:30 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:50:57 [INFO] [*.mydomain.com] The server validated our request
2020/03/18 17:50:57 [INFO] [mydomain.com] acme: Trying to solve DNS-01
2020/03/18 17:50:57 [INFO] [mydomain.com] acme: Checking DNS record propagation using [mylocaldnsresolver:53]
2020/03/18 17:50:57 [INFO] Wait for propagation [timeout: 15m0s, interval: 20s]
2020/03/18 17:50:57 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:51:17 [INFO] [mydomain.com] acme: Waiting for DNS record propagation.
2020/03/18 17:51:37 [INFO] [mydomain.com] The server validated our request
2020/03/18 17:51:37 [INFO] [*.mydomain.com] acme: Cleaning DNS-01 challenge
2020/03/18 17:51:39 [INFO] [mydomain.com] acme: Cleaning DNS-01 challenge
2020/03/18 17:51:39 [INFO] [*.mydomain.com, mydomain.com] acme: Validations succeeded; requesting certificates
2020/03/18 17:51:40 [INFO] [*.mydomain.com] Server responded with a certificate.
```

**Comment by ldez** [comment]
> Would you still like me to "rm -rf .lego" and run again?

No I will consider that your test is sufficient to validate the functioning of this PR.

Thank you for the tests :+1:

**Comment by jflattery** [comment]
So would this be difficult for me to pull this change into a container? I would really like to get some services spun up :)

**Comment by ldez** [comment]
I will create an image for you (based on v2.1)

**Comment by ldez** [comment]
You can use `ldez/traefik:namedotcom`

**Comment by jflattery** [comment]
I'm sorry to be a pain but any chance you could build it for 😬 linux arm when you get a chance? Not sure which v... I'm using a Raspberry Pi 4 running Raspbian Buster Lite (Kernel version: 4.19) on a RPi4

**Comment by ldez** [comment]
Sorry but it will be difficult.

But you can try to use my branch to create a binary https://github.com/ldez/traefik/tree/namedotcom

**Comment by delandtj** [comment]
hey @ldez ,
how can I put this specific patch into my own traefik 2.2 build ?

**Comment by ldez** [comment]
@delandtj not the right to asking for that.

**Pull request merged**
