### PR TITLE
Add DNS provider for Loopia

### LINKED ISSUE #712: Add support for loopia
Any chance you could add support for the domain provider Loopia?
They have a api here https://www.loopia.se/api/ and i think you could use the `addZoneRecord`/`updateZoneRecord` to add dns records.

### PR DESCRIPTION
**Pull request by hazzeh**
Use the XML-RPC API to communicate with loopia.
The XML-RPC client implementation done at a minimal to only work with the functions in the loopia api required to fulfill the Present and Cleanup steps.

Inspiration was taken from the Gandi DNS provider.

Closes #712

### CODE REVIEW

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests (units)
```shell
make test
```
- [ ] add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help, documentation, and readme.
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`

**Comment by hazzeh** [comment]
Output of the lego run (real domain replaced with example.com) 
`2020/12/26 13:32:04 No key found for account hans.hazelius@gmail.com. Generating a P256 key.
2020/12/26 13:32:04 Saved key to /Users/hazze/go/src/github.com/go-acme/lego/dist/.lego/accounts/acme-staging-v02.api.letsencrypt.org/hans.hazelius@gmail.com/keys/hans.hazelius@gmail.com.key
2020/12/26 13:32:05 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
y
2020/12/26 13:32:07 [INFO] acme: Registering account for hans.hazelius@gmail.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/Users/hazze/go/src/github.com/go-acme/lego/dist/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2020/12/26 13:32:07 [INFO] [*.example.com, example.com] acme: Obtaining bundled SAN certificate
2020/12/26 13:32:08 [INFO] [*.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/178973576
2020/12/26 13:32:08 [INFO] [example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/178973577
2020/12/26 13:32:08 [INFO] [*.example.com] acme: use dns-01 solver
2020/12/26 13:32:08 [INFO] [example.com] acme: Could not find solver for: tls-alpn-01
2020/12/26 13:32:08 [INFO] [example.com] acme: Could not find solver for: http-01
2020/12/26 13:32:08 [INFO] [example.com] acme: use dns-01 solver
2020/12/26 13:32:08 [INFO] [*.example.com] acme: Preparing to solve DNS-01
2020/12/26 13:32:08 [INFO] [example.com] acme: Preparing to solve DNS-01
2020/12/26 13:32:09 [INFO] [*.example.com] acme: Trying to solve DNS-01
2020/12/26 13:32:09 [INFO] [*.example.com] acme: Checking DNS record propagation using [8.8.8.8:53]
2020/12/26 13:33:09 [INFO] Wait for propagation [timeout: 40m0s, interval: 1m0s]
2020/12/26 13:33:14 [INFO] [*.example.com] The server validated our request
2020/12/26 13:33:14 [INFO] [example.com] acme: Trying to solve DNS-01
2020/12/26 13:33:14 [INFO] [example.com] acme: Checking DNS record propagation using [8.8.8.8:53]
2020/12/26 13:34:14 [INFO] Wait for propagation [timeout: 40m0s, interval: 1m0s]
2020/12/26 13:34:20 [INFO] [example.com] The server validated our request
2020/12/26 13:34:20 [INFO] [*.example.com] acme: Cleaning DNS-01 challenge
2020/12/26 13:34:55 [INFO] [example.com] acme: Cleaning DNS-01 challenge
2020/12/26 13:34:55 [INFO] [*.example.com, example.com] acme: Validations succeeded; requesting certificates
2020/12/26 13:34:56 [INFO] [*.example.com] Server responded with a certificate.`

**Comment by hazzeh** [comment]
I can be the maintainer of this provider.
I've done my best to keep a homogeneous design with other providers, but I'm yet a bit novice in golang.

**Review by ldez — APPROVED** [review]
Thanks :+1:

**Comment by hazzeh** [comment]
> Thanks 👍

Thank you for your fixes and improvements to my PR :-)

**Pull request merged**
