### PR TITLE
Add DNS provider for Checkdomain

### PR DESCRIPTION
**Pull request by shilch**
This PR adds [Checkdomain](https://checkdomain.net) as DNS provider. I have tested it succesfully using main and sub domains. 

 Unfortunately, their API doesn't seem to provide a simple way of deleting records, thus I have a rather complex function deleteRecord() in client.go to deal with that.
~~I don't think splitting it into more functions is worth it; to satisfy the linter, I had to bypass it using the `//nolint` comment.~~

I did the same for some property name because they have a spelling error in their API which the linter rightfully complains about.

### CODE REVIEW

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests (units)
```shell
make test
```
- [ ] add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add the provider to the [readme.md](https://github.com/go-acme/lego#dns-providers)
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help and documentation
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`

**Comment by shilch** [comment]
Hello @ldez, thanks for your review!  
I executed this step successfully:  
```
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```  
I had to increase the default propagation timeout a bit because occasionally it takes more time.  
  
I am also able to maintain this provider.

**Comment by ldez** [comment]
Hello, could you provide the output of the command?

**Comment by shilch** [comment]
```
2019/12/01 09:49:11 No key found for account COVERT@COVERT.com. Generating a P384 key.
2019/12/01 09:49:11 Saved key to /Users/COVERT/go/src/github.com/go-acme/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/COVERT@COVERT.com/keys/COVERT@COVERT.com.key
2019/12/01 09:49:12 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
y
2019/12/01 09:49:14 [INFO] acme: Registering account for COVERT@COVERT.com
!!!! HEADS UP !!!!

		Your account credentials have been saved in your Let's Encrypt
		configuration directory at "/Users/COVERT/go/src/github.com/go-acme/lego/.lego/accounts".
		You should make a secure backup	of this folder now. This
		configuration directory will also contain certificates and
		private keys obtained from Let's Encrypt so making regular
		backups of this folder is ideal.2019/12/01 09:49:16 [INFO] [COVERT.com, *.COVERT.com] acme: Obtaining bundled SAN certificate
2019/12/01 09:49:18 [INFO] [*.COVERT.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/COVERT
2019/12/01 09:49:18 [INFO] [COVERT.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/COVERT
2019/12/01 09:49:18 [INFO] [*.COVERT.com] acme: use dns-01 solver
2019/12/01 09:49:18 [INFO] [COVERT.com] acme: Could not find solver for: tls-alpn-01
2019/12/01 09:49:18 [INFO] [COVERT.com] acme: Could not find solver for: http-01
2019/12/01 09:49:18 [INFO] [COVERT.com] acme: use dns-01 solver
2019/12/01 09:49:18 [INFO] [*.COVERT.com] acme: Preparing to solve DNS-01
2019/12/01 09:49:24 [INFO] [COVERT.com] acme: Preparing to solve DNS-01
2019/12/01 09:49:28 [INFO] [*.COVERT.com] acme: Trying to solve DNS-01
2019/12/01 09:49:28 [INFO] [*.COVERT.com] acme: Checking DNS record propagation using [192.168.43.246:53]
2019/12/01 09:49:28 [INFO] Wait for propagation [timeout: 5m0s, interval: 7s]
2019/12/01 09:49:29 [INFO] [*.COVERT.com] acme: Waiting for DNS record propagation.
2019/12/01 09:49:44 [INFO] [*.COVERT.com] The server validated our request
2019/12/01 09:49:44 [INFO] [COVERT.com] acme: Trying to solve DNS-01
2019/12/01 09:49:44 [INFO] [COVERT.com] acme: Checking DNS record propagation using [192.168.43.246:53]
2019/12/01 09:49:44 [INFO] Wait for propagation [timeout: 5m0s, interval: 7s]
2019/12/01 09:49:55 [INFO] [COVERT.com] The server validated our request
2019/12/01 09:49:55 [INFO] [*.COVERT.com] acme: Cleaning DNS-01 challenge
2019/12/01 09:50:03 [INFO] [COVERT.com] acme: Cleaning DNS-01 challenge
2019/12/01 09:50:11 [INFO] [COVERT.com, *.COVERT.com] acme: Validations succeeded; requesting certificates
2019/12/01 09:50:15 [INFO] [COVERT.com] Server responded with a certificate.
```

**Comment by shilch** [comment]
When can we expect the v3.3 release? Would like to see support in traefik.

**Comment by shilch** [comment]
Nice, thank you!

**Pull request merged**
