### PR TITLE
Add DNS provider for UKFast SafeDNS

### PR DESCRIPTION
**Pull request by Xiol**
Adds UKFast's SafeDNS dns01 provider for #1503.

### CODE REVIEW

**Comment by ldez** [comment]
#
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests (units)
```shell
make test
```
- [ ] add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help, documentation, and readme.
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`

**Comment by Xiol** [comment]
Example run as requested;

```
❯ export SAFEDNS_AUTH_TOKEN=asdfasdf

❯ dist/lego -m dane.elwell@gmail.com --dns safedns -d '*.testops.ukfast.co.uk' -d 'testops.ukfast.co.uk' -s https://acme-staging-v02.api.letsencrypt.org/directory run
2021/12/16 14:58:16 No key found for account dane.elwell@gmail.com. Generating a P256 key.
2021/12/16 14:58:16 Saved key to /home/dane/projects/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/dane.elwell@gmail.com/keys/dane.elwell@gmail.com.key
2021/12/16 14:58:17 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
y
2021/12/16 14:58:19 [INFO] acme: Registering account for dane.elwell@gmail.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/home/dane/projects/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2021/12/16 14:58:19 [INFO] [*.testops.ukfast.co.uk, testops.ukfast.co.uk] acme: Obtaining bundled SAN certificate
2021/12/16 14:58:20 [INFO] [*.testops.ukfast.co.uk] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/1195778128
2021/12/16 14:58:20 [INFO] [testops.ukfast.co.uk] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/1195778138
2021/12/16 14:58:20 [INFO] [*.testops.ukfast.co.uk] acme: use dns-01 solver
2021/12/16 14:58:20 [INFO] [testops.ukfast.co.uk] acme: Could not find solver for: tls-alpn-01
2021/12/16 14:58:20 [INFO] [testops.ukfast.co.uk] acme: Could not find solver for: http-01
2021/12/16 14:58:20 [INFO] [testops.ukfast.co.uk] acme: use dns-01 solver
2021/12/16 14:58:20 [INFO] [*.testops.ukfast.co.uk] acme: Preparing to solve DNS-01
2021/12/16 14:58:20 [INFO] safedns: creating record {Name:_acme-challenge.testops.ukfast.co.uk Type:TXT Content:"1wUvgm14E8sgWJInLRmy-tcaadflvvD90UPWGS40pNo" TTL:30} at https://api.ukfast.io/safedns/v1/zones/testops.ukfast.co.uk/records
2021/12/16 14:58:20 [INFO] safedns: created record with ID 5020534
2021/12/16 14:58:20 [INFO] [testops.ukfast.co.uk] acme: Preparing to solve DNS-01
2021/12/16 14:58:20 [INFO] safedns: creating record {Name:_acme-challenge.testops.ukfast.co.uk Type:TXT Content:"qXofvo-hbD_3mR-LyDr0xwQZFkRMAcAl6pgAiu2johU" TTL:30} at https://api.ukfast.io/safedns/v1/zones/testops.ukfast.co.uk/records
2021/12/16 14:58:20 [INFO] safedns: created record with ID 5020535
2021/12/16 14:58:20 [INFO] [*.testops.ukfast.co.uk] acme: Trying to solve DNS-01
2021/12/16 14:58:20 [INFO] [*.testops.ukfast.co.uk] acme: Checking DNS record propagation using [127.0.0.53:53]
2021/12/16 14:58:25 [INFO] Wait for propagation [timeout: 1m0s, interval: 5s]
2021/12/16 14:58:25 [INFO] [*.testops.ukfast.co.uk] acme: Waiting for DNS record propagation.
2021/12/16 14:58:34 [INFO] [*.testops.ukfast.co.uk] The server validated our request
2021/12/16 14:58:34 [INFO] [testops.ukfast.co.uk] acme: Trying to solve DNS-01
2021/12/16 14:58:34 [INFO] [testops.ukfast.co.uk] acme: Checking DNS record propagation using [127.0.0.53:53]
2021/12/16 14:58:39 [INFO] Wait for propagation [timeout: 1m0s, interval: 5s]
2021/12/16 14:58:39 [INFO] [testops.ukfast.co.uk] acme: Waiting for DNS record propagation.
2021/12/16 14:58:51 [INFO] [testops.ukfast.co.uk] The server validated our request
2021/12/16 14:58:51 [INFO] [*.testops.ukfast.co.uk] acme: Cleaning DNS-01 challenge
2021/12/16 14:58:51 [INFO] safedns: cleaning up record 5020534 at https://api.ukfast.io/safedns/v1/zones/testops.ukfast.co.uk/records/5020534
2021/12/16 14:58:51 [INFO] [testops.ukfast.co.uk] acme: Cleaning DNS-01 challenge
2021/12/16 14:58:51 [INFO] safedns: cleaning up record 5020535 at https://api.ukfast.io/safedns/v1/zones/testops.ukfast.co.uk/records/5020535
2021/12/16 14:58:51 [INFO] [*.testops.ukfast.co.uk, testops.ukfast.co.uk] acme: Validations succeeded; requesting certificates
2021/12/16 14:58:52 [INFO] [*.testops.ukfast.co.uk] Server responded with a certificate.
```

**Comment by Xiol** [comment]
Right, sorry, that should pass checks now.

**Comment by ldez** [comment]
to answer this point:
>  be able to maintain this provider

I need to know who you are: are you a UKFast employee? Are you a UKFast customer? etc.

**Comment by Xiol** [comment]
@ldez, I'm a UKFast employee. Happy to maintain this.

**Review by ldez — APPROVED** [review]
Thanks :+1:

**Pull request merged**
