### PR TITLE
websupport: include tzdata on windows

### LINKED ISSUE #2273: websupport dns provider fails on windows
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

Use the websupport dns provider on a windows machine where golang is not installed

### What did you see instead?

The tool fails with **unknown time zone GMT** error

### How do you use lego?

Binary

### Reproduction steps

Run lego.exe on windows with `--dns websupport`  

Probably only reproducible on a machine without golang installed

### Version of lego

```console
git master:  d52f7b0b5829e3df87bbc71fbfba9897644ef7fa
```

### Logs

<details>

```console
C:\Users\user\Documents>C:\Users\user\Documents\lego.exe --email "user@example.com" --dns websupport --accept-tos=true --domains example.com run
2024/09/16 09:26:14 [INFO] [example.com] acme: Obtaining bundled SAN certificate
2024/09/16 09:26:15 [INFO] [example.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/404285062436
2024/09/16 09:26:15 [INFO] [example.com] acme: Could not find solver for: tls-alpn-01
2024/09/16 09:26:15 [INFO] [example.com] acme: Could not find solver for: http-01
2024/09/16 09:26:15 [INFO] [example.com] acme: use dns-01 solver
2024/09/16 09:26:15 [INFO] [example.com] acme: Preparing to solve DNS-01
2024/09/16 09:26:15 [INFO] [example.com] acme: Cleaning DNS-01 challenge
2024/09/16 09:26:15 [WARN] [example.com] acme: cleaning up failed: websupport: unknown record ID for '_acme-challenge.example.com.' '68U0Zd4oywRXWrQQdpmiP_Y2JhKG8DXPxxw1cC2TxOc'
2024/09/16 09:26:15 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/404285062436
2024/09/16 09:26:15 Could not obtain certificates:
        error: one or more domains had a problem:
[example.com] [example.com] acme: error presenting token: websupport: add record: time location: unknown time zone GMT
```

</details>

- [ ] 

### Go environment (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by r0b0**
fixes #2273

### CODE REVIEW

**Comment by r0b0** [comment]
see https://github.com/golang/go/issues/55899 for explanation - if golang itself is not installed on the windows machine, `time.LoadLocation()` will fail unless `time/tzdata` is imported

**Comment by ldez** [comment]
In fact, we don't need "GMT" timezone, we can use UTC.


```diff
--- i/providers/dns/websupport/internal/client.go
+++ w/providers/dns/websupport/internal/client.go
@@ -150,12 +150,7 @@ func (c *Client) DeleteRecord(ctx context.Context, domainName string, recordID i
 func (c *Client) do(req *http.Request, result any) error {
        req.Header.Set("Accept-Language", "en_us")
 
-       location, err := time.LoadLocation("GMT")
-       if err != nil {
-               return fmt.Errorf("time location: %w", err)
-       }
-
-       err = c.sign(req, time.Now().In(location))
+       err := c.sign(req, time.Now().UTC())
        if err != nil {
                return fmt.Errorf("signature: %w", err)
        }
```

The problem is related to the usage of `time.LoadLocation` which related on the zip but `.UTC` doesn't need this file.
And globally GMT is equal to UTC, it's just the old name.

**Comment by ldez** [comment]
FYI, this is not exactly true:

>  if golang itself is not installed on the windows machine

The problem is related to the missing time zone data on your computer, not related to Go.

The system time zone data are used if the zip is missing.

<details><summary>demo</summary>

```go
package main

import (
	"fmt"
	"log"
	"time"
)

func main() {
	now := time.Now()

	fmt.Println(now.UTC())

	location, err := time.LoadLocation("GMT")
	if err != nil {
		log.Fatalf("time location: %s", err)
	}

	fmt.Println(now.In(location))
}
```

```console
$ docker run --rm -v $(pwd):/app -w /app -it alpine:3.20 sh
/app # ./foo
2024-09-16 12:44:35.630864645 +0000 UTC
2024/09/16 12:44:35 time location: unknown time zone GMT
/app # 
/app # apk add tzdata
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
(1/1) Installing tzdata (2024b-r0)
OK: 9 MiB in 15 packages
/app # ./foo
2024-09-16 12:45:02.058793991 +0000 UTC
2024-09-16 12:45:02.058793991 +0000 GMT
/app # 
```

</details>

**Comment by r0b0** [comment]
OK, there are multiple instances of `time.LoadLocation()` throughout the code - if you have a fix, you probably want to apply it everywhere:
```
$ grep -ri time.LoadLocation .
./providers/dns/brandit/internal/client.go:     location, err := time.LoadLocation("GMT")
./providers/dns/nifcloud/internal/client.go:            location, err := time.LoadLocation("GMT")
./providers/dns/websupport/internal/client.go:  location, err := time.LoadLocation("GMT")
./providers/dns/wedos/internal/token.go:                loc, err := time.LoadLocation(zoneName)
```

**Comment by ldez** [comment]
Technically, there is nothing to fix because it relies on system elements by default.

Your problem is related the time zones available on your system.

The `time/tzdata` package is just a kind of workaround.

https://github.com/golang/go/blob/3d33437c450aa74014ea1d41cd986b6ee6266984/src/time/tzdata/tzdata.go#L5-L8

The `time/tzdata` package comes with some constraints:
- the size (~450KB)
- this file can be out of date and cannot be updated unless recompiling.

https://github.com/golang/go/blob/3d33437c450aa74014ea1d41cd986b6ee6266984/src/time/tzdata/tzdata.go#L10-L11

So, I will change "GMT" to UTC in some cases but it's not possible everywhere, and it's not required as the problem is the availability of the time zone information on your system.

To avoid any ambiguity, the time zones are available by default on Windows without the `time/tzdata` pacakge.

https://github.com/golang/go/blob/master/src/time/zoneinfo_windows.go

**Pull request closed without merging**
