### PR TITLE
Add DNS provider for Timeweb Cloud

### LINKED ISSUE #1789: Support for provider: Timeweb Cloud
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Docker image

### Link to the DNS provider

https://timeweb.cloud/

### Link to the API documentation

https://timeweb.cloud/docs/public-api/api-managing-domains

### Additional Notes

_No response_

### PR DESCRIPTION
**Pull request by paveloom**
Site: https://timeweb.cloud
API: https://timeweb.cloud/api-docs

Closes #1789

### CODE REVIEW

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests (units)
```shell
make test
```
- [ ] add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help, documentation, and readme.
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`

**Comment by paveloom** [comment]
I am able to maintain it.

Did some testing on real domains already, so LetsEncrypt just returns cached certificates now. Here's my latest run that I found in one of my terminals. Here, the wildcard certificate is being retrieved for the first time.

```
./dist/lego --server=https://acme-staging-v02.api.letsencrypt.org/directory --email contact@paveloom.dev --dns timewebcloud -d "*.paveloom.dev" -d paveloom.dev run
2024/10/13 21:20:16 [INFO] [*.paveloom.dev, paveloom.dev] acme: Obtaining bundled SAN certificate
2024/10/13 21:20:17 [INFO] [*.paveloom.dev] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/14408856473
2024/10/13 21:20:17 [INFO] [paveloom.dev] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/14410959093
2024/10/13 21:20:17 [INFO] [paveloom.dev] acme: authorization already valid; skipping challenge
2024/10/13 21:20:17 [INFO] [*.paveloom.dev] acme: use dns-01 solver
2024/10/13 21:20:17 [INFO] [*.paveloom.dev] acme: Preparing to solve DNS-01
2024/10/13 21:20:18 [INFO] [*.paveloom.dev] acme: Trying to solve DNS-01
2024/10/13 21:20:18 [INFO] [*.paveloom.dev] acme: Checking DNS record propagation. [nameservers=127.0.0.53:53]
2024/10/13 21:20:23 [INFO] Wait for propagation [timeout: 1m0s, interval: 5s]
2024/10/13 21:20:31 [INFO] [*.paveloom.dev] The server validated our request
2024/10/13 21:20:31 [INFO] [*.paveloom.dev] acme: Cleaning DNS-01 challenge
2024/10/13 21:20:31 [INFO] [*.paveloom.dev, paveloom.dev] acme: Validations succeeded; requesting certificates
2024/10/13 21:20:31 [INFO] Wait for certificate [timeout: 30s, interval: 500ms]
2024/10/13 21:20:33 [INFO] [*.paveloom.dev] Server responded with a certificate.
```

**Comment by ldez** [comment]
can you run `rm -rf .lego` (as suggested in my previous comment) before running lego?

**Comment by paveloom** [comment]
Oh, right! I didn't notice that I deleted the one in my home directory.

```
~> lego (timeweb) rm -rf .lego
~> lego (timeweb) ./dist/lego -m contact@paveloom.dev --dns timewebcloud -d "*.paveloom.dev" -d paveloom.dev -s https://acme-staging-v02.api.letsencrypt.org/directory run
2024/10/13 21:41:29 No key found for account contact@paveloom.dev. Generating a P256 key.
2024/10/13 21:41:29 Saved key to /home/paveloom/Playground/lego-env/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/contact@paveloom.dev/keys/contact@paveloom.dev.key
2024/10/13 21:41:30 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf
Do you accept the TOS? Y/n
Y
2024/10/13 21:41:34 [INFO] acme: Registering account for contact@paveloom.dev
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/home/paveloom/Playground/lego-env/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2024/10/13 21:41:35 [INFO] [*.paveloom.dev, paveloom.dev] acme: Obtaining bundled SAN certificate
2024/10/13 21:41:35 [INFO] [*.paveloom.dev] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/14411159803
2024/10/13 21:41:35 [INFO] [paveloom.dev] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/14411159813
2024/10/13 21:41:35 [INFO] [*.paveloom.dev] acme: use dns-01 solver
2024/10/13 21:41:35 [INFO] [paveloom.dev] acme: Could not find solver for: tls-alpn-01
2024/10/13 21:41:35 [INFO] [paveloom.dev] acme: Could not find solver for: http-01
2024/10/13 21:41:35 [INFO] [paveloom.dev] acme: use dns-01 solver
2024/10/13 21:41:35 [INFO] [*.paveloom.dev] acme: Preparing to solve DNS-01
2024/10/13 21:41:36 [INFO] [paveloom.dev] acme: Preparing to solve DNS-01
2024/10/13 21:41:36 [INFO] [*.paveloom.dev] acme: Trying to solve DNS-01
2024/10/13 21:41:36 [INFO] [*.paveloom.dev] acme: Checking DNS record propagation. [nameservers=127.0.0.53:53]
2024/10/13 21:41:41 [INFO] Wait for propagation [timeout: 1m0s, interval: 5s]
2024/10/13 21:41:42 [INFO] [*.paveloom.dev] acme: Waiting for DNS record propagation.
2024/10/13 21:41:53 [INFO] [*.paveloom.dev] The server validated our request
2024/10/13 21:41:53 [INFO] [paveloom.dev] acme: Trying to solve DNS-01
2024/10/13 21:41:53 [INFO] [paveloom.dev] acme: Checking DNS record propagation. [nameservers=127.0.0.53:53]
2024/10/13 21:41:58 [INFO] Wait for propagation [timeout: 1m0s, interval: 5s]
2024/10/13 21:42:02 [INFO] [paveloom.dev] The server validated our request
2024/10/13 21:42:02 [INFO] [*.paveloom.dev] acme: Cleaning DNS-01 challenge
2024/10/13 21:42:02 [INFO] [paveloom.dev] acme: Cleaning DNS-01 challenge
2024/10/13 21:42:02 [INFO] [*.paveloom.dev, paveloom.dev] acme: Validations succeeded; requesting certificates
2024/10/13 21:42:02 [INFO] Wait for certificate [timeout: 30s, interval: 500ms]
2024/10/13 21:42:06 [INFO] [*.paveloom.dev] Server responded with a certificate.
~> lego (timeweb) tree .lego/
.lego/
├── accounts
│   └── acme-staging-v02.api.letsencrypt.org
│       └── contact@paveloom.dev
│           ├── account.json
│           └── keys
│               └── contact@paveloom.dev.key
└── certificates
    ├── _.paveloom.dev.crt
    ├── _.paveloom.dev.issuer.crt
    ├── _.paveloom.dev.json
    └── _.paveloom.dev.key

6 directories, 6 files
```

**Comment by ldez** [comment]
Notes for the future me:

There is an official API client but this client is completely broken:
- the code is generated and the module name is `github.com/GIT_USER_ID/GIT_REPO_ID`
- the code contains redeclared constants
- Even with a fix to the module name and the redeclared constants, the module doesn't compile.

https://github.com/timeweb-cloud/sdk-go/pull/1

So, for now, this API client is unusable.

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
