### PR TITLE
Add DNS provider for Epik

### LINKED ISSUE #1489: Support for provider: epik.com
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Binary

### Link to the DNS provider

https://www.epik.com

### Link to the API documentation

https://www.epik.com/support/knowledgebase/epik-domain-management-api/

https://docs.userapi.epik.com/v2/

### Additional Notes

thank you!

### PR DESCRIPTION
**Pull request by ldez**
- [x] have a homogeneous design with the other providers
- [x] pass the linter
- [x] do `go mod tidy`
- [x] add tests (units)
- [x] add tests ("live")
- [x] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [x] generate CLI help, documentation, and readme.
- [x] be able to do: _(and put the output of this command to a comment)_
```bash
rm -rf .lego/

EPIK_SIGNATURE=xxx ./lego -m your_email@example.com --dns epik -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.

@marius-locomotion could you test by running the previous command (you have to use a real domain and email)?

Closes #1489

### CODE REVIEW

**Comment by marius-locomotion** [comment]
Hello,
I will test shortly and send an update.
Thank you!

**Comment by marius-locomotion** [comment]
Hi Ludovic,

Could you please help me with the steps to test this new provider?

I cloned your git repo `https://github.com/ldez/lego/tree/feat/epik` and checked-out the branch `feat/epik` then I tried to build it, but it fails. I have go version 1.16.4 installed and golangci-lint 1.42.1
`go version
go version go1.16.4 linux/amd64`

`golangci-lint version
golangci-lint has version 1.42.1 built from 54f4301d on 2021-09-06T17:05:10Z`

I ran `make` command, but I get the error message below:

`make
BIN_OUTPUT: dist/lego
rm -rf dist/ builds/ cover.out
go generate ./...
Documentation for 98 DNS providers has been generated.
golangci-lint run
acme/api/order_test.go:75:14: undeclared name: `jose` (typecheck)
        jws, err := jose.ParseSigned(string(reqBody))
                    ^
acme/api/order_test.go:80:27: undeclared name: `jose` (typecheck)
        body, err := jws.Verify(&jose.JSONWebKey{
                                 ^
acme/api/order_test.go:15:2: "gopkg.in/square/go-jose.v2" imported but not used (typecheck)
        "gopkg.in/square/go-jose.v2"
        ^
challenge/resolver/solver_manager_test.go:162:14: undeclared name: `jose` (typecheck)
        jws, err := jose.ParseSigned(string(reqBody))
                    ^
challenge/resolver/solver_manager_test.go:167:27: undeclared name: `jose` (typecheck)
        body, err := jws.Verify(&jose.JSONWebKey{
                                 ^
challenge/resolver/solver_manager_test.go:17:2: "gopkg.in/square/go-jose.v2" imported but not used (typecheck)
        "gopkg.in/square/go-jose.v2"
        ^
challenge/tlsalpn01/tls_alpn_challenge.go:4:2: "crypto/rsa" imported but not used (typecheck)
        "crypto/rsa"
        ^
providers/dns/cloudflare/client.go:12:14: undeclared name: `cloudflare` (typecheck)
        clientEdit *cloudflare.API // needs Zone/DNS/Edit permissions
                    ^
providers/dns/cloudflare/client.go:13:14: undeclared name: `cloudflare` (typecheck)
        clientRead *cloudflare.API // needs Zone/Zone/Read permissions
                    ^
providers/dns/cloudflare/client.go:62:77: undeclared name: `cloudflare` (typecheck)
func (m *metaClient) CreateDNSRecord(ctx context.Context, zoneID string, rr cloudflare.DNSRecord) (*cloudflare.DNSRecordResponse, error) {
                                                                            ^
providers/dns/cloudflare/client.go:66:72: undeclared name: `cloudflare` (typecheck)
func (m *metaClient) DNSRecords(ctx context.Context, zoneID string, rr cloudflare.DNSRecord) ([]cloudflare.DNSRecord, error) {
                                                                       ^
providers/dns/cloudflare/client.go:22:18: undeclared name: `cloudflare` (typecheck)
                client, err := cloudflare.New(config.AuthKey, config.AuthEmail, cloudflare.HTTPClient(config.HTTPClient))
                               ^
providers/dns/cloudflare/client.go:35:14: undeclared name: `cloudflare` (typecheck)
        dns, err := cloudflare.NewWithAPIToken(config.AuthToken, cloudflare.HTTPClient(config.HTTPClient))
                    ^
providers/dns/cloudflare/client.go:49:15: undeclared name: `cloudflare` (typecheck)
        zone, err := cloudflare.NewWithAPIToken(config.ZoneToken, cloudflare.HTTPClient(config.HTTPClient))
                     ^
providers/dns/cloudflare/client.go:7:2: "github.com/cloudflare/cloudflare-go" imported but not used (typecheck)
        "github.com/cloudflare/cloudflare-go"
        ^
providers/dns/gcloud/googlecloud.go:68:10: undeclared name: `dns` (typecheck)
        client *dns.Service
                ^
providers/dns/gcloud/googlecloud.go:236:57: undeclared name: `dns` (typecheck)
func (d *DNSProvider) applyChanges(zone string, change *dns.Change) error {
                                                        ^
providers/dns/gcloud/googlecloud.go:343:61: undeclared name: `dns` (typecheck)
func (d *DNSProvider) findTxtRecords(zone, fqdn string) ([]*dns.ResourceRecordSet, error) {
                                                            ^
providers/dns/gcloud/googlecloud.go:94:60: undeclared name: `dns` (typecheck)
        client, err := google.DefaultClient(context.Background(), dns.NdevClouddnsReadwriteScope)
                                                                  ^
providers/dns/gcloud/googlecloud.go:128:47: undeclared name: `dns` (typecheck)
        conf, err := google.JWTConfigFromJSON(saKey, dns.NdevClouddnsReadwriteScope)
                                                     ^
providers/dns/gcloud/googlecloud.go:165:14: undeclared name: `dns` (typecheck)
        svc, err := dns.NewService(context.Background(), option.WithHTTPClient(config.HTTPClient))
                    ^
providers/dns/gcloud/googlecloud.go:204:34: undeclared name: `dns` (typecheck)
                if err = d.applyChanges(zone, &dns.Change{Deletions: existingRrSet}); err != nil {
                                               ^
providers/dns/gcloud/googlecloud.go:209:10: undeclared name: `dns` (typecheck)
        rec := &dns.ResourceRecordSet{
                ^
providers/dns/gcloud/googlecloud.go:225:13: undeclared name: `dns` (typecheck)
        change := &dns.Change{
                   ^
providers/dns/gcloud/googlecloud.go:226:17: undeclared name: `dns` (typecheck)
                Additions: []*dns.ResourceRecordSet{rec},
                              ^
providers/dns/gcloud/googlecloud.go:298:60: undeclared name: `dns` (typecheck)
        _, err = d.client.Changes.Create(d.config.Project, zone, &dns.Change{Deletions: records}).Do()
                                                                  ^
providers/dns/gcloud/googlecloud_test.go:36:56: undeclared name: `dns` (typecheck)
                _, err := google.DefaultClient(context.Background(), dns.NdevClouddnsReadwriteScope)
                                                                     ^
providers/dns/gcloud/googlecloud_test.go:155:13: undeclared name: `dns` (typecheck)
                mzlrs := &dns.ManagedZonesListResponse{
                          ^
providers/dns/gcloud/googlecloud_test.go:156:21: undeclared name: `dns` (typecheck)
                        ManagedZones: []*dns.ManagedZone{
                                         ^
providers/dns/gcloud/googlecloud_test.go:175:13: undeclared name: `dns` (typecheck)
                rrslr := &dns.ResourceRecordSetsListResponse{
                          ^
providers/dns/gcloud/googlecloud_test.go:176:15: undeclared name: `dns` (typecheck)
                        Rrsets: []*dns.ResourceRecordSet{},
                                   ^
providers/dns/gcloud/googlecloud_test.go:193:14: undeclared name: `dns` (typecheck)
                var chgReq dns.Change
                           ^
providers/dns/gcloud/googlecloud_test.go:235:13: undeclared name: `dns` (typecheck)
                mzlrs := &dns.ManagedZonesListResponse{
                          ^
providers/dns/gcloud/googlecloud_test.go:236:21: undeclared name: `dns` (typecheck)
                        ManagedZones: []*dns.ManagedZone{
                                         ^
providers/dns/gcloud/googlecloud_test.go:255:13: undeclared name: `dns` (typecheck)
                rrslr := &dns.ResourceRecordSetsListResponse{
                          ^
providers/dns/gcloud/googlecloud_test.go:256:15: undeclared name: `dns` (typecheck)
                        Rrsets: []*dns.ResourceRecordSet{{
                                   ^
providers/dns/gcloud/googlecloud_test.go:278:14: undeclared name: `dns` (typecheck)
                var chgReq dns.Change
                           ^
providers/dns/gcloud/googlecloud_test.go:335:13: undeclared name: `dns` (typecheck)
                mzlrs := &dns.ManagedZonesListResponse{
                          ^
providers/dns/gcloud/googlecloud_test.go:336:21: undeclared name: `dns` (typecheck)
                        ManagedZones: []*dns.ManagedZone{
                                         ^
providers/dns/gcloud/googlecloud_test.go:355:13: undeclared name: `dns` (typecheck)
                rrslr := &dns.ResourceRecordSetsListResponse{
                          ^
providers/dns/gcloud/googlecloud_test.go:356:15: undeclared name: `dns` (typecheck)
                        Rrsets: []*dns.ResourceRecordSet{{
                                   ^
providers/dns/gcloud/googlecloud.go:20:2: "google.golang.org/api/dns/v1" imported but not used (typecheck)
        "google.golang.org/api/dns/v1"
        ^
providers/dns/gcloud/googlecloud_test.go:16:2: "google.golang.org/api/dns/v1" imported but not used (typecheck)
        "google.golang.org/api/dns/v1"
        ^
providers/dns/hyperone/internal/token.go:37:46: undeclared name: `jose` (typecheck)
func getRSASigner(privateKey, keyID string) (jose.Signer, error) {
                                             ^
providers/dns/hyperone/internal/token.go:65:44: undeclared name: `jose` (typecheck)
func (payload *Payload) buildToken(signer *jose.Signer) (string, error) {
                                           ^
providers/dns/hyperone/internal/token.go:43:9: undeclared name: `jose` (typecheck)
        key := jose.SigningKey{Algorithm: jose.RS256, Key: parsedKey}
               ^
providers/dns/hyperone/internal/token.go:45:16: undeclared name: `jose` (typecheck)
        signerOpts := jose.SignerOptions{}
                      ^
providers/dns/hyperone/internal/token.go:49:20: undeclared name: `jose` (typecheck)
        rsaSigner, err := jose.NewSigner(key, &signerOpts)
                          ^
providers/dns/hyperone/internal/token.go:10:2: "gopkg.in/square/go-jose.v2" imported but not used (typecheck)
        "gopkg.in/square/go-jose.v2"
        ^
make: *** [Makefile:39: checks] Error 1`

**Comment by marius-locomotion** [comment]
if you have the new `lego` binary already built, that may be easier, so I can just use that one, to pass the parameters and test with it.

thanks a lot,
Marius

**Comment by ldez** [comment]
the right command to build the binary is `make build`

**Comment by marius-locomotion** [comment]
ok, thank you. I am trying it now. It seems I am missing a bunch of go modules which need to be downloaded manually..

**Comment by ldez** [comment]
You don't need to download modules manually, you just have to run `go mod tidy` command.

**Comment by marius-locomotion** [comment]
I ran this command

`EPIK_SIGNATURE=<USER_API_SIG> ./dist/lego -m marius@manea.org --dns epik -d *.easynumbers.ca -d easynumbers.ca -s https://acme-staging-v02.api.letsencrypt.org/directory run`

but I am getting this error:

`2021/09/29 15:28:26 [INFO] [*.easynumbers.ca, easynumbers.ca] acme: Obtaining bundled SAN certificate
2021/09/29 15:28:30 [INFO] [*.easynumbers.ca] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/593284608
2021/09/29 15:28:30 [INFO] [easynumbers.ca] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/593284618
2021/09/29 15:28:30 [INFO] [*.easynumbers.ca] acme: use dns-01 solver
2021/09/29 15:28:30 [INFO] [easynumbers.ca] acme: Could not find solver for: tls-alpn-01
2021/09/29 15:28:30 [INFO] [easynumbers.ca] acme: Could not find solver for: http-01
2021/09/29 15:28:30 [INFO] [easynumbers.ca] acme: use dns-01 solver
2021/09/29 15:28:30 [INFO] [*.easynumbers.ca] acme: Preparing to solve DNS-01
2021/09/29 15:28:30 [INFO] [easynumbers.ca] acme: Preparing to solve DNS-01
2021/09/29 15:28:30 [INFO] [*.easynumbers.ca] acme: Cleaning DNS-01 challenge
2021/09/29 15:28:31 [WARN] [*.easynumbers.ca] acme: cleaning up failed: epik: code: 1, message: Unauthorized, description: Unauthorized: Signature was not provided or was invalid
2021/09/29 15:28:31 [INFO] [easynumbers.ca] acme: Cleaning DNS-01 challenge
2021/09/29 15:28:31 [WARN] [easynumbers.ca] acme: cleaning up failed: epik: code: 1, message: Unauthorized, description: Unauthorized: Signature was not provided or was invalid
2021/09/29 15:28:31 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/593284608
2021/09/29 15:28:31 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/593284618
2021/09/29 15:28:32 Could not obtain certificates:
        error: one or more domains had a problem:
[*.easynumbers.ca] [*.easynumbers.ca] acme: error presenting token: epik: code: 1, message: Unauthorized, description: Unauthorized: Signature was not provided or was invalid`

**Comment by ldez** [comment]
Your signature seems to be wrong.

https://registrar.epik.com/account/api-settings/

**Comment by marius-locomotion** [comment]
I found out the issue. The signature was not wrong, but the IP address allowed for API access was outdated. So I had to put the new IP address, and then it worked.

I ran it for another domain, and this was the output:

`2021/09/29 15:57:21 [INFO] [*.allmychannels.com, allmychannels.com] acme: Obtaining bundled SAN certificate
2021/09/29 15:57:22 [INFO] [*.allmychannels.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/593435758
2021/09/29 15:57:22 [INFO] [allmychannels.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/593435768
2021/09/29 15:57:22 [INFO] [*.allmychannels.com] acme: use dns-01 solver
2021/09/29 15:57:22 [INFO] [allmychannels.com] acme: Could not find solver for: tls-alpn-01
2021/09/29 15:57:22 [INFO] [allmychannels.com] acme: Could not find solver for: http-01
2021/09/29 15:57:22 [INFO] [allmychannels.com] acme: use dns-01 solver
2021/09/29 15:57:22 [INFO] [*.allmychannels.com] acme: Preparing to solve DNS-01
2021/09/29 15:57:23 [INFO] [allmychannels.com] acme: Preparing to solve DNS-01
2021/09/29 15:57:24 [INFO] [*.allmychannels.com] acme: Trying to solve DNS-01
2021/09/29 15:57:24 [INFO] [*.allmychannels.com] acme: Checking DNS record propagation using [192.168.100.1:53]
2021/09/29 15:57:26 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2021/09/29 15:57:31 [INFO] [*.allmychannels.com] The server validated our request
2021/09/29 15:57:31 [INFO] [allmychannels.com] acme: Trying to solve DNS-01
2021/09/29 15:57:32 [INFO] [allmychannels.com] acme: Checking DNS record propagation using [192.168.100.1:53]
2021/09/29 15:57:34 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2021/09/29 15:57:34 [INFO] [allmychannels.com] The server validated our request
2021/09/29 15:57:34 [INFO] [*.allmychannels.com] acme: Cleaning DNS-01 challenge
2021/09/29 15:57:35 [INFO] [allmychannels.com] acme: Cleaning DNS-01 challenge
2021/09/29 15:57:36 [INFO] [*.allmychannels.com, allmychannels.com] acme: Validations succeeded; requesting certificates
2021/09/29 15:57:37 [INFO] [*.allmychannels.com] Server responded with a certificate.`

**Review by marius-locomotion — APPROVED** [review]
tested with epik provider and works fine, thank you!

**Review by dmke — APPROVED** [review]
LGTM

**Pull request merged**
