### PR TITLE
added uds capability to http challenge server

### PR DESCRIPTION
**Pull request by trey-jones**
Addresses #1471 (opened by me, not long ago)
The semantics aren't perfect, but it's functional. Very minor changes and impacts.
Tests didn't all pass, but mine did!

Related to  #1472

### CODE REVIEW

**Comment by ldez** [comment]
Can you allow maintainers to edit your PR?

https://github.com/go-acme/lego/pull/1472#issuecomment-915565944

Screenshot_20211119_225057

**Comment by trey-jones** [comment]
That box is checked.

**Comment by ldez** [comment]
```console
$ git push --no-follow-tags --force-with-lease trey-jones 1485--http-challenge-uds:http-challenge-uds
ERROR: Permission to trey-jones/lego.git denied to ldez.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Then I don't understand why I cannot push on your branch.

**Comment by ldez** [comment]
I can update through the GitHub UI but I cannot push with git, so for me it's related to the configuration of the PR or of your fork.

**Comment by ldez** [comment]
Maybe it's a GitHub bug :thinking: I will close then re-open your PR.

**Comment by ldez** [comment]
Still the same problem, please double-check the PR settings and your fork settings.

**Comment by trey-jones** [comment]
I think I see what the problem is - I forked from the previous
(organization-owned) fork, rather than the main repo.  I'm sure that seemed
easier at the time.  I will try and resolve this later today.  Sorry for
the trouble.
[image: Cortex Logo]
Trey Jones
Senior Application Developer / Systems Administrator
678.692.8512 x118 <16786928512>
POLYGLOT <https://www.polyglotlabs.com/> | EYESORE
<https://www.eyesoreinc.com/> | CORTEX <https://www.cortexdigitalinc.com/>

We've expanded! Eyesore and Cortex
are now divisions of our new parent company,
Polyglot Labs. Click here to learn more!
<https://www.polyglotlabs.com/emails/brand-intro.html>

**Comment by ldez** [comment]
@trey-jones friendly ping

**Comment by trey-jones** [comment]
I've closed to delete my fork and create a new (hopefully mutable by you) PR from a fresh fork.  Thank you for your patience.

**Comment by trey-jones** [comment]
I hate to even ask, but after deleting the organization repo, my fork now lists this as the base repo, and I was able to recheck the box.  Can you try one more time to edit this PR?  And if it doesn't work, then I'll start over.  I've also merged from upstream, but I think that doesn't make any difference.

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
