### PR TITLE
Add yandex

### PR DESCRIPTION
**Pull request by truongdo**
Add yandex DNS provider

### CODE REVIEW

**Comment by xenolf** [comment]
Hey there! Thanks for providing this!
Did you mean to not include the provider into the CLI?

**Comment by truongdo** [comment]
Yandex is a quite popular service out there (they provide mail, dns, search services). I think it would be nice to have them in the library.

**Comment by lenovouser** [comment]
@truongdo he just wants you to include into the CLI. Otherwise people won't be able to use it.

**Comment by truongdo** [comment]
I just found out Yandex DNS API does not support case sensitivity, leading to failure when performing ACME challenges. I've contacted them for this problem and will include Yandex into CLI when they fix the issue.

**Comment by xenolf** [comment]
@truongdo did you hear anything back?

**Comment by truongdo** [comment]
They said they are aware of the problem and are working on a fix, but I don't know when they will release the fix.

**Comment by xenolf** [comment]
No problem. Thank you for the update! :)

**Comment by ldez** [comment]
@truongdo any new about case sensitivity issue?

**Comment by truongdo** [comment]
I haven’t heard anything from them since last year. I really don’t know if they are going to fix it or not.

**Comment by Akkarine** [comment]
Hello. Though Yandex didn't reply to @truongdo, here is a tiny project, made not so far ago that can get wildcard certificates: https://github.com/myallod/certbot-dns-pddyandex
So I believe, Yandex fixed the problem?

**Comment by ldez** [comment]
@Akkarine If you create a new PR to add Yandex are you able to do test for me?

**Comment by ldez** [comment]
@Akkarine If I create a new PR to add Yandex, can you do some tests for me?

**Comment by Akkarine** [comment]
@ldez Yes, of course.

**Comment by ldez** [comment]
Close in favor of #953

**Pull request closed without merging**
