### PR TITLE
Add DNS provider for Yandex.

### PR DESCRIPTION
**Pull request by ldez**
Add DNS provider for Yandex.

https://tech.yandex.com/domain/doc/concepts/api-dns-docpage/

Closes #278

---

ping @Akkarine, could you do:
```bash
rm -rf .lego

./lego -m your@email.com --dns yandex -d *.yourdomain.com -d yourdomain.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```

Note the wildcard domain is important.

If you have problems building lego, do not hesitate to ask me.

### CODE REVIEW

**Comment by Akkarine** [comment]
TXT DNS-record was successfully created, but did not cleaned. I believe that has similar roots as here: https://github.com/adferrand/docker-letsencrypt-dns/issues/58

image

Check failed probably to long DNS-propagation. Could I determine explicit DNS-server to perform checks? DNS-propagation from Yandex take around an hour to reach Let's encrypt. As workaround I've already found `YANDEX_POLLING_INTERVAL`.

**Comment by Akkarine** [comment]
`POLLING_INTERVAL` did not help.

image

From administration panel of Yandex DNS:

image

**Comment by ldez** [comment]
you can use `--dns.resolvers` https://go-acme.github.io/lego/usage/cli/

**Comment by ldez** [comment]
I fixed a small bug.

Could you clean your TXT records.

**Comment by Akkarine** [comment]
Now immediate falls to error:

image

**Comment by ldez** [comment]
I fixed the problem

**Comment by Akkarine** [comment]
Well, records are created and deleted, but even with google DNS 8.8.8.8 It can't check domain. Sometimes it is previous record, sometimes new was not propogated to 8.8.8.8.

image

**Comment by ldez** [comment]
It's a propagation issue, not related to the implementation of the provider.
The propagation can be long.

**Comment by ldez** [comment]
Just to be sure, are the TXT records deleted?

**Comment by Akkarine** [comment]
> Just to be sure, are the TXT records deleted?

Yes, no problems with that.

**Comment by Akkarine** [comment]
Changed polling interval to 1h, get new error. After that, DNS-record was not deleted.

```
user1@docker_server:~/lego/dist$ export YANDEX_POLLING_INTERVAL=3600
user1@docker_server:~/lego/dist$ ./lego -m ****@****.ru --dns.resolvers 8.8.8.8 --dns yandex -d *.infra.****.ru -s https://acme-staging-v02.api.letsencrypt.org/directory run
2019/08/20 16:27:26 [INFO] [*.infra.****.ru] acme: Obtaining bundled SAN certificate
2019/08/20 16:27:27 [INFO] [*.infra.****.ru] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/5000500
2019/08/20 16:27:27 [INFO] [*.infra.****.ru] acme: use dns-01 solver
2019/08/20 16:27:27 [INFO] [*.infra.****.ru] acme: Preparing to solve DNS-01
2019/08/20 16:27:28 [INFO] [*.infra.****.ru] acme: Trying to solve DNS-01
2019/08/20 16:27:28 [INFO] [*.infra.****.ru] acme: Checking DNS record propagation using [8.8.8.8:53]
2019/08/20 16:27:28 [INFO] Wait for propagation [timeout: 1m0s, interval: 1h0m0s]
2019/08/20 16:27:28 [INFO] [*.infra.****.ru] acme: Waiting for DNS record propagation.
2019/08/20 17:27:28 [INFO] [*.infra.****.ru] acme: Cleaning DNS-01 challenge
2019/08/20 17:27:35 [INFO] nonce error retry: acme: error: 400 :: POST :: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/5000500 :: urn:ietf:params:acme:error:badNonce :: JWS has an invalid anti-replay nonce: "00029hG8goYb-TbK7Jh1w3lKsFbrmIa1igXD1CZ6Xr4fD1o", url:
2019/08/20 17:27:36 Could not obtain certificates:
        acme: Error -> One or more domains had a problem:
[*.infra.****.ru] time limit exceeded: last error: NS dns2.yandex.net. did not return the expected TXT record [fqdn: _acme-challenge.infra.****.ru., value: GNjcnhFNTsFmFKydQ7ct1TTC3tIHn3pKl0XKV5ZN8jo]:
```

**Comment by ldez** [comment]
> DNS-record was not deleted.
The TXT records must have been deleted in Yandex, you must wait for the deletion to be propagated to the DNS servers.

So when you say "DNS-record was not deleted.", do you speak about Yandex or DNS servers?

**Comment by ldez** [comment]
I added some logs.

could you remove manually the TXT records from Yandex and retry?

**Comment by Akkarine** [comment]
> So when you say "DNS-record was not deleted.", do you speak about Yandex or DNS servers?
I speak about Yandex admin panel. But now I doubt if forgot to press F5 before manual deletion.

I've set polling to 2h. If it fails again, I'll try to 12h and give feedback after that.

**Comment by Akkarine** [comment]
Even 12h was not enough. But records were successfully created and deleted.
```
root@testing:~/lego/dist# cat log 
2019/08/20 21:40:54 [INFO] [*.infra.****.ru] acme: Obtaining bundled SAN certificate
2019/08/20 21:40:55 [INFO] [*.infra.****.ru] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/5032427
2019/08/20 21:40:55 [INFO] [*.infra.****.ru] acme: use dns-01 solver
2019/08/20 21:40:55 [INFO] [*.infra.****.ru] acme: Preparing to solve DNS-01
2019/08/20 21:40:55 [INFO] Present: infra.****.ru :: ****.ru. :: _acme-challenge.infra :: joUb3qAuNo0LkrDGgYgGFwnGZBdko2E88ECTj1vyHR8
2019/08/20 21:40:56 [INFO] Present: infra.****.ru :: 27968035 :: TXT :: ****.ru :: _acme-challenge.infra :: joUb3qAuNo0LkrDGgYgGFwnGZBdko2E88ECTj1vyHR8
2019/08/20 21:40:56 [INFO] [*.infra.****.ru] acme: Trying to solve DNS-01
2019/08/20 21:40:56 [INFO] [*.infra.****.ru] acme: Checking DNS record propagation using [10.10.1.1:53]
2019/08/20 21:40:56 [INFO] Wait for propagation [timeout: 1m0s, interval: 12h0m0s]
2019/08/20 21:40:57 [INFO] [*.infra.****.ru] acme: Waiting for DNS record propagation.
2019/08/21 09:40:57 [INFO] [*.infra.****.ru] acme: Cleaning DNS-01 challenge
2019/08/21 09:40:58 [INFO] CleanUp, skip: 26645549 :: A :: ****.ru :: *.dev :: 88.87.78.110
2019/08/21 09:40:58 [INFO] CleanUp, skip: 27747390 :: A :: ****.ru :: *.infra :: 88.87.78.110
2019/08/21 09:40:58 [INFO] CleanUp, skip: 24568036 :: A :: ****.ru :: @ :: 130.193.58.80
2019/08/21 09:40:58 [INFO] CleanUp, skip: 7609719 :: MX :: ****.ru :: @ :: mx.yandex.net.
2019/08/21 09:40:58 [INFO] CleanUp, skip: 7609715 :: TXT :: ****.ru :: @ :: v=spf1 redirect=_spf.yandex.net
2019/08/21 09:40:58 [INFO] CleanUp, remove: infra.****.ru :: joUb3qAuNo0LkrDGgYgGFwnGZBdko2E88ECTj1vyHR8
2019/08/21 09:40:59 [INFO] nonce error retry: acme: error: 400 :: POST :: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/5032427 :: urn:ietf:params:acme:error:badNonce :: JWS has an invalid anti-replay nonce: "0001xJdZXcNTyjOof-LvKomIYDs1uaQc3yPDipt0hoaynRI", url: 
2019/08/21 09:41:00 Could not obtain certificates:
        acme: Error -> One or more domains had a problem:
[*.infra.****.ru] time limit exceeded: last error: NS dns2.yandex.net. did not return the expected TXT record [fqdn: _acme-challenge.infra.****.ru., value: joUb3qAuNo0LkrDGgYgGFwnGZBdko2E88ECTj1vyHR8]: 
[1]+  Exit 1                  ./lego -m ****@****.ru -a --dns yandex -d *.infra.****.ru -s https://acme-staging-v02.api.letsencrypt.org/directory run &> log
root@testing:~/lego/dist# fg
```

**Comment by ldez** [comment]
Maybe those tools can help you to evaluate the propagation:
- http://www.propagationdns.com/
- https://dnsmap.io

**Comment by Akkarine** [comment]
> Maybe those tools can help you to evaluate the propagation:
> 
> * http://www.propagationdns.com/
> * https://dnsmap.io

I'm using https://www.gdnspc.com . Found dnsmap.io useless (says "no" even for yandex itself :) ). propagationdns.com though will be useful, thanks.

Do you know, which DNS servers Let's Encrypt use to check records?

**Comment by ldez** [comment]
I don't know, and I don't know if it's deterministic or not.

**Comment by Akkarine** [comment]
I'm starting to think, that it is bug in logic somewhere. I've spent days since my last coment trying to obtain a WC certificate. I've tried 12h and 24h delay with 1 day with cleared records (to be sure, that there is no other data left in DNS servers). When this also didn't work, I made final clean test with 48h challenge (It's time which Yandex guarantee that records will be spreaded).

Even after around an hour DNS check was looking like that:
image

But unfortunately:
```
root@testing:~/lego/dist# cat log
2019/08/24 13:21:31 [INFO] [*.infra.****.ru] acme: Obtaining bundled SAN certificate
2019/08/24 13:21:32 [INFO] [*.infra.****.ru] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/5595611
2019/08/24 13:21:32 [INFO] [*.infra.****.ru] acme: use dns-01 solver
2019/08/24 13:21:32 [INFO] [*.infra.****.ru] acme: Preparing to solve DNS-01
2019/08/24 13:21:32 [INFO] Present: infra.****.ru :: ****.ru. :: _acme-challenge.infra :: DTg6969J-ndG5nt0zrc1bssgE4-9Owey-sqpDXyk6m4
2019/08/24 13:21:33 [INFO] Present: infra.****.ru :: 27990403 :: TXT :: ****.ru :: _acme-challenge.infra :: DTg6969J-ndG5nt0zrc1bssgE4-9Owey-sqpDXyk6m4
2019/08/24 13:21:33 [INFO] [*.infra.****.ru] acme: Trying to solve DNS-01
2019/08/24 13:21:33 [INFO] [*.infra.****.ru] acme: Checking DNS record propagation using [10.10.1.1:53]
2019/08/24 13:21:33 [INFO] Wait for propagation [timeout: 1m0s, interval: 48h0m0s]
2019/08/24 13:21:34 [INFO] [*.infra.****.ru] acme: Waiting for DNS record propagation.
2019/08/26 13:21:34 [INFO] [*.infra.****.ru] acme: Cleaning DNS-01 challenge
2019/08/26 13:21:35 [INFO] CleanUp, skip: 26645549 :: A :: ****.ru :: *.dev :: **.**.**.***
2019/08/26 13:21:35 [INFO] CleanUp, skip: 27747390 :: A :: ****.ru :: *.infra :: **.**.**.***
2019/08/26 13:21:35 [INFO] CleanUp, skip: 24568036 :: A :: ****.ru :: @ :: **.**.**.***
2019/08/26 13:21:35 [INFO] CleanUp, skip: 7609719 :: MX :: ****.ru :: @ :: mx.yandex.net.
2019/08/26 13:21:35 [INFO] CleanUp, skip: 7609715 :: TXT :: ****.ru :: @ :: v=spf1 redirect=_spf.yandex.net
2019/08/26 13:21:35 [INFO] CleanUp, remove: infra.****.ru :: DTg6969J-ndG5nt0zrc1bssgE4-9Owey-sqpDXyk6m4
2019/08/26 13:21:36 [INFO] nonce error retry: acme: error: 400 :: POST :: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/5595611 :: urn:ietf:params:acme:error:badNonce :: JWS has an invalid anti-replay nonce: "0001rlpsGM0_KzXf-G6_IjFy-nGb5BMXj8mwef3vuEyyu4A", url:
2019/08/26 13:21:37 Could not obtain certificates:
        acme: Error -> One or more domains had a problem:
[*.infra.****.ru] time limit exceeded: last error: NS dns2.yandex.net. did not return the expected TXT record [fqdn: _acme-challenge.infra.****.ru., value: DTg6969J-ndG5nt0zrc1bssgE4-9Owey-sqpDXyk6m4]:
```

That `JWS has an invalid anti-replay nonce` I've seen every time it's failed. 
Made `rm -rf lego/` each time.
What also make me feel that it is actually bug: I made another wildcard certificate relatively easy with this tool https://github.com/adferrand/docker-letsencrypt-dns/issues/58#issuecomment-522496577

What could be not right? @ldez

**Comment by ldez** [comment]
I need to investigate :thinking:

**Comment by Akkarine** [comment]
How goes the investigation?

**Comment by ldez** [comment]
good reminder, I will take a bit of time on that.

**Comment by ldez** [comment]
I found the problem, you have to change the TTL.

`YANDEX_TTL=86400` for one day

**Comment by ldez** [comment]
I'm looking for someone who could test this PR.

**Comment by Akkarine** [comment]
I'll try on a week.

**Comment by Akkarine** [comment]
Hello. I cant' build updated branch:

```
root@testing:~/lego# git pull
Already up to date.
root@testing:~/lego# git branch
* feature/add-yandex
  master
root@testing:~/lego# make build
BIN_OUTPUT: dist/lego
rm -rf dist/ builds/ cover.out
Version: d150bbe607c72dd489b143985f24e93877a77d18
go build -v -trimpath -ldflags '-X "main.version=d150bbe607c72dd489b143985f24e93877a77d18"' -o  dist/lego ./cmd/lego/
flag provided but not defined: -trimpath
usage: go build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
Makefile:24: recipe for target 'build' failed
make: *** [build] Error 2
root@testing:~/lego#
```

**Comment by ldez** [comment]
You have use use go1.14

**Comment by Akkarine** [comment]
Started 48h challenge. DNS record appeared at hosting panel.

**Comment by Akkarine** [comment]
@ldez 
Unfortunately, sert was not obtained. DNS record successfully removed.
```
root@testing:~/lego/dist# cat log
2020/04/25 04:13:00 No key found for account ****@****.ru. Generating a P384 key                                                                        .
2020/04/25 04:13:00 Saved key to /root/lego/dist/.lego/accounts/acme-staging-v02                                                                        .api.letsencrypt.org/****@****.ru/keys/****@****.ru.key
2020/04/25 04:13:01 [INFO] acme: Registering account for ****@****.ru
!!!! HEADS UP !!!!

                Your account credentials have been saved in your Let's Encrypt
                configuration directory at "/root/lego/dist/.lego/accounts".
                You should make a secure backup of this folder now. This
                configuration directory will also contain certificates and
                private keys obtained from Let's Encrypt so making regular
                backups of this folder is ideal.2020/04/25 04:13:01 [INFO] [*.sr                                                                        v.****.ru] acme: Obtaining bundled SAN certificate
2020/04/25 04:13:02 [INFO] [*.srv.****.ru] AuthURL: https://acme-staging-v02.api                                                                        .letsencrypt.org/acme/authz-v3/51440695
2020/04/25 04:13:02 [INFO] [*.srv.****.ru] acme: use dns-01 solver
2020/04/25 04:13:02 [INFO] [*.srv.****.ru] acme: Preparing to solve DNS-01
2020/04/25 04:13:02 [INFO] [*.srv.****.ru] acme: Trying to solve DNS-01
2020/04/25 04:13:02 [INFO] [*.srv.****.ru] acme: Checking DNS record propagation                                                                         using [10.10.1.1:53]
2020/04/25 04:13:02 [INFO] Wait for propagation [timeout: 1m0s, interval: 48h0m0                                                                        s]
2020/04/25 04:13:03 [INFO] [*.srv.****.ru] acme: Waiting for DNS record propagat                                                                        ion.
2020/04/27 04:13:03 [INFO] [*.srv.****.ru] acme: Cleaning DNS-01 challenge
2020/04/27 04:13:05 [INFO] retry due to: acme: error: 400 :: POST :: https://acm                                                                        e-staging-v02.api.letsencrypt.org/acme/authz-v3/51440695 :: urn:ietf:params:acme                                                                        :error:badNonce :: JWS has an invalid anti-replay nonce: "0001d6KZ1GaZrI0BXY2q1p                                                                        sq5rmAdUb90dt9rmePghVg5iQ", url:
2020/04/27 04:13:06 [INFO] Deactivating auth: https://acme-staging-v02.api.letse                                                                        ncrypt.org/acme/authz-v3/51440695
2020/04/27 04:13:06 Could not obtain certificates:
        acme: Error -> One or more domains had a problem:
[*.srv.****.ru] time limit exceeded: last error: NS dns1.yandex.net. returned NX                                                                        DOMAIN for _acme-challenge.srv.****.ru.
root@testing:~/lego/dist#
```

**Comment by ldez** [comment]
```
NS dns1.yandex.net. returned NXDOMAIN for _acme-challenge.srv.****.ru.
```

This error comes from the verification of the propagation of the records, this verification sends DNS calls to try to validate the propagation of the TXT records using nameservers (from `/etc/resolv.conf` or from the `--dns.resolvers` option).
So the error comes from the nameservers it-self.

Now, I think that the issue is related to your nameservers or your DNS configuration.

FYI: NXDOMAIN -> Non eXistent DOMAIN

**Comment by ldez** [comment]
could you explain why you are using `10.10.1.1:53` as DNS resolvers ?

**Comment by Akkarine** [comment]
> ```
> NS dns1.yandex.net. returned NXDOMAIN for _acme-challenge.srv.****.ru.
> ```
> 
> This error comes from the verification of the propagation of the records, this verification sends DNS calls to try to validate the propagation of the TXT records using nameservers (from `/etc/resolv.conf` or from the `--dns.resolvers` option).
> So the error comes from the nameservers it-self.
> 
> Now, I think that the issue is related to your nameservers or your DNS configuration.
> 
> FYI: NXDOMAIN -> Non eXistent DOMAIN

I'm using this script to perform long polls:
```
#!/bin/sh
sleep 5s
export YANDEX_PDD_TOKEN=****
export YANDEX_POLLING_INTERVAL=172800
./lego -m ****@****.ru -a --dns yandex -d *.srv.****.ru -s https://acme-staging-v02.api.letsencrypt.org/directory run > log
```
start this with ./test_my_domain.sh &
then disown %1

As you see, there is no `--dns.resolvers` option. 

I'm testing in container on hypervisor behind router, so `/etc/resolv.conf` contains 
```
# --- BEGIN PVE ---
search ****.ru
nameserver 10.10.1.1
# --- END PVE ---
```
domain in record `search ****.ru` same as `*.srv.****.ru`
I don't know if I should change something.

Router works as relay DNS server. Just redirects requests to provider's DNS and cahces results (but he is not associates itself with my domain name and don't know where is `srv.****.ru`, shouldn't be error here).

I'll try another run with `--dns.resolvers 8.8.8.8` option.

**Comment by ldez** [comment]
@Akkarine could you try with a lower propagation timeout? Because I think that you don't need to wait 48H to get a certificate.

So, if you can, could you try with maybe 30min, and if it fail you can try 2h, then 12h, ...

**Comment by Akkarine** [comment]
Omg that was fast:
```
root@testing:~/lego/dist# cat log
2020/04/27 15:29:15 [INFO] [*.srv.****.ru] acme: Obtaining bundled SAN certificate
2020/04/27 15:29:16 [INFO] [*.srv.****.ru] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/51898305
2020/04/27 15:29:16 [INFO] [*.srv.****.ru] acme: use dns-01 solver
2020/04/27 15:29:16 [INFO] [*.srv.****.ru] acme: Preparing to solve DNS-01
2020/04/27 15:29:17 [INFO] [*.srv.****.ru] acme: Trying to solve DNS-01
2020/04/27 15:29:17 [INFO] [*.srv.****.ru] acme: Checking DNS record propagation using [8.8.8.8:53]
2020/04/27 15:29:17 [INFO] Wait for propagation [timeout: 1m0s, interval: 48h0m0s]
2020/04/27 15:29:21 [INFO] [*.srv.****.ru] The server validated our request
2020/04/27 15:29:21 [INFO] [*.srv.****.ru] acme: Cleaning DNS-01 challenge
2020/04/27 15:29:22 [INFO] [*.srv.****.ru] acme: Validations succeeded; requesting certificates
2020/04/27 15:29:23 [INFO] [*.srv.****.ru] Server responded with a certificate.
```

**Comment by ldez** [comment]
Great news !!!! :tada:

**Comment by ldez** [comment]
So, can i now consider that everything is working properly?

**Comment by Akkarine** [comment]
I think there is should be notice somewhere in docs to use`--dns.resolvers` then for cases, that have same configuration as mine.

**Comment by Akkarine** [comment]
> So, can I now consider that everything is working properly?

Yes, all certificates in place. Thank you for all patience and work on this issue )

**Pull request merged**
