### PR TITLE
azure: new implementation based on the new API client

### LINKED ISSUE #1205: Support azure cli authentication
Hi, I'd like to authenticate using the az cli and avoid any env vars. 
Terraform uses https://github.com/hashicorp/go-azure-helpers/tree/master/authentication to support it.

Is this something anyone has looked at?

I'm happy to put together a PR, would calling out to the library just for cli be ok?

### LINKED ISSUE #1624: Azure DNS auth via client credentials - allow use of client certificate
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Other

### Detailed Description

Currently you can specify client id and secret via env variables, but it looks like you are not able to use a client certificate to authenticate via service principal. As far as I can see, we would need to supply the additional env variables to autorest (https://github.com/Azure/go-autorest/blob/v10.14.0/autorest/azure/auth/auth.go#L83 ) to support client certificates.

Looks like a non-invasive change, which one could contribute, what do you think?

### PR DESCRIPTION
**Pull request by pchanvallon**
**New Azure DNS provider implementation**

Since `Azure/go-autorest` package has been deprecated, `Azure/azure-sdk-for-go` is the new package to use.
Therefore this new `azuredns` DNS provider will be implemented using this new SDK and gradually will replace the previous `azure` provider.

This new implementation will keep almost the same interface as the previous one, but also [add some other authentication's means](https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication) like OIDC authentication, Azure CLI or AKS workload identity.

Fixes #1205
Fixes #1624

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

first, can you clean the go.mod?

The main problem with this PR is because of the breaking change related to the removal of some env var and the other changes not directly related to az.
So the best approach is to create a dedicated constructor for this.

**Comment by pchanvallon** [comment]
Hello @ldez,

Thank you for you answer.

As described in the `.toml` file, the env vars removed from the code are still managed by the Azure SDK authentication method `azidentity.NewDefaultAzureCredential` (cf. [documentation](https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication?tabs=bash)).

This is the new way Azure SDK manages the authentication : it automatically handle client env vars for client secret or certificate, or redirect authentication to other methods if they are not set.

Therefore, it will not break the current behaviour but add new authentication methods.

**Comment by ldez** [comment]
lego is used as a library, in this case, the env vars are optional and the `Config` is used.
I was not clear in my previous message, because I said env vars but it was related to configuration.
So I will prefer a new constructor.

**Comment by ldez** [comment]
you have done a wrong rebase/merge, you have to clean your branch.

**Comment by pchanvallon** [comment]
I have updated the code following you remarks. 
It also made me realize that I still need to manage client secret credentials as it might be needed.

**Comment by ldez** [comment]
I was talking about a constructor not a full provider implementation :wink:

**Comment by pchanvallon** [comment]
From my point of view, it is the best way of avoiding a breaking change and managing the migration from the deprecated version. 

As the `Azure/go-autorest` library will no longer be supported from march 2023, I think it can be useful to add a deprecation notice on the initial `azure` DNS provider, to warn users to use the new one.

This way, users and third-party softwares using lego can switch smoothly.

**Comment by pchanvallon** [comment]
Hello @ldez, what's you opinion about this proposition ? 
Do you still need a new constructor ? If it is the case, then I'll do it.

**Comment by ldez** [comment]
I'm currently working on another part of lego for several weeks, I don't have time now to review your PR.
So keep your PR as this, I will think about provider vs constructor as soon as possible.

**Comment by pchanvallon** [comment]
Hello @ldez, did you manage to get some more time recently to think about this PR ?

I have some colleagues of mine that are really interested in this change.
Looking forward to your decision.

**Comment by erictg** [comment]
This won't work for workload identity as is, the dependency to `github.com/Azure/azure-sdk-for-go/sdk/azidentity` needs to be updated to `v1.3.0`. The current azidentity version in this pr points to `v1.2.1` which doesn't support workload identity

**Comment by pchanvallon** [comment]
Hello @erictg,
Thank you for comment, I have updated the version to allow this kind of authentication.

**Comment by erictg** [comment]
@pchanvallon no problem. It may also be worth adding a reference to the [workload identity docs](https://azure.github.io/azure-workload-identity/docs/topics/service-account-labels-and-annotations.html) reminding users that when using this in kubernetes they have to set specific labels/annotations for it to actually work. I've run into a lot of issues with workload identity so I think this would help :)

**Comment by pchanvallon** [comment]
@erictg, I also had some trouble to use it, so yes I agree with you on this point.
I have added a quick summary of the steps to follow in order to make it working.

**Comment by pchanvallon** [comment]
Hello @ldez, some tests are failing but they are not related to my changes. Maybe a transient issue, is it possible to re-run failed jobs ?

**Comment by ldez** [comment]
I squash and rebase your branch.

Based on the fact that [autorest](https://github.com/Azure/go-autorest/) is now dead, your provider can become the full replacement of the old Azure provider. (We will not remove the old implementation for now).

I will consider your PR like a new DNS provider and so I will ask you the same things.

---

In order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests (units)
```shell
make test
```
- [ ] add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help, documentation, and readme.
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`

**Comment by pchanvallon** [comment]
Hello @ldez,

Thank you for the update.

I have updated the implementation of this new provider to have almost the same interface as the previous `azure` one.

Here are the status of the required checks : 

- [x] be able to maintain this provider
- [x] add tests (units & "live") :
``` bash
go test -v -cover ./providers/dns/azuredns/...
=== RUN   TestNewDNSProvider
=== RUN   TestNewDNSProvider/success
=== RUN   TestNewDNSProvider/unknown_environment
--- PASS: TestNewDNSProvider (0.00s)
    --- PASS: TestNewDNSProvider/success (0.00s)
    --- PASS: TestNewDNSProvider/unknown_environment (0.00s)
=== RUN   TestNewDNSProviderConfig
=== RUN   TestNewDNSProviderConfig/success_(public)
=== RUN   TestNewDNSProviderConfig/success_(private)
=== RUN   TestNewDNSProviderConfig/SubscriptionID_missing
=== RUN   TestNewDNSProviderConfig/ResourceGroup_missing
--- PASS: TestNewDNSProviderConfig (0.00s)
    --- PASS: TestNewDNSProviderConfig/success_(public) (0.00s)
    --- PASS: TestNewDNSProviderConfig/success_(private) (0.00s)
    --- PASS: TestNewDNSProviderConfig/SubscriptionID_missing (0.00s)
    --- PASS: TestNewDNSProviderConfig/ResourceGroup_missing (0.00s)
=== RUN   TestLivePresent
--- PASS: TestLivePresent (2.33s)
=== RUN   TestLiveCleanUp
--- PASS: TestLiveCleanUp (2.81s)
PASS
        github.com/go-acme/lego/v4/providers/dns/azuredns       coverage: 51.8% of statements
ok      github.com/go-acme/lego/v4/providers/dns/azuredns       5.446s  coverage: 51.8% of statements
```

- [x] add a  [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [x] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed)
- [x] do `go mod tidy`

Please let me know if I have to change anything before merging it.

**Comment by ldez** [comment]
You have to follow the checklist https://github.com/go-acme/lego/pull/1830#issuecomment-1614865300

Can you also update the PR description?

**Comment by pchanvallon** [comment]
Hello @ldez,

I have completed the missing checks : 

- [x] add a description to your PR
- [x] have a homogeneous design with the other providers : as my implementation is based on the previous `azure` DNS provider, so from my point of view it is homogeneous. Don’t hesitate to let me know if something is not.
- [x] generate CLI help, documentation, and readme
- [x] be able to do: (and put the output of this command to a comment in your PR)

```
$ rm -rf .lego                                                                                                                                                                        
$ ./lego -m paul@sendora.io --dns azuredns -d ‘*.sendora.io’ -d 'sendora.io' -s 'https://acme-staging-v02.api.letsencrypt.org/directory' run
2023/07/06 09:49:33 No key found for account paul@sendora.io. Generating a P256 key.
2023/07/06 09:49:33 Saved key to /Users/paulchanvallon/Projects/git/perso/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/paul@sendora.io/keys/paul@sendora.io.key
2023/07/06 09:49:34 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf
Do you accept the TOS? Y/n
y
2023/07/06 09:49:35 [INFO] acme: Registering account for paul@sendora.io
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/Users/paulchanvallon/Projects/git/perso/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2023/07/06 09:49:35 [INFO] [*.sendora.io, sendora.io] acme: Obtaining bundled SAN certificate
2023/07/06 09:49:36 [INFO] [*.sendora.io] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/7188269094
2023/07/06 09:49:36 [INFO] [sendora.io] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/7188269104
2023/07/06 09:49:36 [INFO] [*.sendora.io] acme: use dns-01 solver
2023/07/06 09:49:36 [INFO] [sendora.io] acme: Could not find solver for: tls-alpn-01
2023/07/06 09:49:36 [INFO] [sendora.io] acme: Could not find solver for: http-01
2023/07/06 09:49:36 [INFO] [sendora.io] acme: use dns-01 solver
2023/07/06 09:49:36 [INFO] [*.sendora.io] acme: Preparing to solve DNS-01
2023/07/06 09:49:40 [INFO] [sendora.io] acme: Preparing to solve DNS-01
2023/07/06 09:49:42 [INFO] [*.sendora.io] acme: Trying to solve DNS-01
2023/07/06 09:49:42 [INFO] [*.sendora.io] acme: Checking DNS record propagation using [192.168.1.1:53]
2023/07/06 09:49:44 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
2023/07/06 09:49:50 [INFO] [*.sendora.io] The server validated our request
2023/07/06 09:49:50 [INFO] [sendora.io] acme: Trying to solve DNS-01
2023/07/06 09:49:50 [INFO] [sendora.io] acme: Checking DNS record propagation using [192.168.1.1:53]
2023/07/06 09:49:52 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
2023/07/06 09:49:57 [INFO] [sendora.io] The server validated our request
2023/07/06 09:49:57 [INFO] [*.sendora.io] acme: Cleaning DNS-01 challenge
2023/07/06 09:49:58 [INFO] [sendora.io] acme: Cleaning DNS-01 challenge
2023/07/06 09:49:59 [INFO] [*.sendora.io, sendora.io] acme: Validations succeeded; requesting certificates
2023/07/06 09:49:59 [INFO] Wait for certificate [timeout: 30s, interval: 500ms]
2023/07/06 09:50:00 [INFO] [*.sendora.io] Server responded with a certificate.
```

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
