### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by ldez**
- https://github.com/akamai/AkamaiOPEN-edgegrid-golang/compare/v0.9.18...v1.1.0
- https://github.com/aliyun/alibaba-cloud-sdk-go/compare/v1.61.458...v1.61.976
- https://github.com/aws/aws-sdk-go/compare/v1.30.20...v1.37.27
- https://github.com/cenkalti/backoff/compare/v4.0.2...v4.1.0
- https://github.com/cloudflare/cloudflare-go/compare/v0.13.2...v0.14.0
- https://github.com/exoscale/egoscale/compare/v0.23.0...v1.19.0
- https://github.com/linode/linodego/compare/v0.21.0...v0.25.3
- https://github.com/liquidweb/liquidweb-go/compare/v1.6.1...v1.6.3
- https://github.com/miekg/dns/compare/v1.1.31...v1.1.40
- https://github.com/oracle/oci-go-sdk/compare/v24.2.0...v24.3.0
- https://github.com/pquerna/otp/compare/v1.2.0...v1.3.0
- https://github.com/transip/gotransip/compare/v6.2.0...v6.6.0
- https://github.com/vultr/govultr/compare/v2.0.0...v2.4.0
- https://github.com/ns1/ns1-go/compare/v2.4.2...v2.4.4
- https://github.com/miekg/dns/compare/v1.1.31...v1.1.40

The changes in the RFC2136 provider are related to https://github.com/miekg/dns/pull/1187

### CODE REVIEW

**Review by dmke — APPROVED** [review]
LGTM

**Comment by mhoran** [comment]
Looks like exoscale/egoscale was bumped to v1.19.0 again, which doesn't exist on GitHub. This was last fixed in #1244. It seems the latest version of exoscale/egoscale is v0.46.0, though v1.19.0 still exists on https://pkg.go.dev/github.com/exoscale/egoscale?tab=versions.

**Comment by ldez** [comment]
I forgot that :facepalm: I will fix

**Comment by mhoran** [comment]
No worries, thanks!

**Pull request merged**
