### PR TITLE
Add DNS provider for Mythic beasts DNSv2

### LINKED ISSUE #1124: Support for Mythic Beasts DNSv2 API
My employer needs support for [Mythic Beasts' DNSv2 API][dnsv2] in order to better support our infrastructure using Lego.  As such, we need Lego to support the API.

I am prepared to do the work to implement this, though I appreciate this is a beta API as far as Mythic Beasts are concerned, we need it for the delegated permissions support it has over their v1 API.

Would this be something the Lego project would consider merging once I'm done?

[dnsv2]: https://www.mythic-beasts.com/support/api/dnsv2

### PR DESCRIPTION
**Pull request by danielsilverstone-ct**
This PR implements Mythic Beasts DNSv2 API support (see https://www.mythic-beasts.com/support/api/dnsv2)

I cribbed a lot from the `dyn` DNS-01 provider and from others in the set so I hope the code isn't too awful.  It's my first time ever writing GoLang code so I expect there'll be some issues.

If merged, this fixes #1124

### CODE REVIEW

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests (units)
```shell
make test
```
- [ ] add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add the provider to the [readme.md](https://github.com/go-acme/lego#dns-providers)
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help and documentation
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`

**Comment by danielsilverstone-ct** [comment]
Regarding the command you want run, to include a wildcard domain -- quite obviously I do not have example.com access on my DNS provider -- is the goal simply to check for any domain that both wildcard and non-wildcard options work?

**Comment by danielsilverstone-ct** [comment]
```
equanimity(git)% rm -rf .lego && dist/lego -m your@email.com --dns mythicbeasts -d "*.kinnison.providinggenius.com" -d kinnison.providinggenius.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
2020/04/27 14:16:26 No key found for account your@email.com. Generating a P384 key.
2020/04/27 14:16:26 Saved key to /home/danielsilverstone/dev-git/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/your@email.com/keys/your@email.com.key
2020/04/27 14:16:27 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n

2020/04/27 14:16:28 [INFO] acme: Registering account for your@email.com
!!!! HEADS UP !!!!

		Your account credentials have been saved in your Let's Encrypt
		configuration directory at "/home/danielsilverstone/dev-git/lego/.lego/accounts".
		You should make a secure backup	of this folder now. This
		configuration directory will also contain certificates and
		private keys obtained from Let's Encrypt so making regular
		backups of this folder is ideal.2020/04/27 14:16:28 [INFO] [*.kinnison.providinggenius.com, kinnison.providinggenius.com] acme: Obtaining bundled SAN certificate
2020/04/27 14:16:29 [INFO] [*.kinnison.providinggenius.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/51971685
2020/04/27 14:16:29 [INFO] [kinnison.providinggenius.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/51971686
2020/04/27 14:16:29 [INFO] [*.kinnison.providinggenius.com] acme: use dns-01 solver
2020/04/27 14:16:29 [INFO] [kinnison.providinggenius.com] acme: Could not find solver for: tls-alpn-01
2020/04/27 14:16:29 [INFO] [kinnison.providinggenius.com] acme: Could not find solver for: http-01
2020/04/27 14:16:29 [INFO] [kinnison.providinggenius.com] acme: use dns-01 solver
2020/04/27 14:16:29 [INFO] [*.kinnison.providinggenius.com] acme: Preparing to solve DNS-01
2020/04/27 14:16:30 [INFO] [kinnison.providinggenius.com] acme: Preparing to solve DNS-01
2020/04/27 14:16:31 [INFO] [*.kinnison.providinggenius.com] acme: Trying to solve DNS-01
2020/04/27 14:16:31 [INFO] [*.kinnison.providinggenius.com] acme: Checking DNS record propagation using [127.0.0.1:53]
2020/04/27 14:16:31 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2020/04/27 14:16:31 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:16:33 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:16:35 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:16:37 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:16:39 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:16:41 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:16:43 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:16:45 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:16:47 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:16:49 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:16:51 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:16:53 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:16:55 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:16:57 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:16:59 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:17:01 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:17:03 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:17:06 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:17:08 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:17:10 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:17:13 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:17:15 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:17:17 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:17:21 [INFO] [*.kinnison.providinggenius.com] acme: Waiting for DNS record propagation.
2020/04/27 14:17:28 [INFO] [*.kinnison.providinggenius.com] The server validated our request
2020/04/27 14:17:28 [INFO] [kinnison.providinggenius.com] acme: Trying to solve DNS-01
2020/04/27 14:17:28 [INFO] [kinnison.providinggenius.com] acme: Checking DNS record propagation using [127.0.0.1:53]
2020/04/27 14:17:28 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2020/04/27 14:17:28 [INFO] [kinnison.providinggenius.com] The server validated our request
2020/04/27 14:17:28 [INFO] [*.kinnison.providinggenius.com] acme: Cleaning DNS-01 challenge
2020/04/27 14:17:29 [INFO] [kinnison.providinggenius.com] acme: Cleaning DNS-01 challenge
2020/04/27 14:17:29 [INFO] [*.kinnison.providinggenius.com, kinnison.providinggenius.com] acme: Validations succeeded; requesting certificates
2020/04/27 14:17:30 [INFO] [*.kinnison.providinggenius.com] Server responded with a certificate.
equanimity(git)%```

**Comment by danielsilverstone-ct** [comment]
The test failure (waitForTimeout) seems unrelated to my change.  Is it spurious?

**Comment by danielsilverstone-ct** [comment]
@ldez Thank you for tracking as I completed those last parts, I think the CI is now green so I assume I'm waiting on you (or someone else) to have the time and energy to do a code review.  As such I'll relax for a bit :grin:

**Comment by danielsilverstone-ct** [comment]
@ldez Thank you for those changes, they look nice.  Should I fold them into the main commits, or leave it as a separate commit?  The current Travis failure looks like a travis snafu since it couldn't download something.

**Comment by danielsilverstone-ct** [comment]
Thank you for the merge @ldez I have filed #1129 to act as a tracker for when the mythicbeasts API stabilises and I'll point them at it so that if they change anything we can catch it quickly and make an update release.  I had a really nice time of contributing to lego, kudos to you and your clear and easy to work with codebase.

**Pull request merged**
