### PR TITLE
doc: update Designate documentation

### PR DESCRIPTION
**Pull request by namsral**
Added public Designate provider Fuga Cloud.

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

You have edited a generated file.

I'm not sure how to see your change, please give me more explaination

**Comment by namsral** [comment]
Sorry, meant to make changes to `providers/dns/designate/designate.toml` instead.

**Comment by ldez** [comment]
Maybe I was not clear: your PR feels like an advertisement for Fuga Cloud.
lego is not a place to reference cloud provider features.

Maybe I'm wrong, then please give me more information about your goal and your expectation with this PR.

**Comment by namsral** [comment]
I find it convenient that lego has a list of supported DNS providers. But because not all cloud providers have a custom DNS API I though it convenient for DNS providers with more standardised DNS API to also be listed as custom APIs are now very dominant.

If it makes any difference I can refactor the PR to include other "standardised" DNS providers like Netnod.se which supports RFC2136.

**Review by ldez — APPROVED** [review]

**Pull request merged**
