### PR TITLE
lib: improve wait.For returns.

### LINKED ISSUE #1401: wait.For() can return ambigous errors
- [x] Yes, I'm using a binary release within 2 latest releases.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

`wait.For` returns nil error if deadline exceeded

### What did you see instead?

If certificate got deadline `For()` returns nil error wrapped by fmt: 

```
obtaining certificate: error: one or more domains had a problem:
[example.com] time limit exceeded: last error: %!w(<nil>)
```

So, this is not good: it's way more better if we can replace timeout to context and return DeadlineExceeded or bare error which returns from callback

### Steps to reproduce

1. idk, just put into `wait.For()` some callback, which never returns any error

### Details

<details><summary>Version of lego</summary>

discovered on `v4.2.0` reproduces as well on `v4.3.1`
</details>

<details><summary>Logs</summary>
no any logs, idk
</details>

### PR DESCRIPTION
**Pull request by ldez**
Fixes #1401

### CODE REVIEW

**Comment by quenbyako** [comment]
@ldez i though about something different which is using context with timeout)

something like
```go 
func For(ctx context.Context, repeatInterval time.Duration, f func() (bool, error)) error {
...
}
```
also, i don't think that it's a good idea to return last error: if `f` returns error, it must be throwed explicitly, cause you can lost more important errors in the middle of updating process.

**Comment by ldez** [comment]
For now, I don't want to change the signature of the function.

> also, i don't think that it's a good idea to return last error: if f returns error, it must be throwed explicitly, cause you can lost more important errors in the middle of updating process.

this is the goal of this function to **not** throw an error immediately and to only return the last error.

**Review by dmke — APPROVED** [review]

**Comment by quenbyako** [comment]
> @ldez return the last error

Ehhh, okay, it just looks pretty weird for me, but okay, you're a member and i'll not argue for my subjective opinion, so alright)

Also, thanks a lot for so fast fix and update! I really appreciate that 🤗

**Comment by dmke** [comment]
> it just looks pretty weird for me

Naming is hard. A better name for `For()` would have been `RetryUntil()`.

**Pull request merged**
