### PR TITLE
Add DNS provider for Liara

### PR DESCRIPTION
**Pull request by guoard**
Add new DNS provider for [Liara](https://liara.ir)

```bash
rm -rf .lego/

LIARA_API_KEY="XXXXXXXXXXXXXX" \
  ./lego \
   --accept-tos \
   --email afsharzadeh8@gmail.com \
   --dns liara \
   --domains "*.runtimecode.ir" \
   --domains "runtimecode.ir" \
   run

```

```
BIN_OUTPUT: dist/lego
rm -rf dist/ builds/ cover.out
Version: cc1a9987cf102cd5d09799991ef61b2406d6d915
go build -trimpath -ldflags '-X "main.version=cc1a9987cf102cd5d09799991ef61b2406d6d915"' -o  dist/lego ./cmd/lego/
2022/10/25 13:33:24 No key found for account afsharzadeh8@gmail.com. Generating a P256 key.
2022/10/25 13:33:24 Saved key to /home/ali/w/lego/.lego/accounts/acme-v02.api.letsencrypt.org/afsharzadeh8@gmail.com/keys/afsharzadeh8@gmail.com.key
2022/10/25 13:33:25 [INFO] acme: Registering account for afsharzadeh8@gmail.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/home/ali/w/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2022/10/25 13:33:26 [INFO] [*.runtimecode.ir, runtimecode.ir] acme: Obtaining bundled SAN certificate
2022/10/25 13:33:28 [INFO] [*.runtimecode.ir] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/168515916807
2022/10/25 13:33:28 [INFO] [runtimecode.ir] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/168515916817
2022/10/25 13:33:28 [INFO] [*.runtimecode.ir] acme: use dns-01 solver
2022/10/25 13:33:28 [INFO] [runtimecode.ir] acme: Could not find solver for: tls-alpn-01
2022/10/25 13:33:28 [INFO] [runtimecode.ir] acme: Could not find solver for: http-01
2022/10/25 13:33:28 [INFO] [runtimecode.ir] acme: use dns-01 solver
2022/10/25 13:33:28 [INFO] [*.runtimecode.ir] acme: Preparing to solve DNS-01
2022/10/25 13:33:30 [DEBUG] POST https://dns-service.iran.liara.ir/api/v1/zones/runtimecode.ir/dns-records
2022/10/25 13:33:30 [INFO] [runtimecode.ir] acme: Preparing to solve DNS-01
2022/10/25 13:33:31 [DEBUG] POST https://dns-service.iran.liara.ir/api/v1/zones/runtimecode.ir/dns-records
2022/10/25 13:33:31 [INFO] [*.runtimecode.ir] acme: Trying to solve DNS-01
2022/10/25 13:33:32 [INFO] [*.runtimecode.ir] acme: Checking DNS record propagation using [8.8.8.8:53 8.8.4.4:53]
2022/10/25 13:33:34 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2022/10/25 13:33:40 [INFO] [*.runtimecode.ir] The server validated our request
2022/10/25 13:33:40 [INFO] [runtimecode.ir] acme: Trying to solve DNS-01
2022/10/25 13:33:40 [INFO] [runtimecode.ir] acme: Checking DNS record propagation using [8.8.8.8:53 8.8.4.4:53]
2022/10/25 13:33:42 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2022/10/25 13:33:43 [INFO] [runtimecode.ir] acme: Waiting for DNS record propagation.
2022/10/25 13:33:46 [INFO] [runtimecode.ir] acme: Waiting for DNS record propagation.
2022/10/25 13:33:49 [INFO] [runtimecode.ir] acme: Waiting for DNS record propagation.
2022/10/25 13:33:52 [INFO] [runtimecode.ir] acme: Waiting for DNS record propagation.
2022/10/25 13:33:54 [INFO] [runtimecode.ir] acme: Waiting for DNS record propagation.
2022/10/25 13:34:06 [INFO] [runtimecode.ir] The server validated our request
2022/10/25 13:34:06 [INFO] [*.runtimecode.ir] acme: Cleaning DNS-01 challenge
2022/10/25 13:34:06 [DEBUG] DELETE https://dns-service.iran.liara.ir/api/v1/zones/runtimecode.ir/dns-records/6357b472a959ac3566dcf329
2022/10/25 13:34:18 [INFO] [runtimecode.ir] acme: Cleaning DNS-01 challenge
2022/10/25 13:34:18 [DEBUG] DELETE https://dns-service.iran.liara.ir/api/v1/zones/runtimecode.ir/dns-records/6357b472a959ac3566dcf329
2022/10/25 13:34:18 [INFO] [*.runtimecode.ir, runtimecode.ir] acme: Validations succeeded; requesting certificates
2022/10/25 13:34:22 [INFO] [*.runtimecode.ir] Server responded with a certificate.
```

### CODE REVIEW

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests (units)
```shell
make test
```
- [ ] add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help, documentation, and readme.
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`

**Comment by guoard** [comment]
Hi, @ldez 
Thanks for your review and time.

> * [ ]  add a description to your PR

Added description to PR.

> * [ ]  be able to maintain this provider

Yes, I'm able to maintain the implementation.

**Comment by ldez** [comment]
> Yes, I'm able to maintain the implementation.

Are you a Liara employee?
Are you a Liara customer?

**Comment by guoard** [comment]
> Are you a Liara employee? Are you a Liara customer?

I'm Liara employee.

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
