### PR TITLE
Add DNS provider for hosttech

### LINKED ISSUE #1437: Support for provider: Hosttech
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### Link to the DNS provider

https://www.hosttech.eu

### Link to the API documentation

https://api.ns1.hosttech.eu/api/documentation/

### Additional Notes

_No response_

### PR DESCRIPTION
**Pull request by ldez**
- [x] have a homogeneous design with the other providers
- [x] pass the linter
- [x] do `go mod tidy`
- [x] add tests (units)
- [x] add tests ("live")
- [x] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [x] generate CLI help, documentation, and readme.
- [x] be able to do: _(and put the output of this command to a comment)_
```bash
rm -rf .lego/

HOSTTECH_API_KEY=xxx ./lego -m your_email@example.com --dns hosttech -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.

@RealFriesi could you test by running the previous command (you have to use a real domain and email)?

Closes #1437

### CODE REVIEW

**Comment by RealFriesi** [comment]
I will test it out today as soon as I get home

**Comment by RealFriesi** [comment]
I used a real mail and domain, I just replaced them in the output

`2021/07/06 07:48:51 No key found for account mail@mail.com. Generating a P256 key.
2021/07/06 07:48:51 Saved key to /root/lego/dist/.lego/accounts/acme-staging-v02.api.letsencrypt.org/mail@mail.com                                                                                            t/keys/mail@mail.com.key
2021/07/06 07:48:51 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
Y
2021/07/06 07:49:00 [INFO] acme: Registering account for mail@mail.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/root/lego/dist/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2021/07/06 07:49:00 [INFO] [*.domain.com, domain.com] acme: Obtaining bundled SAN certificate
2021/07/06 07:49:01 [INFO] [*.domain.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/8316098                                                                                             3
2021/07/06 07:49:01 [INFO] [domain.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/83160984
2021/07/06 07:49:01 [INFO] [*.domain.com] acme: use dns-01 solver
2021/07/06 07:49:01 [INFO] [domain.com] acme: Could not find solver for: tls-alpn-01
2021/07/06 07:49:01 [INFO] [domain.com] acme: Could not find solver for: http-01
2021/07/06 07:49:01 [INFO] [domain.com] acme: use dns-01 solver
2021/07/06 07:49:01 [INFO] [*.domain.com] acme: Preparing to solve DNS-01
2021/07/06 07:49:01 [INFO] [domain.com] acme: Preparing to solve DNS-01
2021/07/06 07:49:01 [INFO] [*.domain.com] acme: Cleaning DNS-01 challenge
2021/07/06 07:49:01 [WARN] [*.domain.com] acme: cleaning up failed: hosttech: unknown record ID for '_acme-challenge.                                                                                             domain.com.' 'q_FlHvBjSXaPV-ZcXlMXHDwQyLElbNCJJ5CSmK4QL_k'
2021/07/06 07:49:01 [INFO] [domain.com] acme: Cleaning DNS-01 challenge
2021/07/06 07:49:01 [WARN] [domain.com] acme: cleaning up failed: hosttech: unknown record ID for '_acme-challenge.sr                                                                                             vb.at.' 'kDAORslopwJiNKd7osXcBEWLUGlwU8R11Ef8RtA6syU'
2021/07/06 07:49:02 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/83160983
2021/07/06 07:49:02 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/83160984
2021/07/06 07:49:02 Could not obtain certificates:
        error: one or more domains had a problem:
[*.domain.com] [*.domain.com] acme: error presenting token: hosttech: 422: The given data was invalid.
[domain.com] [domain.com] acme: error presenting token: hosttech: 422: The given data was invalid.`

**Comment by ldez** [comment]
I added extra logs, could you try again?

**Comment by RealFriesi** [comment]
The error response from the api is german
`raw response: {"message":"The given data was invalid.","errors":{"type":["Darf nicht leer sein."]}}`
-> "type": ["cannot be empty."]

```2021/07/06 09:01:52 No key found for account friesi@domain.com. Generating a P256 key.
2021/07/06 09:01:52 Saved key to /root/lego/dist/.lego/accounts/acme-staging-v02.api.letsencrypt.org/friesi@domain.com/keys/friesi@domain.com.key
2021/07/06 09:01:53 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
Y
2021/07/06 09:01:55 [INFO] acme: Registering account for friesi@domain.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/root/lego/dist/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2021/07/06 09:01:56 [INFO] [*.domain.com, domain.com] acme: Obtaining bundled SAN certificate
2021/07/06 09:01:56 [INFO] [*.domain.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/83198208
2021/07/06 09:01:56 [INFO] [domain.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/83198209
2021/07/06 09:01:56 [INFO] [*.domain.com] acme: use dns-01 solver
2021/07/06 09:01:56 [INFO] [domain.com] acme: Could not find solver for: tls-alpn-01
2021/07/06 09:01:56 [INFO] [domain.com] acme: Could not find solver for: http-01
2021/07/06 09:01:56 [INFO] [domain.com] acme: use dns-01 solver
2021/07/06 09:01:56 [INFO] [*.domain.com] acme: Preparing to solve DNS-01
2021/07/06 09:01:56 GetZone: https://api.ns1.hosttech.eu/api/user/v1/zones/domain.com: %!s(MISSING)
2021/07/06 09:01:57 AddRecord: https://api.ns1.hosttech.eu/api/user/v1/zones/274860/records: {"type":"TXT","name":"_acme-challenge","text":"EhYTB47dbWszxOQBxbGWbsCp34x5CIZODSsyOKKG17Q","ttl":3600}
2021/07/06 09:01:57 raw response: {"message":"The given data was invalid.","errors":{"type":["Darf nicht leer sein."]}}
2021/07/06 09:01:57 [INFO] [domain.com] acme: Preparing to solve DNS-01
2021/07/06 09:01:57 GetZone: https://api.ns1.hosttech.eu/api/user/v1/zones/domain.com: %!s(MISSING)
2021/07/06 09:01:57 AddRecord: https://api.ns1.hosttech.eu/api/user/v1/zones/274860/records: {"type":"TXT","name":"_acme-challenge","text":"FE19JbgvYMYpUEtzYma87Mhv1Ip0rd999h4bmVJXoeg","ttl":3600}
2021/07/06 09:01:57 raw response: {"message":"The given data was invalid.","errors":{"type":["Darf nicht leer sein."]}}
2021/07/06 09:01:57 [INFO] [*.domain.com] acme: Cleaning DNS-01 challenge
2021/07/06 09:01:57 GetZone: https://api.ns1.hosttech.eu/api/user/v1/zones/domain.com: %!s(MISSING)
2021/07/06 09:01:57 [WARN] [*.domain.com] acme: cleaning up failed: hosttech: unknown record ID for '_acme-challenge.domain.com.' 'BPW0LXO669uODzEImCxVZ3e_dP-rQEUhU0IBMnlm4L4'
2021/07/06 09:01:57 [INFO] [domain.com] acme: Cleaning DNS-01 challenge
2021/07/06 09:01:57 GetZone: https://api.ns1.hosttech.eu/api/user/v1/zones/domain.com: %!s(MISSING)
2021/07/06 09:01:57 [WARN] [domain.com] acme: cleaning up failed: hosttech: unknown record ID for '_acme-challenge.domain.com.' 'dfXCsdQ4YeYmPb74wYn3J8MXW0VXccTkwXWei1gkkhM'
2021/07/06 09:01:57 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/83198208
2021/07/06 09:01:58 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/83198209
2021/07/06 09:01:58 Could not obtain certificates:
        error: one or more domains had a problem:
[*.domain.com] [*.domain.com] acme: error presenting token: hosttech: 422: The given data was invalid.
[domain.com] [domain.com] acme: error presenting token: hosttech: 422: The given data was invalid.```

**Comment by ldez** [comment]
:thinking: 

```json
AddRecord: https://api.ns1.hosttech.eu/api/user/v1/zones/274860/records: {"type":"TXT","name":"_acme-challenge","text":"EhYTB47dbWszxOQBxbGWbsCp34x5CIZODSsyOKKG17Q","ttl":3600}
raw response: {"message":"The given data was invalid.","errors":{"type":["Darf nicht leer sein."]}}
```

"Darf nicht leer sein." = "Must not be empty."

The API documentation doesn't provide any information about the error schema, then it's hard to understand the error.

Is it a problem with the `type` of the record request? Is it another field? Without documentation on the error schema, it's a bit hard to know.

I need to find a way to understand this message :thinking: 

Could you try the following command (you have to replace `SECRET` by your token):

```console
$ curl -X POST "https://api.ns1.hosttech.eu/api/user/v1/zones/274860/records" -H  "accept: application/json" -H  "Authorization: Bearer SECRET" -H  "Content-Type: application/json" -d "{\"type\":\"TXT\",\"name\":\"_test\",\"text\":\"example\",\"ttl\":3600}"
```

**Comment by ldez** [comment]
:thinking: Maybe it's related to the `Content-Type` header, I updated the code, you can try again.

**Comment by RealFriesi** [comment]
> 🤔
> 
> ```json
> AddRecord: https://api.ns1.hosttech.eu/api/user/v1/zones/274860/records: {"type":"TXT","name":"_acme-challenge","text":"EhYTB47dbWszxOQBxbGWbsCp34x5CIZODSsyOKKG17Q","ttl":3600}
> raw response: {"message":"The given data was invalid.","errors":{"type":["Darf nicht leer sein."]}}
> ```
> 
> The API documentation doesn't provide any information about the error schema, then it's hard to understand the error.
> 
> Is it a problem with the `type` of the record request? Is it another field? Is it related to something else? Without documentation on the error schema, it's a bit hard to know.
> 
> I need to find a way to understand this message 🤔
> 
> Could you try the following commands (you have to replace `SECRET` by your token):
> 
> ```shell
> curl -X POST "https://api.ns1.hosttech.eu/api/user/v1/zones/274860/records" -H  "accept: application/json" -H  "Authorization: Bearer SECRET" -H  "Content-Type: application/json" -d "{\"type\":\"TXT\",\"name\":\"_test\",\"text\":\"example\",\"ttl\":3600}"
> ```
> 
> ```shell
> curl -X POST "https://api.ns1.hosttech.eu/api/user/v1/zones/274860/records" -H  "accept: application/json" -H  "Authorization: Bearer SECRET" -H  "Content-Type: application/json" -d "{\"type\":\"TXT\",\"name\":\"_test\",\"text\":\"example\",\"ttl\":3600,\"comment\":\"example\"}"
> ```

the two post requests worked. txt records were actually registered.

**Comment by ldez** [comment]
ok could you try again with the current branch state?

**Comment by RealFriesi** [comment]
```2021/07/09 10:36:24 [INFO] [*.domain.com, domain.com] acme: Obtaining bundled SAN certificate
2021/07/09 10:36:24 [INFO] [*.domain.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/85409690
2021/07/09 10:36:24 [INFO] [domain.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/85409691
2021/07/09 10:36:24 [INFO] [*.domain.com] acme: use dns-01 solver
2021/07/09 10:36:24 [INFO] [domain.com] acme: Could not find solver for: tls-alpn-01
2021/07/09 10:36:24 [INFO] [domain.com] acme: Could not find solver for: http-01
2021/07/09 10:36:24 [INFO] [domain.com] acme: use dns-01 solver
2021/07/09 10:36:24 [INFO] [*.domain.com] acme: Preparing to solve DNS-01
2021/07/09 10:36:24 GetZone: https://api.ns1.hosttech.eu/api/user/v1/zones/domain.com: %!s(MISSING)
2021/07/09 10:36:25 AddRecord: https://api.ns1.hosttech.eu/api/user/v1/zones/274860/records: {"type":"TXT","name":"_acme-challenge","text":"h7PLII7QA3ABBIBXQHf8q4Wff05U4FDIrzVmfWJ-xIM","ttl":3600}
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/go-acme/lego/v4/providers/dns/hosttech.(*DNSProvider).Present(0xc0002a0260, 0xc0002a4e30, 0x7, 0xc0002ec330, 0x2b, 0xc0005fc240, 0x57, 0xc0002a4e28, 0x3)
        github.com/go-acme/lego/v4@/providers/dns/hosttech/hosttech.go:129 +0x3e3
github.com/go-acme/lego/v4/challenge/dns01.(*Challenge).PreSolve(0xc0005ec1c0, 0xc0002a4e37, 0x7, 0x0, 0xed8835807, 0x0, 0xc0002a4e28, 0x3, 0xc0002a4e30, 0x7, ...)
        github.com/go-acme/lego/v4@/challenge/dns01/dns_challenge.go:94 +0x2a1
github.com/go-acme/lego/v4/challenge/resolver.parallelSolve(0xc0002aa810, 0x2, 0x2, 0xc0005ce5a0)
        github.com/go-acme/lego/v4@/challenge/resolver/prober.go:135 +0x101
github.com/go-acme/lego/v4/challenge/resolver.(*Prober).Solve(0xc00063c030, 0xc0000b0000, 0x2, 0x2, 0x14, 0xc0005e4000)
        github.com/go-acme/lego/v4@/challenge/resolver/prober.go:84 +0x35c
github.com/go-acme/lego/v4/certificate.(*Certifier).Obtain(0xc00053a2d0, 0xc000420080, 0x2, 0x2, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/go-acme/lego/v4@/certificate/certificates.go:124 +0x2da
github.com/go-acme/lego/v4/cmd.obtainCertificate(0xc0000e3340, 0xc0002a0220, 0xc0003f7f50, 0xc0002a0220, 0x8)
        github.com/go-acme/lego/v4@/cmd/cmd_run.go:171 +0x319
github.com/go-acme/lego/v4/cmd.run(0xc0000e3340, 0x0, 0x2)
        github.com/go-acme/lego/v4@/cmd/cmd_run.go:88 +0xe6
github.com/urfave/cli.HandleAction(0x161bcc0, 0x1a50420, 0xc0000e3340, 0xc0000e3340, 0x0)
        github.com/urfave/cli@v1.22.4/app.go:526 +0xbe
github.com/urfave/cli.Command.Run(0x19bd9f7, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1a10a8e, 0x3a, 0x0, ...)
        github.com/urfave/cli@v1.22.4/command.go:174 +0x528
github.com/urfave/cli.(*App).Run(0xc00015efc0, 0xc00003a0c0, 0xc, 0xc, 0x0, 0x0)
        github.com/urfave/cli@v1.22.4/app.go:279 +0x731
main.main()
        github.com/go-acme/lego/v4@/cmd/lego/main.go:42 +0x190
```
TXT Record _acme-challenge.domain.at has been added :D

**Comment by ldez** [comment]
Fixed, you can try again.

**Comment by RealFriesi** [comment]
```
2021/07/09 10:44:43 [INFO] [*.domain.com, domain.com] acme: Obtaining bundled SAN certificate
2021/07/09 10:44:44 [INFO] [*.domain.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/85412592
2021/07/09 10:44:44 [INFO] [domain.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/85413243
2021/07/09 10:44:44 [INFO] [domain.com] acme: authorization already valid; skipping challenge
2021/07/09 10:44:44 [INFO] [*.domain.com] acme: use dns-01 solver
2021/07/09 10:44:44 [INFO] [*.domain.com] acme: Preparing to solve DNS-01
2021/07/09 10:44:44 GetZone: https://api.ns1.hosttech.eu/api/user/v1/zones/domain.com: %!s(MISSING)
2021/07/09 10:44:44 AddRecord: https://api.ns1.hosttech.eu/api/user/v1/zones/274860/records: {"type":"TXT","name":"_acme-challenge","text":"RUzsPTEJVZttGemxOrJRJiJ9jILLCjfekCwxOpS-8Xo","ttl":3600}
2021/07/09 10:44:44 [INFO] [*.domain.com] acme: Trying to solve DNS-01
2021/07/09 10:44:44 [INFO] [*.domain.com] acme: Checking DNS record propagation using [127.0.0.53:53]
2021/07/09 10:44:46 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2021/07/09 10:44:46 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 10:44:48 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 10:44:50 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 10:44:52 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 10:44:54 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 10:44:56 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 10:44:58 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 10:45:00 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 10:45:03 [INFO] [*.domain.com] acme: Cleaning DNS-01 challenge
2021/07/09 10:45:03 GetZone: https://api.ns1.hosttech.eu/api/user/v1/zones/domain.com: %!s(MISSING)
2021/07/09 10:45:03 DeleteRecord: https://api.ns1.hosttech.eu/api/user/v1/zones/274860/records/2111625
2021/07/09 10:45:03 [INFO] Skipping deactivating of valid auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/85412592
2021/07/09 10:45:03 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/85413243
2021/07/09 10:45:03 [INFO] Unable to deactivate the authorization: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/85413243
2021/07/09 10:45:03 Could not obtain certificates:
        error: one or more domains had a problem:
[*.domain.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Incorrect TXT record "U_8Vh2u3QkjxD9XkNwmvi8TqC61UokhaSgx5hHaZoJQ" found at _acme-challenge.domain.com

```

**Comment by ldez** [comment]
could you clean your TXT records and execute the following commands times:
```bash
curl -X POST "https://api.ns1.hosttech.eu/api/user/v1/zones/274860/records" -H  "accept: application/json" -H  "Authorization: Bearer SECRET" -H  "Content-Type: application/json" -d "{\"type\":\"TXT\",\"name\":\"_test\",\"text\":\"example1\",\"ttl\":3600}"
```
```bash
curl -X POST "https://api.ns1.hosttech.eu/api/user/v1/zones/274860/records" -H  "accept: application/json" -H  "Authorization: Bearer SECRET" -H  "Content-Type: application/json" -d "{\"type\":\"TXT\",\"name\":\"_test\",\"text\":\"example2\",\"ttl\":3600}"
```

After that can you check your TXT records to see if you 2 entries : one with `example1` as value and one with `example2` as value, the name must be the same.

**Comment by ldez** [comment]
You can execute the following command to get all the TXT records of the zone:
```bash
curl -X GET "https://api.ns1.hosttech.eu/api/user/v1/zones/274860/records?type=TXT" -H  "accept: application/json" -H  "Authorization: Bearer SECRET"
```

**Comment by RealFriesi** [comment]
Both were added correctly

```json
{
  "data": [
    {
      "id": 2111628,
      "type": "TXT",
      "name": "_test",
      "text": "example1",
      "ttl": 3600,
      "comment": null
    },
    {
      "id": 2111629,
      "type": "TXT",
      "name": "_test",
      "text": "example2",
      "ttl": 3600,
      "comment": null
    }
  ]
}
```

**Comment by ldez** [comment]
can you clean your local store (`rm -rf .lego/`) and try again the PR?

**Comment by RealFriesi** [comment]
worked! awesome 👍 
```
2021/07/09 11:02:12 No key found for account friesi@domain.com. Generating a P256 key.
2021/07/09 11:02:12 Saved key to /root/lego/dist/.lego/accounts/acme-staging-v02.api.letsencrypt.org/friesi@domain.com/keys/friesi@domain.com.key
2021/07/09 11:02:13 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
Y
2021/07/09 11:02:16 [INFO] acme: Registering account for friesi@domain.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/root/lego/dist/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2021/07/09 11:02:16 [INFO] [*.domain.com, domain.com] acme: Obtaining bundled SAN certificate
2021/07/09 11:02:17 [INFO] [*.domain.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/85422045
2021/07/09 11:02:17 [INFO] [domain.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/85422047
2021/07/09 11:02:17 [INFO] [*.domain.com] acme: use dns-01 solver
2021/07/09 11:02:17 [INFO] [domain.com] acme: Could not find solver for: tls-alpn-01
2021/07/09 11:02:17 [INFO] [domain.com] acme: Could not find solver for: http-01
2021/07/09 11:02:17 [INFO] [domain.com] acme: use dns-01 solver
2021/07/09 11:02:17 [INFO] [*.domain.com] acme: Preparing to solve DNS-01
2021/07/09 11:02:17 GetZone: https://api.ns1.hosttech.eu/api/user/v1/zones/domain.com: %!s(MISSING)
2021/07/09 11:02:17 AddRecord: https://api.ns1.hosttech.eu/api/user/v1/zones/274860/records: {"type":"TXT","name":"_acme-challenge","text":"-o6D8Cu2P7dMEUrwOUGerZKI01bD4yqMTCLbgboSAfU","ttl":3600}
2021/07/09 11:02:18 [INFO] [domain.com] acme: Preparing to solve DNS-01
2021/07/09 11:02:18 GetZone: https://api.ns1.hosttech.eu/api/user/v1/zones/domain.com: %!s(MISSING)
2021/07/09 11:02:18 AddRecord: https://api.ns1.hosttech.eu/api/user/v1/zones/274860/records: {"type":"TXT","name":"_acme-challenge","text":"XNxThWanT4sxWSFF9Kq9F7eLNhD26g_ppMNiIA-izhw","ttl":3600}
2021/07/09 11:02:18 [INFO] [*.domain.com] acme: Trying to solve DNS-01
2021/07/09 11:02:18 [INFO] [*.domain.com] acme: Checking DNS record propagation using [127.0.0.53:53]
2021/07/09 11:02:20 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2021/07/09 11:02:20 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:02:22 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:02:24 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:02:26 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:02:28 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:02:30 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:02:32 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:02:34 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:02:36 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:02:38 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:02:40 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:02:42 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:02:44 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:02:46 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:02:48 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:02:50 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:02:52 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:02:54 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:02:56 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:02:58 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:03:00 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2021/07/09 11:03:10 [INFO] [*.domain.com] The server validated our request
2021/07/09 11:03:10 [INFO] [domain.com] acme: Trying to solve DNS-01
2021/07/09 11:03:10 [INFO] [domain.com] acme: Checking DNS record propagation using [127.0.0.53:53]
2021/07/09 11:03:12 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2021/07/09 11:03:19 [INFO] [domain.com] The server validated our request
2021/07/09 11:03:19 [INFO] [*.domain.com] acme: Cleaning DNS-01 challenge
2021/07/09 11:03:19 GetZone: https://api.ns1.hosttech.eu/api/user/v1/zones/domain.com: %!s(MISSING)
2021/07/09 11:03:19 DeleteRecord: https://api.ns1.hosttech.eu/api/user/v1/zones/274860/records/2111630
2021/07/09 11:03:19 [INFO] [domain.com] acme: Cleaning DNS-01 challenge
2021/07/09 11:03:19 GetZone: https://api.ns1.hosttech.eu/api/user/v1/zones/domain.com: %!s(MISSING)
2021/07/09 11:03:19 DeleteRecord: https://api.ns1.hosttech.eu/api/user/v1/zones/274860/records/2111631
2021/07/09 11:03:20 [INFO] [*.domain.com, domain.com] acme: Validations succeeded; requesting certificates
2021/07/09 11:03:21 [INFO] [*.domain.com] Server responded with a certificate.

```

**Review by dmke — APPROVED** [review]

**Pull request merged**
