### PR TITLE
Adding Hezner DNS provider

### PR DESCRIPTION
**Pull request by via-justa**
Adding Hezner DNS provider

### CODE REVIEW

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests (units)
```shell
make test
```
- [ ] add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help and documentation
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`

**Comment by ldez** [comment]
@via-justa any news?

**Comment by via-justa** [comment]
@ldez I'm currently working on other project with priority. I'll be able to get back to it in few days.

**Comment by via-justa** [comment]
```
# ./lego -m via-justa@outlook.com -d *.via-justa.com -d via-justa.com --dns "hetzner" -s https://acme-staging-v02.api.letsencrypt.org/directory run
2020/05/08 11:58:02 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
y
2020/05/08 11:58:04 [INFO] acme: Registering account for via-justa@outlook.com
!!!! HEADS UP !!!!

                Your account credentials have been saved in your Let's Encrypt
                configuration directory at "/root/.lego/accounts".
                You should make a secure backup of this folder now. This
                configuration directory will also contain certificates and
                private keys obtained from Let's Encrypt so making regular
                backups of this folder is ideal.2020/05/08 11:58:05 [INFO] [*.via-justa.com, via-justa.com] acme: Obtaining bundled SAN certificate
2020/05/08 11:58:05 [INFO] [*.via-justa.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/55091863
2020/05/08 11:58:05 [INFO] [via-justa.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/55091864
2020/05/08 11:58:05 [INFO] [*.via-justa.com] acme: use dns-01 solver
2020/05/08 11:58:05 [INFO] [via-justa.com] acme: Could not find solver for: tls-alpn-01
2020/05/08 11:58:05 [INFO] [via-justa.com] acme: Could not find solver for: http-01
2020/05/08 11:58:05 [INFO] [via-justa.com] acme: use dns-01 solver
2020/05/08 11:58:05 [INFO] [*.via-justa.com] acme: Preparing to solve DNS-01
2020/05/08 11:58:06 [INFO] [via-justa.com] acme: Preparing to solve DNS-01
2020/05/08 11:58:07 [INFO] [*.via-justa.com] acme: Trying to solve DNS-01
2020/05/08 11:58:07 [INFO] [*.via-justa.com] acme: Checking DNS record propagation using [1.1.1.1:53 1.0.0.1:53 213.133.100.100:53]
2020/05/08 11:58:07 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
2020/05/08 11:58:07 [INFO] [*.via-justa.com] acme: Waiting for DNS record propagation.
2020/05/08 11:58:09 [INFO] [*.via-justa.com] acme: Waiting for DNS record propagation.
2020/05/08 11:58:11 [INFO] [*.via-justa.com] acme: Waiting for DNS record propagation.
2020/05/08 11:58:13 [INFO] [*.via-justa.com] acme: Waiting for DNS record propagation.
2020/05/08 11:58:15 [INFO] [*.via-justa.com] acme: Waiting for DNS record propagation.
2020/05/08 11:58:17 [INFO] [*.via-justa.com] acme: Waiting for DNS record propagation.
2020/05/08 11:58:20 [INFO] [*.via-justa.com] acme: Waiting for DNS record propagation.
2020/05/08 11:58:22 [INFO] [*.via-justa.com] acme: Waiting for DNS record propagation.
2020/05/08 11:58:24 [INFO] [*.via-justa.com] acme: Waiting for DNS record propagation.
2020/05/08 11:58:26 [INFO] [*.via-justa.com] acme: Waiting for DNS record propagation.
2020/05/08 11:58:28 [INFO] [*.via-justa.com] acme: Waiting for DNS record propagation.
2020/05/08 11:58:30 [INFO] [*.via-justa.com] acme: Waiting for DNS record propagation.
2020/05/08 11:58:38 [INFO] [*.via-justa.com] The server validated our request
2020/05/08 11:58:38 [INFO] [via-justa.com] acme: Trying to solve DNS-01
2020/05/08 11:58:38 [INFO] [via-justa.com] acme: Checking DNS record propagation using [1.1.1.1:53 1.0.0.1:53 213.133.100.100:53]
2020/05/08 11:58:38 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
2020/05/08 11:58:42 [INFO] [via-justa.com] The server validated our request
2020/05/08 11:58:42 [INFO] [*.via-justa.com] acme: Cleaning DNS-01 challenge
2020/05/08 11:58:43 [INFO] [via-justa.com] acme: Cleaning DNS-01 challenge
2020/05/08 11:58:44 [WARN] [via-justa.com] acme: cleaning up failed: could not find record: zone ID: 9neavV25DNRvcsvNFBZxpN; Record: _acme-challenge
2020/05/08 11:58:44 [INFO] [*.via-justa.com, via-justa.com] acme: Validations succeeded; requesting certificates
2020/05/08 11:58:45 [INFO] [*.via-justa.com] Server responded with a certificate.
```

@ldez Ready for review

**Pull request merged**
