### PR TITLE
Add support for Joker.com DMAPI

### PR DESCRIPTION
**Pull request by kad**
Implementation for DNS API https://joker.com/faq/category/39/22-dmapi.html

### CODE REVIEW

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests ("live" and units)
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add the provider to the [readme.md](https://github.com/go-acme/lego#dns-providers)
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help and documentation
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf ./lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```

**Comment by kad** [comment]
I'll be able to maintain that DNS provider, as it is used for my domains.

Design is similar to other providers (e.g. namecheap, exec and httpreq were used as examples)

Code successfully supports wildcard domains

```shell
$ dist/lego -a -m kad@kad.name --dns joker -d '*.afield.eu' -d afield.eu -s https://acme-staging-v02.api.letsencrypt.org/directory run
2019/04/28 00:34:47 No key found for account kad@kad.name. Generating a P384 key.
2019/04/28 00:34:47 Saved key to /Users/kad/go/src/github.com/go-acme/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/kad@kad.name/keys/kad@kad.name.key
2019/04/28 00:34:47 [INFO] acme: Registering account for kad@kad.name
!!!! HEADS UP !!!!

		Your account credentials have been saved in your Let's Encrypt
		configuration directory at "/Users/kad/go/src/github.com/go-acme/lego/.lego/accounts".
		You should make a secure backup	of this folder now. This
		configuration directory will also contain certificates and
		private keys obtained from Let's Encrypt so making regular
		backups of this folder is ideal.2019/04/28 00:34:48 [INFO] [*.afield.eu, afield.eu] acme: Obtaining bundled SAN certificate
2019/04/28 00:34:49 [INFO] [*.afield.eu] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/cZTGJepUs_f_qa5f0XYLkD1XGeKJX6rvI7iJ56wzIc0
2019/04/28 00:34:49 [INFO] [afield.eu] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/KO7yMc4ZcLWfKKOrc_EsA9Et5-eLjdYY9DeS_PLdHFg
2019/04/28 00:34:49 [INFO] [*.afield.eu] acme: use dns-01 solver
2019/04/28 00:34:49 [INFO] [afield.eu] acme: Could not find solver for: tls-alpn-01
2019/04/28 00:34:49 [INFO] [afield.eu] acme: Could not find solver for: http-01
2019/04/28 00:34:49 [INFO] [afield.eu] acme: use dns-01 solver
2019/04/28 00:34:49 [INFO] [*.afield.eu] acme: Preparing to solve DNS-01
2019/04/28 00:34:54 [INFO] [afield.eu] acme: Preparing to solve DNS-01
2019/04/28 00:34:58 [INFO] [*.afield.eu] acme: Trying to solve DNS-01
2019/04/28 00:34:58 [INFO] [*.afield.eu] acme: Checking DNS record propagation using [10.0.0.1:53]
2019/04/28 00:34:58 [INFO] Wait for propagation [timeout: 1h0m0s, interval: 15s]
2019/04/28 00:34:58 [INFO] [*.afield.eu] acme: Waiting for DNS record propagation.
2019/04/28 00:35:20 [INFO] [*.afield.eu] The server validated our request
2019/04/28 00:35:20 [INFO] [afield.eu] acme: Trying to solve DNS-01
2019/04/28 00:35:20 [INFO] [afield.eu] acme: Checking DNS record propagation using [10.0.0.1:53]
2019/04/28 00:35:20 [INFO] Wait for propagation [timeout: 1h0m0s, interval: 15s]
2019/04/28 00:35:21 [INFO] [afield.eu] The server validated our request
2019/04/28 00:35:21 [INFO] [*.afield.eu] acme: Cleaning DNS-01 challenge
2019/04/28 00:35:26 [INFO] [afield.eu] acme: Cleaning DNS-01 challenge
2019/04/28 00:35:27 [INFO] [*.afield.eu, afield.eu] acme: Validations succeeded; requesting certificates
2019/04/28 00:35:28 [INFO] [*.afield.eu] Server responded with a certificate.
$
```

I'll add unit / live tests.

**Comment by ldez** [comment]
I saw that you were inspired by the Namecheap provider, you are so inspired of Namecheap that Namecheap is written in all the comments :smile:

**Comment by kad** [comment]
Ouch. I forgot to clean-up comments :)
Updated, now with tests.

**Comment by ldez** [comment]
Could you add tests on `parseJokerResponse`?

Could you also address review comments in terms of additional commits (and don't amend/squash existing ones).

**Pull request merged**
