### PR TITLE
dnspod: upgrade API

### PR DESCRIPTION
**Pull request by libla**
dnspod is upgrade by tencentcloud api now.

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

you have to:

- [ ] add a description to your PR
- [ ] have a homogeneous design with the other providers
- [ ] update the tests (units)
- [ ] update the tests ("live")
- [ ] update the [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/dnspod/dnspod.toml)
- [ ] generate CLI help, documentation, and readme.
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`



**This PR contains breaking change, then your PR is not mergeable in its current state**

**Comment by ldez** [comment]
Please don't open several PRs, thank you.

**Comment by libla** [comment]
> Please don't open several PRs, thank you.

The last request missed the test, so I closed it and reopen it.

**Comment by ldez** [comment]
You don't need to create a new PR just to add tests.

**Comment by ldez** [comment]
Could you explain why do you think that that tencent implementation is better?
Do you understand that your PR is breaking?

**Comment by libla** [comment]
I know my PR is breaking.
But the old api is not support. The error message is 'API call failed: could not get domains: The login token ID is invalid'.
In addition, DNSPod has been acquired by Tencent. In the future, the interface will be integrated into tencentcloud, just like alidns.

**Comment by ldez** [comment]
I think that the `dnspod` package in the tencent repository is not related to [DNSPod](https://www.dnspod.cn/)

The API is not the same as in the DNSPod documentation https://docs.dnspod.com/api/

**Comment by libla** [comment]
Maybe the English version of the document is out of date, you can refer to this
https://docs.dnspod.cn/api/5f55993d8ae73e11c5b01ce6/

**Comment by libla** [comment]
Chinese version has the following part:
> 注意：本页面提供 API 文档为 DNSPod 传统 API ，仅支持 DNSPod Token。仅限主账号调用，子账号不可用。 若您非使用 D 监控功能，推荐使用 腾讯云 API 3.0 ，支持 CAM 权限管理，同时支持主账号、子账号调用。兼容腾讯云 API 密钥，提供 API Explorer、API 调用统计等工具，还可以与腾讯云其他产品更好协同使用。

**Comment by ldez** [comment]
> 注意：本页面提供 API 文档为 DNSPod 传统 API ，仅支持 DNSPod Token

So the current implementation still works.

I think you are trying to do the same thing as #1527

**Comment by libla** [comment]
Yes, #1527 does almost the same work as I do.
Close my PR and add a provider like it is a better way.

**Pull request closed without merging**
