### PR TITLE
gcloud: add CLI example

### PR DESCRIPTION
**Pull request by KuberDriver**
[Document](https://go-acme.github.io/lego/dns/gcloud/) has note to add CLI example for provider: `glcoud` 

Adding example with this PR.

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

this file is generated:
https://github.com/go-acme/lego/blob/0122506c23fc2955a58263152cf75075e391cb7f/docs/content/dns/zz_gen_gcloud.md?plain=1#L12-L14

**Comment by KuberDriver** [comment]
> Hello,
> 
> this file is generated:
> 
> https://github.com/go-acme/lego/blob/0122506c23fc2955a58263152cf75075e391cb7f/docs/content/dns/zz_gen_gcloud.md?plain=1#L12-L14

Hi @ldez - apologies, trying to understand if there is any issue with the example provided? or is document with example is already present?

**Comment by ldez** [comment]
You have to change this file: https://github.com/go-acme/lego/blob/master/providers/dns/gcloud/gcloud.toml

**Comment by KuberDriver** [comment]
Thank you @ldez, reverted change on auto-generated file and updated the .toml file in gcloud.

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
