### PR TITLE
route53: add assume role ARN

### LINKED ISSUE #1647: Support for `Role ARN` in Route53 Provider
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Other

## How am I using Lego?
I am currently using [acme provider](https://github.com/vancluever/terraform-provider-acme) for terraform. Which currently uses lego. 

## Feature Request. 
I would like to have support for assuming a role along with `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`, As I am using cross-account roles.

### PR DESCRIPTION
**Pull request by ncs-nozomi-nishinohara**
I also needed AssumeRole, so I supported #1647.

See the command result in the comment.

Fixes #1647

### CODE REVIEW

**Comment by ncs-nozomi-nishinohara** [comment]
This is the result of the command using AssumeRole.
I'm converting the actual domain to `example.com`.

```
root@bb087df7e2ad:/src/dist# export AWS_ACCESS_KEY_ID="xxxxxxx"
root@bb087df7e2ad:/src/dist# export AWS_SECRET_ACCESS_KEY="xxxxxxx"
root@bb087df7e2ad:/src/dist# export AWS_REGION="xxxxxxx"
root@bb087df7e2ad:/src/dist# export AWS_HOSTED_ZONE_ID="xxxxxxx"
root@bb087df7e2ad:/src/dist# export AWS_ASSUME_ROLE_ARN="arn:aws:iam::xxxxxxx:role/xxxxxxx"
root@bb087df7e2ad:/src/dist# rm -rf .lego 
root@bb087df7e2ad:/src/dist# ./lego -m nozomi_nishinohara@n-creativesystem.com --dns route53 -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
2022/05/26 15:53:18 No key found for account nozomi_nishinohara@n-creativesystem.com. Generating a P256 key.
2022/05/26 15:53:18 Saved key to /src/dist/.lego/accounts/acme-staging-v02.api.letsencrypt.org/nozomi_nishinohara@n-creativesystem.com/keys/nozomi_nishinohara@n-creativesystem.com.key
2022/05/26 15:53:18 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
Y
2022/05/26 15:53:20 [INFO] acme: Registering account for nozomi_nishinohara@n-creativesystem.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/src/dist/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2022/05/26 15:53:20 [INFO] [*.example.com, example.com] acme: Obtaining bundled SAN certificate
2022/05/26 15:53:21 [INFO] [*.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/2544711364
2022/05/26 15:53:21 [INFO] [example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/2544711374
2022/05/26 15:53:21 [INFO] [*.example.com] acme: use dns-01 solver
2022/05/26 15:53:21 [INFO] [example.com] acme: Could not find solver for: tls-alpn-01
2022/05/26 15:53:21 [INFO] [example.com] acme: Could not find solver for: http-01
2022/05/26 15:53:21 [INFO] [example.com] acme: use dns-01 solver
2022/05/26 15:53:21 [INFO] [*.example.com] acme: Preparing to solve DNS-01
2022/05/26 15:53:23 [INFO] Wait for route53 [timeout: 2m0s, interval: 4s]
2022/05/26 15:53:55 [INFO] [example.com] acme: Preparing to solve DNS-01
2022/05/26 15:53:56 [INFO] Wait for route53 [timeout: 2m0s, interval: 4s]
2022/05/26 15:54:19 [INFO] [*.example.com] acme: Trying to solve DNS-01
2022/05/26 15:54:19 [INFO] [*.example.com] acme: Checking DNS record propagation using [127.0.0.11:53]
2022/05/26 15:54:23 [INFO] Wait for propagation [timeout: 2m0s, interval: 4s]
2022/05/26 15:54:38 [INFO] [*.example.com] The server validated our request
2022/05/26 15:54:38 [INFO] [example.com] acme: Trying to solve DNS-01
2022/05/26 15:54:38 [INFO] [example.com] acme: Checking DNS record propagation using [127.0.0.11:53]
2022/05/26 15:54:42 [INFO] Wait for propagation [timeout: 2m0s, interval: 4s]
2022/05/26 15:54:58 [INFO] [example.com] The server validated our request
2022/05/26 15:54:58 [INFO] [*.example.com] acme: Cleaning DNS-01 challenge
2022/05/26 15:55:00 [INFO] Wait for route53 [timeout: 2m0s, interval: 4s]
2022/05/26 15:55:35 [INFO] [example.com] acme: Cleaning DNS-01 challenge
2022/05/26 15:55:36 [INFO] [*.example.com, example.com] acme: Validations succeeded; requesting certificates
2022/05/26 15:55:37 [INFO] [*.example.com] Server responded with a certificate.
```

**Comment by ncs-nozomi-nishinohara** [comment]
I do not know why CI is down.🤔

**Comment by ncs-nozomi-nishinohara** [comment]
I don't know when the CI came through.😲

**Review by ldez — APPROVED** [review]
Thanks :+1:

**Comment by ncs-nozomi-nishinohara** [comment]
Excuse me. 
When will this be released?

**Pull request merged**
