### PR TITLE
Add DNS provider for Hurricane Electric

### LINKED ISSUE #901: Add support for Hurricane Electric as dns provider
It would be nice to have Hurricane Electric (he.net) as a dns provider. They don't have a real API but there are several ways to use their service with some self made HTTP requests.
There's probably a go library already doing it.

I'm looking into adding that feature and creating a pull request, but my time is quite limited at the moment.

### PR DESCRIPTION
**Pull request by ben-zen**
Hurricane Electric's DDNS API supports TXT records now, and as a Hurricane Electric DNS user I'd like to also get certificates using their API.

Fixes #901

### CODE REVIEW

**Comment by ben-zen** [comment]
I see that there's #901 for adding support for HE, and this change uses their API instead of DOM interactions; can I get that issue re-opened to attach to this PR?

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] have a homogeneous design with the other providers
- [ ] add tests (units)
```shell
make test
```
- [ ] add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help, documentation, and readme.
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`

**Comment by ldez** [comment]
You also have to revert all the unrelated changes on the `go mod` file.

**Comment by ldez** [comment]
From https://dns.he.net/

> Dynamic TXT Records
> 
>     Dynamic TXT records have been added!
>     We've received requests for dynamic TXT records for use with Let's Encrypt Certificates. We've added them in using the same basic ddns syntax that we already provide with the difference being the use of 'txt=' in place of 'myip='. You will need to create the dynamic TXT record from within the dns.he.net interface before you will be able to make updates. You will not be able to dynamically create and delete these TXT records as doing so would subsequently remove your ddns key associated with the record. 

The HE API is still not complete: in order for this to really useful, we would need to be able to create new TXT records without the web interface.

So your PR will never work, sorry.

**Comment by ben-zen** [comment]
I'm not sure I understand the comment about this not being really useful because arbitrary record creation/deletion is not available; if anything, I consider that restriction a feature of HE's API surface, because the limitation to only being able to modify records with individual tokens restricts the blast radius of a compromised service, unlike with the more generic API keys for a lot of other services. As a Hurricane Electric user, I'm fully aware of the limitations of their service, and am willing to work within them. With the understood limitation that the _user_ needs to create the `_acme-challenge....` record, this change is quite usable, for both standalone and wildcard certificates.

If I add additional documentation describing the limitations on how to set up for Hurricane Electric--and make some additional modifications including working out how to handle multiple domains with the provider--would that be sufficient, or do you still feel that this change is a non-starter?

**Comment by ldez** [comment]
As HE requires manual operation, I think that the manual provider will work better in this case.

**Comment by ben-zen** [comment]
HE's API only requires manual operation for creating or deleting records; the update mechanism is honestly fairly trivial, and is all this PR relies on. This is even in line with the [EFF's published best practices](https://www.eff.org/deeplinks/2018/02/technical-deep-dive-securing-automation-acme-dns-challenge-validation) for handling DNS-01 challenges, because generic API access is a dangerous tool to leave lying around. There's also no issue with leaving a TXT record up with a content of "." the rest of the time, since it's only an important record during the ACME transaction.

I'm still having a hard time following how this is a completely blocking issue with the PR.

**Comment by indrora** [comment]
As a point of note:

The [documentation on making a new DNS challenge solver](https://go-acme.github.io/lego/usage/library/writing-a-challenge-solver/) makes *no mention of such a requirement*, and the [published interface documentation](https://pkg.go.dev/github.com/go-acme/lego/challenge#Provider), specifically that

> Present presents the solution to a challenge available to be solved.

Nowhere does this say it must create the TXT record, nor does it say that CleanUp must __destroy__ the TXT record, either. 

In fact, it's made pretty clear that the actual authentication mechanism chosen by DNS providers is out of scope and that if a DNS provider wants to make a point of not giving full record control over an HTTP interface, that's for the implementer to figure out and document.

I disagree that `DnsProviderManual` is the right way to go: `DnsProviderManual` implies that there is a human factor in setting of the TXT record, not just the creation of the record.

**Comment by ldez** [comment]
All the other providers follow the same rules (creation/deletion), I'm 100% sure that some HE users will not understand the difference, so I hope you help us to answer these users.

The EFF article seems clear to me so I authorize the addition of this provider.

But:
- the documentation must be really clear and precise
- the propagation timeout and sequence interval must be increased
- the last uncheck element must be done https://github.com/go-acme/lego/pull/1344#issuecomment-774654743

> NOTE: A propagation delay of up to 5 minutes may be experienced as the TTL of the record will need to expire and refresh. You should wait before requesting DNS01 validation once you have updated the record.

PS: You can ask HE to create a more powerful API.

**Comment by ben-zen** [comment]
Here's a request for certificates, anonymized:

$ HURRICANE_TOKENS=test.example.com:TOKEN-1,demo.example.com:TOKEN-2 ./dist/lego -m [...] --dns hurricane -d *.test.example.com -d test.example.com -d demo.example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
	A future release of golang/protobuf will delete this package,
	which has long been excluded from the compatibility promise.

2021/02/09 23:27:05 No key found for account [...]. Generating a P256 key.
2021/02/09 23:27:05 Saved key to /home/ben-zen/source/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/[...]/keys/[...].key
2021/02/09 23:27:05 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
y
2021/02/09 23:27:12 [INFO] acme: Registering account for [...]
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/home/ben-zen/source/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2021/02/09 23:27:13 [INFO] [*.test.example.com, test.example.com, demo.example.com] acme: Obtaining bundled SAN certificate
2021/02/09 23:27:13 [INFO] [*.test.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/206407767
2021/02/09 23:27:13 [INFO] [demo.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/206407768
2021/02/09 23:27:13 [INFO] [test.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/206407769
2021/02/09 23:27:13 [INFO] [*.test.example.com] acme: use dns-01 solver
2021/02/09 23:27:13 [INFO] [demo.example.com] acme: Could not find solver for: tls-alpn-01
2021/02/09 23:27:13 [INFO] [demo.example.com] acme: Could not find solver for: http-01
2021/02/09 23:27:13 [INFO] [demo.example.com] acme: use dns-01 solver
2021/02/09 23:27:13 [INFO] [test.example.com] acme: Could not find solver for: tls-alpn-01
2021/02/09 23:27:13 [INFO] [test.example.com] acme: Could not find solver for: http-01
2021/02/09 23:27:13 [INFO] [test.example.com] acme: use dns-01 solver
2021/02/09 23:27:13 [INFO] [*.test.example.com] acme: Preparing to solve DNS-01
2021/02/09 23:27:13 [INFO] [*.test.example.com] acme: Trying to solve DNS-01
2021/02/09 23:27:13 [INFO] [*.test.example.com] acme: Checking DNS record propagation using [127.0.0.53:53]
2021/02/09 23:27:15 [INFO] Wait for propagation [timeout: 5m0s, interval: 2s]
2021/02/09 23:27:20 [INFO] [*.test.example.com] The server validated our request
2021/02/09 23:27:20 [INFO] [*.test.example.com] acme: Cleaning DNS-01 challenge
2021/02/09 23:27:20 [INFO] sequence: wait for 1m0s
2021/02/09 23:28:20 [INFO] [demo.example.com] acme: Preparing to solve DNS-01
2021/02/09 23:28:20 [INFO] [demo.example.com] acme: Trying to solve DNS-01
2021/02/09 23:28:20 [INFO] [demo.example.com] acme: Checking DNS record propagation using [127.0.0.53:53]
2021/02/09 23:28:22 [INFO] Wait for propagation [timeout: 5m0s, interval: 2s]
2021/02/09 23:28:29 [INFO] [demo.example.com] The server validated our request
2021/02/09 23:28:29 [INFO] [demo.example.com] acme: Cleaning DNS-01 challenge
2021/02/09 23:28:29 [INFO] sequence: wait for 1m0s
2021/02/09 23:29:29 [INFO] [test.example.com] acme: Preparing to solve DNS-01
2021/02/09 23:29:29 [INFO] [test.example.com] acme: Trying to solve DNS-01
2021/02/09 23:29:29 [INFO] [test.example.com] acme: Checking DNS record propagation using [127.0.0.53:53]
2021/02/09 23:29:31 [INFO] Wait for propagation [timeout: 5m0s, interval: 2s]
2021/02/09 23:29:37 [INFO] [test.example.com] The server validated our request
2021/02/09 23:29:37 [INFO] [test.example.com] acme: Cleaning DNS-01 challenge
2021/02/09 23:29:37 [INFO] [*.test.example.com, test.example.com, demo.example.com] acme: Validations succeeded; requesting certificates
2021/02/09 23:29:37 [INFO] [*.test.example.com] Server responded with a certificate.

Per the openssl x509 command, the returned certificate has all the correct domains on it.

**Comment by ldez** [comment]
Why have you changed the token handling?

**Review by ldez — APPROVED** [review]
The API of HE is definitively the worst API of all the DNS provider handled by lego:
- impossible to create/remove a record, those actions must be handled by hand
- one password/token by record
- the passwords/tokens must be generated by hand
- the password/token can only be handled by query parameters
- only one value by record
- don't follow standard HTTP response codes
- the API responses are just plain text
- no real API documentation

If I use an HTML parser, I can automate more things than with the API...

This provider will never work with a dynamic environment where the domains are created and removed automatically.

So I will merge that PR, but I feel dirty and sad.

I hope that HE will create a better API in the future.

**Pull request merged**
