### PR TITLE
Add DNS provider for Infoblox

### LINKED ISSUE #1377: Request to integrate Infoblox DNS provider
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, the DNS provider exposes a public API.
- [x] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation
- [x] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

Request to integrate the Infoblox DNS provider. We (amongst other companies) run this provider on-prem. Infoblox has a pretty good API so I hope this would be possible. 

### Link to the DNS provider

https://www.infoblox.com/products/ddi/

### Link to the API documentation

https://www.infoblox.com/wp-content/uploads/infoblox-deployment-infoblox-rest-api.pdf

### Additional Notes

No additional notes. Feel free to fire away with questions in regards to missing input. I'd be happy to fill in any gaps.

### PR DESCRIPTION
**Pull request by bmayfi3ld**
Pull request to add a provider to work with an on-prem infoblox instance.

Fixes #1377

### CODE REVIEW

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests (units)
```shell
make test
```
- [ ] add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help, documentation, and readme.
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`

**Comment by bmayfi3ld** [comment]
Tests incoming soon.

**Comment by bmayfi3ld** [comment]
tests added, output generated, linter run, and here is run output

```
root@8135369295f2:/workspaces/lego# rm -rf .lego
root@8135369295f2:/workspaces/lego# ./dist/lego -m bmayfield@mycompany.com --dns infoblox -d *.mytestdomain.org -d mytestdomain.org -s https://acme-staging-v02.api.letsencrypt.org/directory run
2021/05/28 19:14:36 No key found for account bmayfield@mycompany.com. Generating a P256 key.
2021/05/28 19:14:36 Saved key to /workspaces/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/bmayfield@mycompany.com/keys/bmayfield@mycompany.com.key
2021/05/28 19:14:36 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
y
2021/05/28 19:14:38 [INFO] acme: Registering account for bmayfield@mycompany.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/workspaces/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2021/05/28 19:14:38 [INFO] [*.mytestdomain.org, mytestdomain.org] acme: Obtaining bundled SAN certificate
2021/05/28 19:14:38 [INFO] [*.mytestdomain.org] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/57800017
2021/05/28 19:14:38 [INFO] [mytestdomain.org] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/57800018
2021/05/28 19:14:38 [INFO] [*.mytestdomain.org] acme: use dns-01 solver
2021/05/28 19:14:38 [INFO] [mytestdomain.org] acme: Could not find solver for: tls-alpn-01
2021/05/28 19:14:38 [INFO] [mytestdomain.org] acme: Could not find solver for: http-01
2021/05/28 19:14:38 [INFO] [mytestdomain.org] acme: use dns-01 solver
2021/05/28 19:14:38 [INFO] [*.mytestdomain.org] acme: Preparing to solve DNS-01
2021/05/28 19:14:39 [INFO] [mytestdomain.org] acme: Preparing to solve DNS-01
2021/05/28 19:14:39 [INFO] [*.mytestdomain.org] acme: Trying to solve DNS-01
2021/05/28 19:14:39 [INFO] [*.mytestdomain.org] acme: Checking DNS record propagation using [192.168.65.5:53]
2021/05/28 19:14:41 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2021/05/28 19:14:48 [INFO] [*.mytestdomain.org] The server validated our request
2021/05/28 19:14:48 [INFO] [mytestdomain.org] acme: Trying to solve DNS-01
2021/05/28 19:14:48 [INFO] [mytestdomain.org] acme: Checking DNS record propagation using [192.168.65.5:53]
2021/05/28 19:14:50 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2021/05/28 19:14:57 [INFO] [mytestdomain.org] The server validated our request
2021/05/28 19:14:57 [INFO] [*.mytestdomain.org] acme: Cleaning DNS-01 challenge
2021/05/28 19:14:58 [INFO] [mytestdomain.org] acme: Cleaning DNS-01 challenge
2021/05/28 19:14:59 [INFO] [*.mytestdomain.org, mytestdomain.org] acme: Validations succeeded; requesting certificates
2021/05/28 19:15:00 [INFO] [*.mytestdomain.org] Server responded with a certificate.
```

**Comment by bmayfi3ld** [comment]
@ldez I believe I have completed most of the tasks. 

I could not figure out how to get the live tests to work and nor could I run "make test" because there were failures in other packages.

**Comment by ldez** [comment]
@bmayfi3ld Could you retry to run the command to generate certificates with my changes?

**Comment by bmayfi3ld** [comment]
looks good to me

```
root@2a721b9d0575:/workspaces/lego# git log
commit 465b24d3ae7b1dc516c12b3ac5d6c9423a16b961 (HEAD -> adding-infoblox-provider, origin/adding-infoblox-provider)
root@2a721b9d0575:/workspaces/lego# rm -rf .lego
root@2a721b9d0575:/workspaces/lego# ./dist/lego -m bmayfield@myorg.com --dns infoblox -d *.mytestdomain.org -d mytestdomain.org -s https://acme-staging-v02.api.letsencrypt.org/directory run
2021/05/28 20:00:59 No key found for account bmayfield@myorg.com. Generating a P256 key.
2021/05/28 20:00:59 Saved key to /workspaces/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/bmayfield@myorg.com/keys/bmayfield@myorg.com.key
2021/05/28 20:00:59 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
Y
2021/05/28 20:01:01 [INFO] acme: Registering account for bmayfield@myorg.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/workspaces/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2021/05/28 20:01:02 [INFO] [*.mytestdomain.org, mytestdomain.org] acme: Obtaining bundled SAN certificate
2021/05/28 20:01:02 [INFO] [*.mytestdomain.org] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/57823551
2021/05/28 20:01:02 [INFO] [mytestdomain.org] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/57823552
2021/05/28 20:01:02 [INFO] [*.mytestdomain.org] acme: use dns-01 solver
2021/05/28 20:01:02 [INFO] [mytestdomain.org] acme: Could not find solver for: tls-alpn-01
2021/05/28 20:01:02 [INFO] [mytestdomain.org] acme: Could not find solver for: http-01
2021/05/28 20:01:02 [INFO] [mytestdomain.org] acme: use dns-01 solver
2021/05/28 20:01:02 [INFO] [*.mytestdomain.org] acme: Preparing to solve DNS-01
2021/05/28 20:01:03 [INFO] [mytestdomain.org] acme: Preparing to solve DNS-01
2021/05/28 20:01:03 [INFO] [*.mytestdomain.org] acme: Trying to solve DNS-01
2021/05/28 20:01:03 [INFO] [*.mytestdomain.org] acme: Checking DNS record propagation using [192.168.65.5:53]
2021/05/28 20:01:05 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2021/05/28 20:01:11 [INFO] [*.mytestdomain.org] The server validated our request
2021/05/28 20:01:11 [INFO] [mytestdomain.org] acme: Trying to solve DNS-01
2021/05/28 20:01:11 [INFO] [mytestdomain.org] acme: Checking DNS record propagation using [192.168.65.5:53]
2021/05/28 20:01:13 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2021/05/28 20:01:21 [INFO] [mytestdomain.org] The server validated our request
2021/05/28 20:01:21 [INFO] [*.mytestdomain.org] acme: Cleaning DNS-01 challenge
2021/05/28 20:01:22 [INFO] [mytestdomain.org] acme: Cleaning DNS-01 challenge
2021/05/28 20:01:22 [INFO] [*.mytestdomain.org, mytestdomain.org] acme: Validations succeeded; requesting certificates
2021/05/28 20:01:24 [INFO] [*.mytestdomain.org] Server responded with a certificate.
```

**Comment by ldez** [comment]
There is something weird :thinking: 

For the 2 domains the `Present`, you create 2 records from the same FQDN `_acme-challenge.mytestdomain.org.`

In the `Cleanup`, you get the TXT record base on the FQDN (for the 2 domains the FQDN must the same), and you delete one record.
But previously you have created 2 records on the same FQDN.
How it is possible to do that without having a least a non-blocking error?

**Comment by bmayfi3ld** [comment]
Binary rebuilt and output is the same. 

```
root@2a721b9d0575:/workspaces/lego# ./dist/lego -m bmayfield@myorg.com --dns infoblox -d *.mytestdomain.org -d mytestdomain.org -s https://acme-staging-v02.api.letsencrypt.org/directory run
2021/05/28 20:24:06 No key found for account bmayfield@myorg.com. Generating a P256 key.
2021/05/28 20:24:06 Saved key to /workspaces/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/bmayfield@myorg.com/keys/bmayfield@myorg.com.key
2021/05/28 20:24:06 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
y
2021/05/28 20:24:12 [INFO] acme: Registering account for bmayfield@myorg.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/workspaces/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2021/05/28 20:24:12 [INFO] [*.mytestdomain.org, mytestdomain.org] acme: Obtaining bundled SAN certificate
2021/05/28 20:24:13 [INFO] [*.mytestdomain.org] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/57835462
2021/05/28 20:24:13 [INFO] [mytestdomain.org] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/57835463
2021/05/28 20:24:13 [INFO] [*.mytestdomain.org] acme: use dns-01 solver
2021/05/28 20:24:13 [INFO] [mytestdomain.org] acme: Could not find solver for: tls-alpn-01
2021/05/28 20:24:13 [INFO] [mytestdomain.org] acme: Could not find solver for: http-01
2021/05/28 20:24:13 [INFO] [mytestdomain.org] acme: use dns-01 solver
2021/05/28 20:24:13 [INFO] [*.mytestdomain.org] acme: Preparing to solve DNS-01
2021/05/28 20:24:13 [INFO] [mytestdomain.org] acme: Preparing to solve DNS-01
2021/05/28 20:24:14 [INFO] [*.mytestdomain.org] acme: Trying to solve DNS-01
2021/05/28 20:24:14 [INFO] [*.mytestdomain.org] acme: Checking DNS record propagation using [192.168.65.5:53]
2021/05/28 20:24:16 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2021/05/28 20:24:22 [INFO] [*.mytestdomain.org] The server validated our request
2021/05/28 20:24:22 [INFO] [mytestdomain.org] acme: Trying to solve DNS-01
2021/05/28 20:24:22 [INFO] [mytestdomain.org] acme: Checking DNS record propagation using [192.168.65.5:53]
2021/05/28 20:24:24 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2021/05/28 20:24:31 [INFO] [mytestdomain.org] The server validated our request
2021/05/28 20:24:31 [INFO] [*.mytestdomain.org] acme: Cleaning DNS-01 challenge
2021/05/28 20:24:32 [INFO] [mytestdomain.org] acme: Cleaning DNS-01 challenge
2021/05/28 20:24:34 [INFO] [*.mytestdomain.org, mytestdomain.org] acme: Validations succeeded; requesting certificates
2021/05/28 20:24:36 [INFO] [*.mytestdomain.org] Server responded with a certificate.
```

I can see both records pop up and get cleaned out in the infoblox gui.

image

**Comment by ldez** [comment]
I will describe how lego handles a challenge for a DNS provider.
1. call the `Present` for `*.mytestdomain.org`, create a TXT record for `_acme-challenge.mytestdomain.org.`
2. call the `Present` for `mytestdomain.org`, create a TXT record for `_acme-challenge.mytestdomain.org.`
3. at this point the 2 records exist
4. do the challenge for the 2 domains
5. call the `Cleanup` for `*.mytestdomain.org`, delete the TXT record for `_acme-challenge.mytestdomain.org.`
6. call the `Cleanup` for `mytestdomain.org`, delete the TXT record for `_acme-challenge.mytestdomain.org.`

But in the `Cleanup`:
```go
record, err := objectManager.GetTXTRecord(dns01.UnFqdn(fqdn))
// ...
_, err = objectManager.DeleteTXTRecord(record.Ref)
```

`GetTXTRecord` returns only **one** record.

How the record ref can be good? Because you have **2** records for this FQDN.
How two calls of `GetTXTRecord` with the exact same parameter can return 2 different records?

Maybe the API is iterating on the TXT records :thinking:

**Comment by bmayfi3ld** [comment]
Oh I see what your saying now. 

Yea that is weird. 

Ah, so it looks like the go infoblox package returns the first record it finds during that call. 

https://github.com/infobloxopen/infoblox-go-client/blob/97e09d6039103ef699d4a3009de1af909cb97801/object_manager.go#L642

**Comment by ldez** [comment]
I will add an additional level of security because the API client has some unexpected behavior.

**Comment by ldez** [comment]
In fact, using `GetTXTRecord` with a ref is a kind of hack, because this method expects the name and not the ref.
The "right" method to get a record by ref is `GetTXTRecordByRef`.

**Comment by bmayfi3ld** [comment]
Yea the original code that I pulled this from had design requirements of being stateless and to be only based on the fqdn, so the delete call had the "search" function built into it.

**Comment by bmayfi3ld** [comment]
Works with latest changes

```
root@2a721b9d0575:/workspaces/lego# make build
BIN_OUTPUT: dist/lego
rm -rf dist/ builds/ cover.out
Version: 3a79d462cc7035e285a60c270f4b3dbf7f7b45b1
go build -v -trimpath -ldflags '-X "main.version=3a79d462cc7035e285a60c270f4b3dbf7f7b45b1"' -o  dist/lego ./cmd/lego/
github.com/go-acme/lego/v4/providers/dns/infoblox
github.com/go-acme/lego/v4/providers/dns
github.com/go-acme/lego/v4/cmd
root@2a721b9d0575:/workspaces/lego# rm -rf .legoroot@2a721b9d0575:/workspaces/lego# ./dist/lego -m bmayfield@myorg.com --dns infoblox -d *.mytestdomain.org -d mytestdomain.org -s https://acme-staging-v02.api.letsencrypt.org/directory run
2021/05/28 20:57:17 No key found for account bmayfield@myorg.com. Generating a P256 key.
2021/05/28 20:57:17 Saved key to /workspaces/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/bmayfield@myorg.com/keys/bmayfield@myorg.com.key
2021/05/28 20:57:18 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
Y
2021/05/28 20:57:20 [INFO] acme: Registering account for bmayfield@myorg.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/workspaces/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2021/05/28 20:57:21 [INFO] [*.mytestdomain.org, mytestdomain.org] acme: Obtaining bundled SAN certificate
2021/05/28 20:57:21 [INFO] [*.mytestdomain.org] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/57849702
2021/05/28 20:57:21 [INFO] [mytestdomain.org] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/57849703
2021/05/28 20:57:21 [INFO] [*.mytestdomain.org] acme: use dns-01 solver
2021/05/28 20:57:21 [INFO] [mytestdomain.org] acme: Could not find solver for: tls-alpn-01
2021/05/28 20:57:21 [INFO] [mytestdomain.org] acme: Could not find solver for: http-01
2021/05/28 20:57:21 [INFO] [mytestdomain.org] acme: use dns-01 solver
2021/05/28 20:57:21 [INFO] [*.mytestdomain.org] acme: Preparing to solve DNS-01
2021/05/28 20:57:22 [INFO] [mytestdomain.org] acme: Preparing to solve DNS-01
2021/05/28 20:57:22 [INFO] [*.mytestdomain.org] acme: Trying to solve DNS-01
2021/05/28 20:57:22 [INFO] [*.mytestdomain.org] acme: Checking DNS record propagation using [192.168.65.5:53]
2021/05/28 20:57:24 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2021/05/28 20:57:31 [INFO] [*.mytestdomain.org] The server validated our request
2021/05/28 20:57:31 [INFO] [mytestdomain.org] acme: Trying to solve DNS-01
2021/05/28 20:57:31 [INFO] [mytestdomain.org] acme: Checking DNS record propagation using [192.168.65.5:53]
2021/05/28 20:57:33 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2021/05/28 20:57:40 [INFO] [mytestdomain.org] The server validated our request
2021/05/28 20:57:40 [INFO] [*.mytestdomain.org] acme: Cleaning DNS-01 challenge
2021/05/28 20:57:41 [INFO] [mytestdomain.org] acme: Cleaning DNS-01 challenge
2021/05/28 20:57:41 [INFO] [*.mytestdomain.org, mytestdomain.org] acme: Validations succeeded; requesting certificates
2021/05/28 20:57:46 [INFO] [*.mytestdomain.org] Server responded with a certificate.
root@2a721b9d0575:/workspaces/lego# git rev-parse HEAD
3a79d462cc7035e285a60c270f4b3dbf7f7b45b1
```

**Comment by ldez** [comment]
To be stateless, the trick is to use the `connector` instead of the `objectManager`, create an implementation to get all records, iterate over the records, find the right value, and get the record ref.

But a `map` and a lock do the same job and it's less code.

So I will keep this implementation.

**Review by ldez — APPROVED** [review]
Thanks :+1:

**Pull request merged**
