### PR TITLE
Add DNS provider for wedos

### PR DESCRIPTION
**Pull request by lubko**
DNS provider for wedos.com
web: https://www.wedos.com
apis: https://kb.wedos.com/en/kategorie/wapi-api-interface/
dns api documentation: https://kb.wedos.com/en/kategorie/wapi-api-interface/wdns-en/

### CODE REVIEW

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests (units)
```shell
make test
```
- [ ] add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help, documentation, and readme.
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`

**Comment by lubko** [comment]
~/lego$ WEDOS_USERNAME=your@email.com WEDOS_WAPI_PASSWORD="xxxxxxxxxxx" ./dist/lego --dns wedos -d *.example.com -d example.com --email your@email.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
2021/04/13 02:51:15 No key found for account your@email.com. Generating a P256 key.
2021/04/13 02:51:15 Saved key to /home/foo/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/your@email.com/keys/your@email.com.key
2021/04/13 02:51:16 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
y
2021/04/13 02:51:20 [INFO] acme: Registering account for your@email.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/home/foo/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2021/04/13 02:51:21 [INFO] [*.example.com, example.com] acme: Obtaining bundled SAN certificate
2021/04/13 02:51:23 [INFO] [*.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/27035518
2021/04/13 02:51:23 [INFO] [example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/27035519
2021/04/13 02:51:23 [INFO] [*.example.com] acme: use dns-01 solver
2021/04/13 02:51:23 [INFO] [example.com] acme: Could not find solver for: tls-alpn-01
2021/04/13 02:51:23 [INFO] [example.com] acme: Could not find solver for: http-01
2021/04/13 02:51:23 [INFO] [example.com] acme: use dns-01 solver
2021/04/13 02:51:23 [INFO] [*.example.com] acme: Preparing to solve DNS-01
2021/04/13 02:51:23 [INFO] [example.com] acme: Preparing to solve DNS-01
2021/04/13 02:51:24 [INFO] [*.example.com] acme: Trying to solve DNS-01
2021/04/13 02:51:24 [INFO] [*.example.com] acme: Checking DNS record propagation using [172.23.208.1:53]
2021/04/13 02:51:34 [INFO] Wait for propagation [timeout: 10m0s, interval: 10s]
2021/04/13 02:51:34 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:51:44 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:51:54 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:52:04 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:52:14 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:52:24 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:52:34 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:52:44 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:52:55 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:53:05 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:53:15 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:53:25 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:53:35 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:53:45 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:53:55 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:54:05 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:54:15 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:54:25 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:54:35 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:54:45 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:54:55 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:55:05 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:55:15 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:55:25 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:55:35 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:55:45 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:55:55 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:56:06 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:56:16 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:56:26 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:56:36 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:56:46 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:56:56 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/04/13 02:57:13 [INFO] [*.example.com] The server validated our request
2021/04/13 02:57:13 [INFO] [example.com] acme: Trying to solve DNS-01
2021/04/13 02:57:13 [INFO] [example.com] acme: Checking DNS record propagation using [172.23.208.1:53]
2021/04/13 02:57:23 [INFO] Wait for propagation [timeout: 10m0s, interval: 10s]
2021/04/13 02:57:31 [INFO] [example.com] The server validated our request
2021/04/13 02:57:31 [INFO] [*.example.com] acme: Cleaning DNS-01 challenge
2021/04/13 02:57:31 [INFO] [example.com] acme: Cleaning DNS-01 challenge
2021/04/13 02:57:31 [INFO] [*.example.com, example.com] acme: Validations succeeded; requesting certificates
2021/04/13 02:57:33 [INFO] [*.example.com] Server responded with a certificate.

**Comment by lubko** [comment]
Hello and thank you for having a look at my contribution.
If I understand it correctly, two checkboxes remain unchecked so i will try to elaborate on those.

* be able to maintain this provider
I am not affiliated with the company, I just happen to be their paying customer. That said, I do not mind coming back if anything changes, as I will likely do in my own interest anyway. I will as well notify the company about this implementation if it gets approved.

* have a homogeneous design with the other providers
Before going on and making unrequired changes, I would kindly ask for bit of hint or feedback.
There is one aspect i see as polarizing and that is implementing https://github.com/libdns/libdns
I will try to explain myself. 
I found libdns when looking for an existing implementation and thought i would implement it and then use it inside lego. That way more projects can benefit from the same source code.
This being my first contribution, i decided "A little copying is better than a little dependency." (https://go-proverbs.github.io/), as it would be trivial to link it externally later. Also while working on it, i did not grow too impressed with the libdns interface, being it too vague. So my plan is to keep implementing it, as the interface matures and eventually move it under libdns/* umbrella and keep just an wrapper inside lego. However i don't plan of going trough the labor just yet, (i would like to start using lego much sooner).
Anyway i am also willing to throw it all out if you find it an eyesore.

**Review by ldez — APPROVED** [review]
Currently, I prefer the freedom of "classic" client implementation.
Because I don't want to waste your time, I decided to refactor your PR to follow our design requirements, and be homogeneous with the other providers.

Thank you for your work :+1:

**Comment by lubko** [comment]
Awesome, looks good.
I did a little update afterwards in #1386

**Pull request merged**
