### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by ldez**
- https://github.com/golang/crypto/compare/v0.24.0...v0.27.0
- https://github.com/golang/mod/compare/v0.18.0...v0.21.0
- https://github.com/golang/net/compare/v0.26.0...v0.29.0
- https://github.com/golang/sync/compare/v0.7.0...v0.8.0
- https://github.com/golang/sys/compare/v0.21.0...v0.25.0
- https://github.com/golang/text/compare/v0.16.0...v0.18.0
- https://github.com/golang/time/compare/v0.5.0...v0.6.0
- https://github.com/golang/tools/compare/v0.22.0...v0.25.0
- https://github.com/miekg/dns/compare/v1.1.59...v1.1.62
- https://github.com/go-jose/go-jose/compare/v4.0.2...v4.0.4
- https://github.com/go-viper/mapstructure/compare/v2.0.0...v2.1.0
- https://github.com/urfave/cli/compare/v2.27.2...v2.27.4
- https://github.com/SSLMate/go-pkcs12/compare/v0.4.0...v0.5.0
- https://github.com/cloudflare/cloudflare-go/compare/v0.97.0...v0.104.0
- https://github.com/linode/linodego/compare/v1.28.0...v1.40.0
- https://github.com/nrdcg/porkbun/compare/v0.3.0...v0.4.0
- https://github.com/oracle/oci-go-sdk/compare/v65.63.1...v65.73.0
- https://github.com/ovh/go-ovh/compare/v1.5.1...v1.6.0
- https://github.com/scaleway/scaleway-sdk-go/compare/v1.0.0-beta.27...v1.0.0-beta.30
- https://github.com/transip/gotransip/compare/v6.23.0...v6.26.0
- https://github.com/ultradns/ultradns-go-sdk/compare/v1.6.2-20240501171831-432d643...v1.7.0-20240913052650-970ca9a
- https://github.com/vultr/govultr/compare/v3.9.0...v3.9.1
- https://github.com/ns1/ns1-go/compare/v2.7.13...v2.12.0
- https://github.com/exoscale/egoscale/compare/v3.1.1...v3.1.5
- https://github.com/gophercloud/gophercloud/compare/v1.12.0...v1.14.0
- https://github.com/gofrs/flock/compare/v0.10.0...v1.12.1
- https://github.com/huaweicloud/huaweicloud-sdk-go-v3/compare/v0.1.113...v0.1.114
- https://github.com/yandex-cloud/go-genproto/compare/4fe6125f286e...1fa0cb6f47c2
- https://github.com/yandex-cloud/go-sdk/compare/dfa50323a0b4...e4e74d0d02f5
- https://github.com/tencentcloud/tencentcloud-sdk-go/compare/tencentcloud/common/v1.0.898...tencentcloud/common/v1.0.1002
- https://github.com/tencentcloud/tencentcloud-sdk-go/compare/tencentcloud/dnspod/v1.0.898...tencentcloud/dnspod/v1.0.1002
- https://github.com/aliyun/alibaba-cloud-sdk-go/compare/v1.63.14...v1.63.15
- https://github.com/Azure/azure-sdk-for-go/compare/sdk/azidentity/v1.6.0...sdk/azidentity/v1.7.0
- https://github.com/Azure/azure-sdk-for-go/compare/sdk/azcore/v1.12.0...sdk/azcore/v1.14.0
- https://github.com/aws/aws-sdk-go-v2/compare/v1.27.2...v1.30.5
- https://github.com/aws/aws-sdk-go-v2/compare/service/sts/v1.28.12...service/sts/v1.30.7
- https://github.com/aws/aws-sdk-go-v2/compare/credentials/v1.17.18...credentials/v1.17.32
- https://github.com/aws/aws-sdk-go-v2/compare/config/v1.27.18...config/v1.27.33
- https://github.com/aws/aws-sdk-go-v2/compare/service/lightsail/v1.38.3...service/lightsail/v1.40.6
- https://github.com/aws/aws-sdk-go-v2/compare/service/route53/v1.40.10...service/route53/v1.43.2
- https://github.com/aws/aws-sdk-go-v2/compare/service/s3/v1.55.1...service/s3/v1.61.2
- https://github.com/GoogleCloudPlatform/gcloud-golang/compare/compute/metadata/v0.5.0...compute/metadata/v0.5.1
- https://github.com/googleapis/google-api-go-client/compare/v0.172.0...v0.197.0

### CODE REVIEW

**Review by dmke — APPROVED** [review]

**Comment by dmke** [comment]
@ldez: btw, I'm curious, do you have a tool to update dependencies individually?

In my projects, I'm usually doing a `go get -d -t -u ./...` followed by `make test lint`, and a single `git commit -m 'update dependencies'` (unless the tests fail and/or the linter noticed some deprecation warnings).

**Comment by ldez** [comment]
yes and no, I created [modupwiz](https://github.com/ldez/modupwiz) to detect the dependencies to update and generate the compare links.

I "hacked" my own tool to generate a base script inside this branch https://github.com/ldez/modupwiz/tree/feat/script

I modify and use this script to validate each dependency and have a specific update order.

**Comment by dmke** [comment]
Cool. I may start using (something based off of) this in the future. I've run a few times into the situation where some weird dependencies broke builds and it wasn't immediately clear which dependency was the culprit.

Having something to create a commit for each dependency make debugging a bit easier (`git bisect` ftw.). Thinking of it, this could be automated relatively far (update first dependency, run tests; on success create commit, on failure add dependency to a report; continue with next dependency).

This could also run as scheduled CI job, where the final step would be "create a PR", containing the report. But I guess that's already very similar to dependabot et.al.

**Comment by ldez** [comment]
@dmke I replaced my previous hack with a more generic approach.

It was not simple to find this generic way because I learned something about Go dependencies management: it's not possible to have cyclic packages (we all know that) but it's possible to have cyclic imports.

For example, `golang.org/x/mod` depends on `golang.org/x/tools`, and `golang.org/x/tools` depends on `golang.org/x/mod`.

https://github.com/golang/mod/blob/dec0365065b75edd0e98b0306f6f9b0051710ed2/go.mod#L5
https://github.com/golang/tools/blob/44670c7f61274a590108667938d4e33d8d9bdd4a/go.mod#L8

So I was forced to create a topological sorting with the detection of strongly connected components.

---

For now, the new command is hidden, but you can try it:

```
modupwiz -path=bump.sh template
```
```
modupwiz -path=bump.sh template -template=yourfile.tmpl
```

**Pull request merged**
