### PR TITLE
Add DNS provider for Porkbun

### LINKED ISSUE #1395: Add support for Porkbun DNS
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, the DNS provider exposes a public API.
- [x] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation
- [x] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider. 

### Link to the DNS provider

[https://porkbun.com/](https://porkbun.com/)

### Link to the API documentation

[https://porkbun.com/api/json/v3/documentation](https://porkbun.com/api/json/v3/documentation)

### Additional Notes

The API is pretty new and claims to be in beta, but it seems to have enough basic functionality for DNS challenges. I'm not familiar with Go, but I'm happy to help testing or in any other way. 

acme.sh has it implemented [here](https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_porkbun.sh) if that's useful.

### PR DESCRIPTION
**Pull request by ldez**
- [x] have a homogeneous design with the other providers
- [x] pass the linter
- [x] do `go mod tidy`
- [x] add tests (units)
- [x] add tests ("live")
- [x] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [x] generate CLI help, documentation, and readme.
- [x] be able to do: _(and put the output of this command to a comment)_
```bash
rm -rf .lego

PORKBUN_SECRET_API_KEY=xxx PORKBUN_PAPI_KEY=yyy ./lego -m your_email@example.com --dns porkbun -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.

@eosti could you test by running the previous command (you have to use a real domain and email)?

Closes #1395

### CODE REVIEW

**Comment by eosti** [comment]
Thank you for getting this set up so quickly!

A few issues: While your command and the documentation use the variable `PORKBUN_SECRET_API_KEY` and `PORKBUN_PAPI_KEY`, the command expects `PORKBUN_API_KEY` and `PORKBUN_SECRET_API_KEY`, respectively. 

Additionally, the command fails to create the TXT record (information redated appropriately; I was using my actual email and an existing domain that I've used letsencrypt on manually before):

```
2021/05/01 12:04:11 No key found for account example@example.com. Generating a P256 key.
2021/05/01 12:04:11 Saved key to /Users/eosti/Projects/lego/dist/.lego/accounts/acme-staging-v02.api.letsencrypt.org/example@example.com/keys/example@example.com.key
2021/05/01 12:04:12 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
y
2021/05/01 12:04:14 [INFO] acme: Registering account for example@example.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/Users/eosti/Projects/lego/dist/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2021/05/01 12:04:14 [INFO] [*.example.com, example.com] acme: Obtaining bundled SAN certificate
2021/05/01 12:04:14 [INFO] [*.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/12345
2021/05/01 12:04:14 [INFO] [example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/12345
2021/05/01 12:04:14 [INFO] [*.example.com] acme: use dns-01 solver
2021/05/01 12:04:14 [INFO] [example.com] acme: Could not find solver for: tls-alpn-01
2021/05/01 12:04:14 [INFO] [example.com] acme: Could not find solver for: http-01
2021/05/01 12:04:14 [INFO] [example.com] acme: use dns-01 solver
2021/05/01 12:04:14 [INFO] [*.example.com] acme: Preparing to solve DNS-01
2021/05/01 12:04:15 [INFO] [example.com] acme: Preparing to solve DNS-01
2021/05/01 12:04:15 [INFO] [*.example.com] acme: Cleaning DNS-01 challenge
2021/05/01 12:04:15 [WARN] [*.example.com] acme: cleaning up failed: porkbun: unknown record ID for '_acme-challenge.example.com.' 'dns_challenge_key'
2021/05/01 12:04:15 [INFO] [example.com] acme: Cleaning DNS-01 challenge
2021/05/01 12:04:15 [WARN] [example.com] acme: cleaning up failed: porkbun: unknown record ID for '_acme-challenge.example.com.' 'also_dns_challenge_key'
2021/05/01 12:04:15 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/12345
2021/05/01 12:04:16 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/12345
2021/05/01 12:04:16 Could not obtain certificates:
        error: one or more domains had a problem:
[*.example.com] [*.example.com] acme: error presenting token: porkbun: failed to create record: 400: {"status":"ERROR","message":"Invalid domain."}
[example.com] [example.com] acme: error presenting token: porkbun: failed to create record: 400: {"status":"ERROR","message":"Invalid domain."}
```

I don't know why this is happening, though I am rather suspicious at the trailing period in the reported URL (ex. `porkbun: unknown record ID for '_acme-challenge.example.com.' 'also_dns_challenge_key'`). I tried hitting the API manually without the period, and it worked fine, but after adding the period I got the same error as lego. 

Let me know if you need any extra information to figure out what's causing the issue.

**Comment by ldez** [comment]
I fixed the problems, could you retry?

**Comment by eosti** [comment]
No luck, though this time there's a different error. The trailing period still seems to be there, not sure if that's relevant or not. 

```
2021/05/01 13:27:17 No key found for account example@example.com. Generating a P256 key.
2021/05/01 13:27:17 Saved key to /Users/eosti/Projects/lego/dist/.lego/accounts/acme-staging-v02.api.letsencrypt.org/example@example.com/keys/example@example.com.key
2021/05/01 13:27:17 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
y
2021/05/01 13:27:21 [INFO] acme: Registering account for example@example.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/Users/eosti/Projects/lego/dist/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2021/05/01 13:27:21 [INFO] [*.example.com, example.com] acme: Obtaining bundled SAN certificate
2021/05/01 13:27:22 [INFO] [*.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/1234
2021/05/01 13:27:22 [INFO] [example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/1234
2021/05/01 13:27:22 [INFO] [*.example.com] acme: use dns-01 solver
2021/05/01 13:27:22 [INFO] [example.com] acme: Could not find solver for: tls-alpn-01
2021/05/01 13:27:22 [INFO] [example.com] acme: Could not find solver for: http-01
2021/05/01 13:27:22 [INFO] [example.com] acme: use dns-01 solver
2021/05/01 13:27:22 [INFO] [*.example.com] acme: Preparing to solve DNS-01
2021/05/01 13:27:23 [INFO] [example.com] acme: Preparing to solve DNS-01
2021/05/01 13:27:23 [INFO] [*.example.com] acme: Cleaning DNS-01 challenge
2021/05/01 13:27:23 [WARN] [*.example.com] acme: cleaning up failed: porkbun: unknown record ID for '_acme-challenge.example.com.' 'key1'
2021/05/01 13:27:23 [INFO] [example.com] acme: Cleaning DNS-01 challenge
2021/05/01 13:27:23 [WARN] [example.com] acme: cleaning up failed: porkbun: unknown record ID for '_acme-challenge.example.com.' 'key2'
2021/05/01 13:27:23 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/1234
2021/05/01 13:27:23 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/1234
2021/05/01 13:27:23 Could not obtain certificates:
        error: one or more domains had a problem:
[*.example.com] [*.example.com] acme: error presenting token: porkbun: failed to create record: failed to unmarshal response: json: cannot unmarshal number into Go struct field createResponse.id of type string
[example.com] [example.com] acme: error presenting token: porkbun: failed to create record: failed to unmarshal response: json: cannot unmarshal number into Go struct field createResponse.id of type string
```

**Comment by ldez** [comment]
> json: cannot unmarshal number into Go struct field createResponse.id of type string

It sounds like the porkbun API doc is wrong...

Could you give me the JSON output of the `create`  and `retrieve` API calls?

**Comment by eosti** [comment]
`create`:`POST` to `https://porkbun.com/api/json/v3/dns/create/example.com`

Body: 
```
{
	"secretapikey": "secretkey",
	"apikey": "apikey",
        "name": "_acme-challenge",
        "type": "TXT",
        "content": "hello",
        "ttl": "300"
}
```
Response:
```
{
    "status": "SUCCESS",
    "id": 123456789
}
```
`retrieve`: `POST` to `https://porkbun.com/api/json/v3/dns/retrieve/example.com`:

Body:
```
{
	"secretapikey": "secretkey",
	"apikey": "apikey"
}
```
Response:
```
{
    "status": "SUCCESS",
    "cloudflare": "disabled",
    "records": [
        {
            "id": "12345",
            "name": "example.com",
            "type": "ALIAS",
            "content": "uixie.porkbun.com",
            "ttl": "600",
            "prio": null
        },
        {
            "id": "12345",
            "name": "example.com",
            "type": "MX",
            "content": "fwd1.porkbun.com",
            "ttl": "300",
            "prio": "10"
        },
        {
            "id": "12345",
            "name": "example.com",
            "type": "MX",
            "content": "fwd2.porkbun.com",
            "ttl": "300",
            "prio": "20"
        },
        {
            "id": "12345",
            "name": "_autodiscover._tcp.example.com",
            "type": "SRV",
            "content": "10 443 webmail.porkbun.com",
            "ttl": "300",
            "prio": "10"
        },
        {
            "id": "12345",
            "name": "example.com",
            "type": "TXT",
            "content": "v=spf1 mx ~all",
            "ttl": "300",
            "prio": null
        },
        {
            "id": "123456789",
            "name": "_acme-challenge.example.com",
            "type": "TXT",
            "content": "hello",
            "ttl": "300",
            "prio": "0"
        }
    ]
}
```
Side note, lego does create the DNS records,  so it must be erroring out after sending the POST.

**Comment by ldez** [comment]
Thank you, so there is an inconsistency between the APIs, the ID field does not have the same type and the API doc is wrong.

I fixed the problem.

**Comment by eosti** [comment]
I sent Porkbun a message letting them know about the API/documentation mismatch. I'll let you know the result of that if it affects the implementation here. 

New issue, however!

```
2021/05/01 14:08:50 No key found for account example@example.com. Generating a P256 key.
2021/05/01 14:08:50 Saved key to /Users/eosti/Projects/lego/dist/.lego/accounts/acme-staging-v02.api.letsencrypt.org/example@example.com/keys/example@example.com.key
2021/05/01 14:08:50 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
y
2021/05/01 14:08:53 [INFO] acme: Registering account for example@example.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/Users/eosti/Projects/lego/dist/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2021/05/01 14:08:53 [INFO] [*.example.com, example.com] acme: Obtaining bundled SAN certificate
2021/05/01 14:08:53 [INFO] [*.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/12345
2021/05/01 14:08:53 [INFO] [example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/12345
2021/05/01 14:08:53 [INFO] [*.example.com] acme: use dns-01 solver
2021/05/01 14:08:53 [INFO] [example.com] acme: Could not find solver for: tls-alpn-01
2021/05/01 14:08:53 [INFO] [example.com] acme: Could not find solver for: http-01
2021/05/01 14:08:53 [INFO] [example.com] acme: use dns-01 solver
2021/05/01 14:08:53 [INFO] [*.example.com] acme: Preparing to solve DNS-01
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/go-acme/lego/v4/providers/dns/porkbun.(*DNSProvider).Present(0xc00052c0c0, 0xc0005bc3b3, 0xd, 0xc00036a0c0, 0x2b, 0xc0004aaba0, 0x57, 0xc0005bc3b0, 0x3)
        github.com/go-acme/lego/v4/providers/dns/porkbun/porkbun.go:134 +0x3cb
github.com/go-acme/lego/v4/challenge/dns01.(*Challenge).PreSolve(0xc0000c0340, 0xc0005bc3c0, 0x7, 0x0, 0xed828f4e5, 0x0, 0xc0005bc3b0, 0x3, 0xc0005bc3b3, 0xd, ...)
        github.com/go-acme/lego/v4/challenge/dns01/dns_challenge.go:94 +0x314
github.com/go-acme/lego/v4/challenge/resolver.parallelSolve(0xc000365110, 0x2, 0x2, 0xc0005268d0)
        github.com/go-acme/lego/v4/challenge/resolver/prober.go:135 +0x122
github.com/go-acme/lego/v4/challenge/resolver.(*Prober).Solve(0xc0003660c0, 0xc00023a820, 0x2, 0x2, 0x14, 0xc00011c000)
        github.com/go-acme/lego/v4/challenge/resolver/prober.go:84 +0x365
github.com/go-acme/lego/v4/certificate.(*Certifier).Obtain(0xc0005262a0, 0xc000369400, 0x2, 0x2, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/go-acme/lego/v4/certificate/certificates.go:124 +0x36a
github.com/go-acme/lego/v4/cmd.obtainCertificate(0xc0004b8160, 0xc00052c0a0, 0x25033f3, 0x145, 0xc00031f760)
        github.com/go-acme/lego/v4/cmd/cmd_run.go:171 +0x31c
github.com/go-acme/lego/v4/cmd.run(0xc0004b8160, 0xc00036e500, 0x2)
        github.com/go-acme/lego/v4/cmd/cmd_run.go:88 +0xe5
github.com/urfave/cli.HandleAction(0x2146240, 0x252e948, 0xc0004b8160, 0xc0004b8160, 0x0)
        github.com/urfave/cli@v1.22.4/app.go:526 +0x105
github.com/urfave/cli.Command.Run(0x249f249, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x24efacd, 0x3a, 0x0, ...)
        github.com/urfave/cli@v1.22.4/command.go:174 +0x579
github.com/urfave/cli.(*App).Run(0xc00038e1c0, 0xc0000c2000, 0xc, 0xc, 0x0, 0x0)
        github.com/urfave/cli@v1.22.4/app.go:279 +0x808
main.main()
        github.com/go-acme/lego/v4/cmd/lego/main.go:42 +0x197
```

**Comment by ldez** [comment]
Fixed

**Comment by eosti** [comment]
Yay, everything is now working as expected.  Output of the last run:

```
2021/05/01 14:26:49 No key found for account example@example.com. Generating a P256 key.
2021/05/01 14:26:49 Saved key to /Users/eosti/Projects/lego/dist/.lego/accounts/acme-staging-v02.api.letsencrypt.org/example@example.com/keys/example@example.com.key
2021/05/01 14:26:49 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
y
2021/05/01 14:26:52 [INFO] acme: Registering account for example@example.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/Users/eosti/Projects/lego/dist/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2021/05/01 14:26:52 [INFO] [*.example.com, example.com] acme: Obtaining bundled SAN certificate
2021/05/01 14:26:52 [INFO] [*.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/12345
2021/05/01 14:26:52 [INFO] [example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/12345
2021/05/01 14:26:52 [INFO] [*.example.com] acme: use dns-01 solver
2021/05/01 14:26:52 [INFO] [example.com] acme: Could not find solver for: tls-alpn-01
2021/05/01 14:26:52 [INFO] [example.com] acme: Could not find solver for: http-01
2021/05/01 14:26:52 [INFO] [example.com] acme: use dns-01 solver
2021/05/01 14:26:52 [INFO] [*.example.com] acme: Preparing to solve DNS-01
2021/05/01 14:26:53 [INFO] [example.com] acme: Preparing to solve DNS-01
2021/05/01 14:26:53 [INFO] [*.example.com] acme: Trying to solve DNS-01
2021/05/01 14:26:53 [INFO] [*.example.com] acme: Checking DNS record propagation using [192.168.99.21:53 192.168.11.1:53]
2021/05/01 14:27:03 [INFO] Wait for propagation [timeout: 10m0s, interval: 10s]
2021/05/01 14:27:09 [INFO] [*.example.com] The server validated our request
2021/05/01 14:27:09 [INFO] [example.com] acme: Trying to solve DNS-01
2021/05/01 14:27:09 [INFO] [example.com] acme: Checking DNS record propagation using [192.168.99.21:53 192.168.11.1:53]
2021/05/01 14:27:19 [INFO] Wait for propagation [timeout: 10m0s, interval: 10s]
2021/05/01 14:27:20 [INFO] [example.com] acme: Waiting for DNS record propagation.
2021/05/01 14:27:37 [INFO] [example.com] The server validated our request
2021/05/01 14:27:37 [INFO] [*.example.com] acme: Cleaning DNS-01 challenge
2021/05/01 14:27:38 [INFO] [example.com] acme: Cleaning DNS-01 challenge
2021/05/01 14:27:38 [INFO] [*.example.com, example.com] acme: Validations succeeded; requesting certificates
2021/05/01 14:27:39 [INFO] [*.example.com] Server responded with a certificate.
```

Thank you again for your time!

**Comment by ldez** [comment]
Thank you for your time too!

**Review by dmke — APPROVED** [review]
LGTM

**Pull request merged**
