### PR TITLE
Deprecate OS_TENANT_NAME as required field

### PR DESCRIPTION
**Pull request by skatsaounis**
This PR removes the `OS_TENANT_NAME` from the required environment variables since, if set, it breaks authentication in OpenStack deployments where `OS_PROJECT_NAME` and `OS_PROJECT_ID` should be used.

For the record, the following message is received in case `OS_TENANT_NAME` is set only to pass `lego` validation check:

`Error: designate: failed to authenticate: You must provide exactly one of DomainID or DomainName to authenticate by Username`

Fixes: #1254

### CODE REVIEW

**Review by ldez — APPROVED** [review]
Thank you :+1:

**Comment by skatsaounis** [comment]
@ldez Thanks for merging this one.

One question here is, should it be considered an enhancement or bug fix? In my opinion, it is the latter since in OpenStack Train which I use, I cannot use go-acme without this fix. And current OpenStack version is Victoria (two versions ahead).

I do not know your release cycle but I would love to have a ×.×.1 release with this change in 😄

**Comment by ldez** [comment]
The information is in the labels and the milestone of this PR.

>  I cannot use go-acme without this fix

How do you use lego? as a CLI ? as a lib?

**Comment by skatsaounis** [comment]
Thank you very much for the info. Ok, then I have to wait for 4.1 release. Any estimation regarding its availability?

Actually, I am using it through Terraform acme provider. So the next step for me is to open a PR here https://github.com/vancluever/terraform-provider-acme/blob/master/go.mod#L9 to use a version with the fix in place.

I know that I will wait a long time until finally be able to consume the change but I am trying to speed up things the best way possible.

**Pull request merged**
