### PR TITLE
Add DNS provider for g-core labs

### PR DESCRIPTION
**Pull request by shubinmi**
Extending of DNS providers with G-Core DNS Service https://gcorelabs.com/dns/

### CODE REVIEW

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests (units)
```shell
make test
```
- [ ] add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help, documentation, and readme.
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`

**Comment by shubinmi** [comment]
**be able to maintain this provider**
yes

**GCORE_PERMANENT_API_TOKEN="myToken" ./dist/lego -m shubinmi@gmail.com --dns gcore -d '*.g-core.tk' -d g-core.tk -s https://acme-staging-v02.api.letsencrypt.org/directory run**
2021/07/19 16:45:19 [INFO] [*.g-core.tk, g-core.tk] acme: Obtaining bundled SAN certificate
2021/07/19 16:45:20 [INFO] [*.g-core.tk] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/92559187
2021/07/19 16:45:20 [INFO] [g-core.tk] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/92562339
2021/07/19 16:45:20 [INFO] [*.g-core.tk] acme: authorization already valid; skipping challenge
2021/07/19 16:45:20 [INFO] [g-core.tk] acme: authorization already valid; skipping challenge
2021/07/19 16:45:20 [INFO] [*.g-core.tk, g-core.tk] acme: Validations succeeded; requesting certificates
2021/07/19 16:45:20 [INFO] [*.g-core.tk] Server responded with a certificate.
Screenshot 2021-07-19 at 16 47 03


**pass the linter (golangci-lint must be installed)**
Screenshot 2021-07-19 at 16 30 55

**Comment by ldez** [comment]
I need the full log, not just 5 lines.

**Comment by shubinmi** [comment]
> I need the full log, not just 5 lines. (please no screenshot)
> 
> the command `rm -rf .lego` is important.
> 
> Are you a customer or a member of g-core labs?

`GCORE_PERMANENT_API_TOKEN="myToken" ./dist/lego -m my@gmail.com --dns gcore -d '*.g-core.tk' -d g-core.tk -s https://acme-staging-v02.api.letsencrypt.org/directory run
2021/07/20 12:05:04 No key found for account my@gmail.com. Generating a P256 key.
2021/07/20 12:05:04 Saved key to /Users/maxim/develope/local/gcore/lego-gcore/.lego/accounts/acme-staging-v02.api.letsencrypt.org/my@gmail.com/keys/my@gmail.com.key
2021/07/20 12:05:05 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
н
Your input was invalid. Please answer with one of Y/y, n/N or by pressing enter.
Do you accept the TOS? Y/n
y
2021/07/20 12:05:12 [INFO] acme: Registering account for shubinmi@gmail.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/Users/maxim/develope/local/gcore/lego-gcore/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2021/07/20 12:05:12 [INFO] [*.g-core.tk, g-core.tk] acme: Obtaining bundled SAN certificate
2021/07/20 12:05:13 [INFO] [*.g-core.tk] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/93175922
2021/07/20 12:05:13 [INFO] [g-core.tk] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/93175923
2021/07/20 12:05:13 [INFO] [*.g-core.tk] acme: use dns-01 solver
2021/07/20 12:05:13 [INFO] [g-core.tk] acme: Could not find solver for: tls-alpn-01
2021/07/20 12:05:13 [INFO] [g-core.tk] acme: Could not find solver for: http-01
2021/07/20 12:05:13 [INFO] [g-core.tk] acme: use dns-01 solver
2021/07/20 12:05:13 [INFO] [*.g-core.tk] acme: Preparing to solve DNS-01
2021/07/20 12:05:13 [INFO] [g-core.tk] acme: Preparing to solve DNS-01
2021/07/20 12:05:14 [INFO] [*.g-core.tk] acme: Trying to solve DNS-01
2021/07/20 12:05:14 [INFO] [*.g-core.tk] acme: Checking DNS record propagation using [10.254.1.140:53 10.254.0.140:53]
2021/07/20 12:05:34 [INFO] Wait for propagation [timeout: 6m0s, interval: 20s]
2021/07/20 12:05:34 [INFO] [*.g-core.tk] acme: Waiting for DNS record propagation.
2021/07/20 12:05:54 [INFO] [*.g-core.tk] acme: Waiting for DNS record propagation.
2021/07/20 12:06:14 [INFO] [*.g-core.tk] acme: Waiting for DNS record propagation.
2021/07/20 12:06:36 [INFO] [*.g-core.tk] The server validated our request
2021/07/20 12:06:36 [INFO] [g-core.tk] acme: Trying to solve DNS-01
2021/07/20 12:06:36 [INFO] [g-core.tk] acme: Checking DNS record propagation using [10.254.1.140:53 10.254.0.140:53]
2021/07/20 12:06:56 [INFO] Wait for propagation [timeout: 6m0s, interval: 20s]
2021/07/20 12:07:02 [INFO] [g-core.tk] The server validated our request
2021/07/20 12:07:02 [INFO] [*.g-core.tk] acme: Cleaning DNS-01 challenge
2021/07/20 12:07:02 [INFO] [g-core.tk] acme: Cleaning DNS-01 challenge
2021/07/20 12:07:03 [INFO] [*.g-core.tk, g-core.tk] acme: Validations succeeded; requesting certificates
2021/07/20 12:07:03 [INFO] [*.g-core.tk] Server responded with a certificate.`

yep, I am a member.

**Comment by ldez** [comment]
There is a problem: as your PR comes from an organization I'm not able to add commits.

Then we have several solutions:
- re-create the PR from your personal account
- allow me to edit the PR: you have to add me into your organization (I know it's weird but it's related to GitHub)
- I recreate a PR with your commits.

Why do I want to add commits? because currently, your PR doesn't follow our standards, and then it's not homogeneous with the other providers.

**Comment by shubinmi** [comment]
I created new PR https://github.com/go-acme/lego/pull/1456

**Pull request closed without merging**
