### PR TITLE
Add HTTP Provider for S3 and CloudFront

### PR DESCRIPTION
**Pull request by beornf**
Support for AWS S3 as a HTTP provider which can optionally be used in combination with a CloudFront distribution pointing to the requested S3 bucket.

To upload the HTTP challenge key the provider takes in two arguments: the name of the S3 bucket and the S3 region.

### CODE REVIEW

**Comment by ldez** [comment]
could you fix:
```
providers/http/s3/s3.go:15:6:warning: exported type HTTPProvider should have comment or be unexported (golint)
providers/http/s3/s3.go:20:1:warning: exported function NewHTTPProvider should have comment or be unexported (golint)
providers/http/s3/s3.go:39:1:warning: exported method HTTPProvider.Present should have comment or be unexported (golint)
providers/http/s3/s3.go:53:1:warning: exported method HTTPProvider.CleanUp should have comment or be unexported (golint)
```

**Comment by ldez** [comment]
Could someone do some tests of the functionality on real cases?

**Comment by ldez** [comment]
This PR is too old an outdated.
I close.

**Comment by beornf** [comment]
Fair enough. I moved to golang.org/x/crypto/acme around this time.

**Pull request closed without merging**
