### PR TITLE
digitalocean: LEGO_EXPERIMENTAL_CNAME_SUPPORT support

### PR DESCRIPTION
**Pull request by ZimboBoyd**
With this patch LEGO_EXPERIMENTAL_CNAME_SUPPORT will work on digitalocean as dns provider

### CODE REVIEW

**Comment by ldez** [comment]
Thanks.

To validate the non-regression could you run the following commands and give me the output:

```bash
## Without LEGO_EXPERIMENTAL_CNAME_SUPPORT
rm -rf .lego

./lego -m your@email.com --dns digitalocean -d *.mydomain.com -d mydomain.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```

```bash
## Without LEGO_EXPERIMENTAL_CNAME_SUPPORT
rm -rf .lego

./lego -m your@email.com --dns digitalocean -d *.my.domain.com -d my.domain.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.

**Comment by ZimboBoyd** [comment]
Yes here is the output of my Test: https://gist.github.com/ZimboBoyd/619acf69d6cc2f9068ec690969e97b56

**Comment by ldez** [comment]
In your file I cannot see if you have done the tests without CNAME (non-regression)

**Comment by ZimboBoyd** [comment]
The last test ist without a CNAME:

lego git:(pr-885) rm -rf .lego ; ./dist/lego -m wb@stylite.de --dns digitalocean -d '*.cloudraiser.net' -d cloudraiser.net -s https://acme-staging-v02.api.letsencrypt.org/directory -a --dns.resolvers='8.8.8.8:53' run

**Comment by ldez** [comment]
Could you do the 2nd command:
```bash
## Without LEGO_EXPERIMENTAL_CNAME_SUPPORT
rm -rf .lego

./lego -m your@email.com --dns digitalocean -d *.my.domain.com -d my.domain.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```

**Comment by ZimboBoyd** [comment]
I did it here: 


Test with the Patch on a domain without a CNAME (so no LEGO_EXPERIMENTAL_CNAME_SUPPORT needed)

lego git:(pr-885) rm -rf .lego ;  ./dist/lego -m wb@stylite.de --dns digitalocean -d '*.cloudraiser.net' -d cloudraiser.net -s https://acme-staging-v02.api.letsencrypt.org/directory -a --dns.resolvers='8.8.8.8:53' run
2019/05/09 16:14:31 No key found for account wb@stylite.de. Generating a P384 key.
2019/05/09 16:14:31 Saved key to /Users/bonis/go/src/github.com/go-acme/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/wb@stylite.de/keys/wb@stylite.de.key
2019/05/09 16:14:32 [INFO] acme: Registering account for wb@stylite.de
!!!! HEADS UP !!!!

		Your account credentials have been saved in your Let's Encrypt
		configuration directory at "/Users/bonis/go/src/github.com/go-acme/lego/.lego/accounts".
		You should make a secure backup	of this folder now. This
		configuration directory will also contain certificates and
		private keys obtained from Let's Encrypt so making regular
		backups of this folder is ideal.2019/05/09 16:14:32 [INFO] [*.cloudraiser.net, cloudraiser.net] acme: Obtaining bundled SAN certificate
2019/05/09 16:14:33 [INFO] [*.cloudraiser.net] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/niBpx0K6KWPiMpss25IcN6v-IHdPD_DyHMw9U8K3AkY
2019/05/09 16:14:33 [INFO] [cloudraiser.net] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/Ig1Phy5L32NmWBzKtM0VWnhu_UYkawxAcGxtOryimUA
2019/05/09 16:14:33 [INFO] [*.cloudraiser.net] acme: use dns-01 solver
2019/05/09 16:14:33 [INFO] [cloudraiser.net] acme: Could not find solver for: tls-alpn-01
2019/05/09 16:14:33 [INFO] [cloudraiser.net] acme: Could not find solver for: http-01
2019/05/09 16:14:33 [INFO] [cloudraiser.net] acme: use dns-01 solver
2019/05/09 16:14:33 [INFO] [*.cloudraiser.net] acme: Preparing to solve DNS-01
2019/05/09 16:14:34 [INFO] [cloudraiser.net] acme: Preparing to solve DNS-01
2019/05/09 16:14:34 [INFO] [*.cloudraiser.net] acme: Trying to solve DNS-01
2019/05/09 16:14:34 [INFO] [*.cloudraiser.net] acme: Checking DNS record propagation using [8.8.8.8:53]
2019/05/09 16:14:34 [INFO] Wait for propagation [timeout: 1m0s, interval: 5s]
2019/05/09 16:14:34 [INFO] [*.cloudraiser.net] acme: Waiting for DNS record propagation.
2019/05/09 16:14:39 [INFO] [*.cloudraiser.net] acme: Waiting for DNS record propagation.
2019/05/09 16:14:45 [INFO] [*.cloudraiser.net] acme: Waiting for DNS record propagation.
2019/05/09 16:14:56 [INFO] [*.cloudraiser.net] The server validated our request
2019/05/09 16:14:56 [INFO] [cloudraiser.net] acme: Trying to solve DNS-01
2019/05/09 16:14:56 [INFO] [cloudraiser.net] acme: Checking DNS record propagation using [8.8.8.8:53]
2019/05/09 16:14:56 [INFO] Wait for propagation [timeout: 1m0s, interval: 5s]
2019/05/09 16:14:57 [INFO] [cloudraiser.net] acme: Waiting for DNS record propagation.
2019/05/09 16:15:02 [INFO] [cloudraiser.net] The server validated our request
2019/05/09 16:15:02 [INFO] [*.cloudraiser.net] acme: Cleaning DNS-01 challenge
2019/05/09 16:15:03 [INFO] [cloudraiser.net] acme: Cleaning DNS-01 challenge
2019/05/09 16:15:03 [WARN] [cloudraiser.net] acme: error cleaning up: digitalocean: unknown record ID for '_acme-challenge.cloudraiser.net.'
2019/05/09 16:15:03 [INFO] [*.cloudraiser.net, cloudraiser.net] acme: Validations succeeded; requesting certificates
2019/05/09 16:15:04 [INFO] [*.cloudraiser.net] Server responded with a certificate.

**Comment by ZimboBoyd** [comment]
Or do you want a test with a domain which has a CNAME pointing to digitalocean? And it will fail?

**Comment by ldez** [comment]
I want a test with a subdomain: `my.domain.com`

**Comment by ZimboBoyd** [comment]
Ah, okay

Here is the test on a subdomain: https://gist.github.com/ZimboBoyd/d5e67552ccaba901c35b164b2cb5bb1f

**Pull request merged**
