### PR TITLE
Improve Name.com documentation

### PR DESCRIPTION
**Pull request by jflattery**
Add example bash commands.

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

the file you modified is generated automatically, you have to revert your changes and edit the following file:

- https://github.com/go-acme/lego/blob/master/providers/dns/namedotcom/namedotcom.toml

**Comment by jflattery** [comment]
Thanks for the clarification. Fixed.

**Comment by jflattery** [comment]
Unrelated, but I would like to contribute documentation on how to build using Docker. Where should that go?

**Comment by jflattery** [comment]
@ldez Is https://github.com/go-acme/lego/blob/master/docs/content/installation/_index.md generated from something else or should I modify this directly?

**Comment by ldez** [comment]
The generated files contains:

```
<!-- THIS DOCUMENTATION IS AUTO-GENERATED. PLEASE DO NOT EDIT. -->
<!-- ...l -->
<!-- THIS DOCUMENTATION IS AUTO-GENERATED. PLEASE DO NOT EDIT. -->
```

and the names start with `zz_gen_`

**Pull request merged**
