### PR TITLE
Add DNS Provider for Domain Offensive (do.de)

### LINKED ISSUE #834: Support "Domain Offensive" (do.de) provider
I'm working with German https://do.de provider who is offering a simple API for updating TXT records. That API is usable by either the `exec` provider or could get its own provider,  much similar to duckduckdns.

Would a contribution for a dedicated do.de provider be of interest and potentially gain acceptance?

https://www.do.de/wiki/LetsEncrypt_-_Entwickler

### PR DESCRIPTION
**Pull request by andig**
Fixes #834. The code is a modified copy of the DuckDNS provider.

Looking at the PR now I'm not entirely sure if `DODE` (and the `do.de:`) error messages are good enough or if it shouldn't rather be the lengthier `DOMAINOFFENSIVE` (plug package name and error messages?). Please let me know if this needs changing.

### CODE REVIEW

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:
- [x] add a description to your PR
- [x] be able to maintain this provider
- [x] have a homogeneous design with the other providers
- [x] add tests ("live" and units)
```shell
make test
```
- [ ] add the provider to the [readme.md](https://github.com/xenolf/lego#dns-providers)
- [x] add a [provider descriptor](https://github.com/xenolf/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help and documentation
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf ./lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [x] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```

**Comment by andig** [comment]
I‘ll update the readme and show command output. It might make sense to get confirmation from the provider that they intent to maintain this api? I‘ll also try to achieve that.

**Comment by ldez** [comment]
> It might make sense to get confirmation from the provider that they intent to maintain this api?

No, we only need you to maintain the implementation.

**Comment by andig** [comment]
Feels I'm doing this wrong, but provider doesn't like the example domains:

    ~/go/src/github.com/go-acme/lego dode ⇣
    ❯ rm -rf .lego

    ~/go/src/github.com/go-acme/lego dode ⇣
    ❯ DODE_TOKEN=<token> go run ./cmd/lego --dns dode -m cpuidle@gmx.de -d '*.example.com' -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
    2019/03/21 09:49:56 No key found for account cpuidle@gmx.de. Generating a P384 key.
    2019/03/21 09:49:56 Saved key to /Users/andig/go/src/github.com/go-acme/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/cpuidle@gmx.de/keys/cpuidle@gmx.de.key
    2019/03/21 09:49:59 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
    Do you accept the TOS? Y/n

    2019/03/21 09:50:01 [INFO] acme: Registering account for cpuidle@gmx.de
    !!!! HEADS UP !!!!

                    Your account credentials have been saved in your Let's Encrypt
                    configuration directory at "/Users/andig/go/src/github.com/go-acme/lego/.lego/accounts".
                    You should make a secure backup of this folder now. This
                    configuration directory will also contain certificates and
                    private keys obtained from Let's Encrypt so making regular
                    backups of this folder is ideal.2019/03/21 09:50:02 [INFO] [*.example.com, example.com] acme: Obtaining bundled SAN certificate
    2019/03/21 09:50:04 [INFO] [*.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/cOtu8eknTiGHXnTZyRggQmq1kYHLBZWtq01TQJaFYto
    2019/03/21 09:50:04 [INFO] [example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/vn4FFyyzB5LYi4snHfeahITeVTjLsWENrfqc8lH5OkM
    2019/03/21 09:50:04 [INFO] [*.example.com] acme: use dns-01 solver
    2019/03/21 09:50:04 [INFO] [example.com] acme: Could not find solver for: tls-alpn-01
    2019/03/21 09:50:04 [INFO] [example.com] acme: Could not find solver for: http-01
    2019/03/21 09:50:04 [INFO] [example.com] acme: use dns-01 solver
    2019/03/21 09:50:04 [INFO] [*.example.com] acme: Preparing to solve DNS-01
    2019/03/21 09:50:04 [INFO] [*.example.com] acme: Cleaning DNS-01 challenge
    2019/03/21 09:50:04 [WARN] [*.example.com] acme: error cleaning up: request to change TXT record for do.de returned the following error result ({
        "error": "domain not found"
    }); used url [https://www.do.de/api/letsencrypt?action=delete&domain=_acme-challenge.example.com&token=<token>]
    2019/03/21 09:50:04 [INFO] [example.com] acme: Preparing to solve DNS-01
    2019/03/21 09:50:04 [INFO] [example.com] acme: Cleaning DNS-01 challenge
    2019/03/21 09:50:04 [WARN] [example.com] acme: error cleaning up: request to change TXT record for do.de returned the following error result ({
        "error": "domain not found"
    }); used url [https://www.do.de/api/letsencrypt?action=delete&domain=_acme-challenge.example.com&token=<token>]
    2019/03/21 09:50:04 Could not obtain certificates:
            acme: Error -> One or more domains had a problem:
    [*.example.com] [*.example.com] acme: error presenting token: request to change TXT record for do.de returned the following error result ({
        "error": "domain not found"
    }); used url [https://www.do.de/api/letsencrypt?domain=_acme-challenge.example.com&token=<token>&value=wOKoCkNfyBia342tEzhZP9dHkMmAEYvHoN10450QLcM]
    [example.com] [example.com] acme: error presenting token: request to change TXT record for do.de returned the following error result ({
        "error": "domain not found"
    }); used url [https://www.do.de/api/letsencrypt?domain=_acme-challenge.example.com&token=<token>&value=A1UoPBacIR-eTg3ShHRhYb-trtAzfbd-9k8qwP45T6s]
    exit status 1

Is that fault on side of the do.de API?

If I run it without token (as requested), the provider gives the (expected) error:

    2019/03/21 09:54:34 do.de: some credentials information are missing: DODE_TOKEN

**Comment by ldez** [comment]
@andig you have to use a real domain instead of `example.com`

**Comment by andig** [comment]
Sorry for the confusion. I was assuming `example.com` was some wildcard DNS thing. Here we go:

    ❯ rm -rf .lego
    ❯ DODE_TOKEN=<token> go run ./cmd/lego --dns dode -m cpuidle@gmx.de -d '*.xn--gtz-sna' -d xn--gtz-sna -s https://acme-staging-v02.api.letsencrypt.org/directory run
    2019/03/21 11:44:01 No key found for account cpuidle@gmx.de. Generating a P384 key.
    2019/03/21 11:44:01 Saved key to /Users/andig/go/src/github.com/go-acme/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/cpuidle@gmx.de/keys/cpuidle@gmx.de.key
    2019/03/21 11:44:02 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
    Do you accept the TOS? Y/n

    2019/03/21 11:44:04 [INFO] acme: Registering account for cpuidle@gmx.de
    !!!! HEADS UP !!!!

                    Your account credentials have been saved in your Let's Encrypt
                    configuration directory at "/Users/andig/go/src/github.com/go-acme/lego/.lego/accounts".
                    You should make a secure backup of this folder now. This
                    configuration directory will also contain certificates and
                    private keys obtained from Let's Encrypt so making regular
                    backups of this folder is ideal.2019/03/21 11:44:05 [INFO] [*.xn--gtz-sna, xn--gtz-sna] acme: Obtaining bundled SAN certificate
    2019/03/21 11:44:25 [INFO] [*.xn--gtz-sna.it, xn--gtz-sna.it] acme: Obtaining bundled SAN certificate
    2019/03/21 11:44:26 [INFO] [*.xn--gtz-sna.it] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/WeYeTkncacifrmYdSiFcGOfu5M2UabUsxvaqLEUS7EM
    2019/03/21 11:44:26 [INFO] [xn--gtz-sna.it] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/RTeN_NnhgbEscpniNu2y0xc1CwJOiCUY0yC2PdfZzRY
    2019/03/21 11:44:26 [INFO] [*.xn--gtz-sna.it] acme: use dns-01 solver
    2019/03/21 11:44:26 [INFO] [xn--gtz-sna.it] acme: Could not find solver for: tls-alpn-01
    2019/03/21 11:44:26 [INFO] [xn--gtz-sna.it] acme: Could not find solver for: http-01
    2019/03/21 11:44:26 [INFO] [xn--gtz-sna.it] acme: use dns-01 solver
    2019/03/21 11:44:26 [INFO] [*.xn--gtz-sna.it] acme: Preparing to solve DNS-01
    2019/03/21 11:44:27 [INFO] [*.xn--gtz-sna.it] acme: Trying to solve DNS-01
    2019/03/21 11:44:27 [INFO] [*.xn--gtz-sna.it] acme: Checking DNS record propagation using [192.168.0.1:53]
    2019/03/21 11:44:27 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
    2019/03/21 11:44:35 [INFO] [*.xn--gtz-sna.it] The server validated our request
    2019/03/21 11:44:35 [INFO] [*.xn--gtz-sna.it] acme: Cleaning DNS-01 challenge
    2019/03/21 11:44:36 [INFO] sequence: wait for 1m0s
    2019/03/21 11:45:36 [INFO] [xn--gtz-sna.it] acme: Preparing to solve DNS-01
    2019/03/21 11:45:36 [INFO] [xn--gtz-sna.it] acme: Trying to solve DNS-01
    2019/03/21 11:45:36 [INFO] [xn--gtz-sna.it] acme: Checking DNS record propagation using [192.168.0.1:53]
    2019/03/21 11:45:36 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
    2019/03/21 11:45:45 [INFO] [xn--gtz-sna.it] The server validated our request
    2019/03/21 11:45:45 [INFO] [xn--gtz-sna.it] acme: Cleaning DNS-01 challenge
    2019/03/21 11:45:45 [INFO] [*.xn--gtz-sna.it, xn--gtz-sna.it] acme: Validations succeeded; requesting certificates
    2019/03/21 11:45:47 [INFO] [*.xn--gtz-sna.it] Server responded with a certificate.

**Pull request merged**
