### PR TITLE
azuredns: servicediscovery for zones

### LINKED ISSUE #2131: azure: find zones via serviceDiscovery (or allow multiple values for AZURE_RESOURCE_GROUP)
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Docker image

### Detailed Description

Sometimes DNS zones are inside multiple Azure ResourceGroups.

One solution could be to find available Zones via Azure REST API or ResourceGraph Query based on a list of ResourceGroups before using them as a kind of lookup.

Same could be done for subscription IDs or to have the possibility to leave both empty and try to find the zones via ResourceGraph based on roleAssignment visibility.

possible resourcegraph query:

```
resources
| where type =~ "microsoft.network/dnszones"
| project id, subscriptionId, resourceGroup, name
```

### PR DESCRIPTION
**Pull request by mblaschke**
using ResourceGraph to lookup available Azure DNS zones and makes SubscriptionID and ResourceGroup optional

adds env var `AZURE_SERVICEDISCOVERY_FILTER` for advanced kusto query filter (can be a `where` or any additional subquery)

Closes #2131

todo:
- [x] documentation

### CODE REVIEW

**Comment by ldez** [comment]
@pchanvallon can you check if the PR works?

I will do the code review after.

**Comment by pchanvallon** [comment]
Hello @ldez, @mblaschke,

I've tested the following configurations :  
* with `AZURE_SUBSCRIPTION_ID` and `AZURE_RESOURCE_GROUP` variable set
* without `AZURE_SUBSCRIPTION_ID` and `AZURE_RESOURCE_GROUP` variable set
* with RBAC on only one zone 
* with RBAC on both
* with tag filter on only one zone
* with tag filter on both

... and everything worked as expected 👍

**Comment by ldez** [comment]
Waiting for the documentation (`azuredns.toml`)

**Comment by mblaschke** [comment]
@ldez 
done

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
