### PR TITLE
support for ipaddress in SAN

### PR DESCRIPTION
**Pull request by orangepizza**
a tiny edits on few functions that adapt type of identifier/ SAN type if input 'domain' can be parsed as IP address.
not bothered to change name of variable []domains to some better name: kind don't want to follow all those function calls to pass full identifier 

test on pebble that this is enough for ipv4 and ipv6 in -d.

### CODE REVIEW

**Comment by ldez** [comment]
Related to #1649

**Comment by orangepizza** [comment]
while I creating tls-alpn testing I found that current tls-alpn test creating wrong testing certificate (SAN DNSname included port number in it, moke verifier had same error too (not triming port number in domain fro localhost:23578 so test passed. this only happends only in test as problem was sending wrong name to auth - otherwise TLS-ALPN client would be broken

**Comment by ldez** [comment]
Hello,

do you plan to recreate a PR based on your new branch? https://github.com/orangepizza/lego/tree/ipaddr

**Comment by orangepizza** [comment]
yes I already did : look #1838

**Pull request closed without merging**
