### PR TITLE
chore: add snap to release packages

### PR DESCRIPTION
**Pull request by gruyaume**
# Description

The LEGO snap makes it easy to install and use LEGO on any Linux distribution that supports snaps. This PR adds the snap to go releaser to automatically build and publish the snap. 

## Usage

```bash
sudo snap install lego
sudo lego \
  --email="you@example.com" \
  --domains="example.com" \
  --server=https://acme-staging-v02.api.letsencrypt.org/directory \
  --http \
  --http.port :8080 \
  run
```

**Note**: The LEGO snap can only write to the `/var/snap/lego/common/.lego` directory.

## Confinement

The snap is strictly confined, meaning it only has access to what it requires to work and for LEGO that means [network binding](https://snapcraft.io/docs/network-bind-interface). 

## Snap publishing

For the snap publishing to succeed, it will be necessary to do the following before merging this PR:
1. Create a snapcraft account
2. Make a request in the [snapcraft forum](https://forum.snapcraft.io/c/store-requests/) to have the ownership of the `lego` snap name switched from myself to this new account. I can make the request myself once we have step 1 completed. 
3. Generate a snapcraft login token attached to this specific snap with a reasonable ttl
4. Place this token in a GitHub secret named `SNAPCRAFT_STORE_CREDENTIALS`

Once all of those are completed, I will move the PR from draft to live.

## Channel

With the current state of the change proposed here, the snap will be automatically published to the `edge` channel. This means that promotion from edge -> beta -> candidate -> stable would have to be done manually through the Snapcraft UI.

Related to https://github.com/go-acme/lego/discussions/2133

### CODE REVIEW

**Comment by ldez** [comment]
I already have a Snapcraft account: ldez

**Comment by gruyaume** [comment]
> I already have a Snapcraft account: ldez But I don't have Snapcraft forum login.

Ok, I just made the request:
- https://forum.snapcraft.io/t/transfer-ownership-of-lego-charm/39267

**Comment by ldez** [comment]
Before the transfer can you add the v4.16.0 to the current snap?

**Comment by gruyaume** [comment]
> Before the transfer can you add the v4.16.0 to the current snap?

Done!

**Comment by ldez** [comment]
My email is:

**Comment by ldez** [comment]
I accepted the invitation

**Comment by gruyaume** [comment]
@ldez The transfer is complete

**Comment by ldez** [comment]
I can't find the Snapcraft token inside my Snapcraft account, where is it?

**Comment by gruyaume** [comment]
> I can't find the Snapcraft token inside my Snapcraft account, where is it?

You will have to generate one for yourself via snapcraft CLI:
- https://snapcraft.io/docs/snapcraft-authentication

**Comment by ldez** [comment]
It's unexpected to be forced to install a CLI to generate a token, but :shrug:

**Comment by ldez** [comment]
I added the token to the secrets.

**Comment by gruyaume** [comment]
> It's unexpected to be forced to install a CLI to generate a token, but 🤷

Well the token is used by the CLI, you are "forced" to install the cli to use the token as well...

**Comment by ldez** [comment]
Everything is ok? Ready for review?

**Comment by gruyaume** [comment]
> Everything is ok? Ready for review?

I think so, but it's hard to test the PR without running the release.

**Comment by ldez** [comment]
We will see with the next release :smile:

**Review by ldez — APPROVED** [review]
LGTM

**Comment by ldez** [comment]
The release fails:

```
Run snapcraft login
  snapcraft login
  shell: /usr/bin/bash -e {0}
  env:
    GO_VERSION: stable
    CGO_ENABLED: 0
    SNAPCRAFT_STORE_CREDENTIALS: ***
Cannot login with 'SNAPCRAFT_STORE_CREDENTIALS' set.
Recommended resolution: Unset 'SNAPCRAFT_STORE_CREDENTIALS' and try again.
Full execution log: '/home/runner/.local/state/snapcraft/log/snapcraft-20240528-105206.532861.log'
Error: Process completed with exit code 1.
```


https://github.com/go-acme/lego/actions/runs/9267967862/job/25495567069

**Pull request merged**
