### PR TITLE
Add Akamai Edgedns. Deprecate FastDNS

### PR DESCRIPTION
**Pull request by edglynes**
Add support for Akamai EdgeDNS. Deprecate FastDNS.

EdgeDNS utilizes the AKAMAI v2 DNS API. The API is based on  recordsets, necessitating a sequential approach to challenges as TXT targets can have multiple values. 

This provider will be supported by Akamai. Contact: elynes@akamai.com

### CODE REVIEW

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests (units)
```shell
make test
```
- [ ] add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help, documentation, and readme.
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`

**Comment by edglynes** [comment]
[elynes@RHEL02 lego]$ make generate-dns
go generate ./...
Documentation for 79 DNS providers has been generated.


[elynes@RHEL02 lego]$ make test
BIN_OUTPUT: dist/lego
rm -rf dist/ builds/ cover.out
go test -v -cover ./...

...

=== RUN   TestNewDNSProvider
=== RUN   TestNewDNSProvider/success
=== RUN   TestNewDNSProvider/missing_credentials
=== RUN   TestNewDNSProvider/missing_host
=== RUN   TestNewDNSProvider/missing_client_token
=== RUN   TestNewDNSProvider/missing_client_secret
=== RUN   TestNewDNSProvider/missing_access_token
--- PASS: TestNewDNSProvider (0.00s)
    --- PASS: TestNewDNSProvider/success (0.00s)
    --- PASS: TestNewDNSProvider/missing_credentials (0.00s)
    --- PASS: TestNewDNSProvider/missing_host (0.00s)
    --- PASS: TestNewDNSProvider/missing_client_token (0.00s)
    --- PASS: TestNewDNSProvider/missing_client_secret (0.00s)
    --- PASS: TestNewDNSProvider/missing_access_token (0.00s)
=== RUN   TestNewDNSProviderConfig
=== RUN   TestNewDNSProviderConfig/success
=== RUN   TestNewDNSProviderConfig/missing_credentials
=== RUN   TestNewDNSProviderConfig/missing_host
=== RUN   TestNewDNSProviderConfig/missing_client_token
=== RUN   TestNewDNSProviderConfig/missing_client_secret
=== RUN   TestNewDNSProviderConfig/missing_access_token
--- PASS: TestNewDNSProviderConfig (0.00s)
    --- PASS: TestNewDNSProviderConfig/success (0.00s)
    --- PASS: TestNewDNSProviderConfig/missing_credentials (0.00s)
    --- PASS: TestNewDNSProviderConfig/missing_host (0.00s)
    --- PASS: TestNewDNSProviderConfig/missing_client_token (0.00s)
    --- PASS: TestNewDNSProviderConfig/missing_client_secret (0.00s)
    --- PASS: TestNewDNSProviderConfig/missing_access_token (0.00s)
=== RUN   TestDNSProvider_findZoneAndRecordName
=== RUN   TestDNSProvider_findZoneAndRecordName/Extract_root_record_name
=== PAUSE TestDNSProvider_findZoneAndRecordName/Extract_root_record_name
=== RUN   TestDNSProvider_findZoneAndRecordName/Extract_sub_record_name
=== PAUSE TestDNSProvider_findZoneAndRecordName/Extract_sub_record_name
=== CONT  TestDNSProvider_findZoneAndRecordName/Extract_root_record_name
=== CONT  TestDNSProvider_findZoneAndRecordName/Extract_sub_record_name
--- PASS: TestDNSProvider_findZoneAndRecordName (0.00s)
    --- PASS: TestDNSProvider_findZoneAndRecordName/Extract_root_record_name (0.26s)
    --- PASS: TestDNSProvider_findZoneAndRecordName/Extract_sub_record_name (0.60s)
=== RUN   TestLivePresent
    TestLivePresent: edgedns_test.go:239: skipping live test
--- SKIP: TestLivePresent (0.00s)
=== RUN   TestLiveCleanUp
    TestLiveCleanUp: edgedns_test.go:256: skipping live test
--- SKIP: TestLiveCleanUp (0.00s)
PASS
coverage: 23.4% of statements
ok  	github.com/go-acme/lego/v3/providers/dns/edgedns	0.868s	coverage: 23.4% of statements

**Comment by edglynes** [comment]
[elynes@RHEL02 lego]$ rm -rf .lego
[elynes@RHEL02 lego]$ dist/lego --server=https://acme-staging-v02.api.letsencrypt.org/directory --domains=*.edgedns.zone --domains=edgedns.zone --email="elynes@akamai.com" --dns="edgedns" -a run
2020/07/06 08:38:40 No key found for account elynes@akamai.com. Generating a P384 key.
2020/07/06 08:38:41 Saved key to /workdev/src/github.com/edglynes/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/elynes@akamai.com/keys/elynes@akamai.com.key
2020/07/06 08:38:41 [INFO] acme: Registering account for elynes@akamai.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/workdev/src/github.com/edglynes/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2020/07/06 08:38:41 [INFO] [*.edgedns.zone, edgedns.zone] acme: Obtaining bundled SAN certificate
2020/07/06 08:38:42 [INFO] [*.edgedns.zone] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/73112143
2020/07/06 08:38:42 [INFO] [edgedns.zone] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/73112144
2020/07/06 08:38:42 [INFO] [*.edgedns.zone] acme: use dns-01 solver
2020/07/06 08:38:42 [INFO] [edgedns.zone] acme: Could not find solver for: tls-alpn-01
2020/07/06 08:38:42 [INFO] [edgedns.zone] acme: Could not find solver for: http-01
2020/07/06 08:38:42 [INFO] [edgedns.zone] acme: use dns-01 solver
2020/07/06 08:38:42 [INFO] [*.edgedns.zone] acme: Preparing to solve DNS-01
2020/07/06 08:38:45 [INFO] [*.edgedns.zone] acme: Trying to solve DNS-01
2020/07/06 08:38:45 [INFO] [*.edgedns.zone] acme: Checking DNS record propagation using [10.0.2.2:53]
2020/07/06 08:39:15 [INFO] Wait for propagation [timeout: 5m0s, interval: 30s]
2020/07/06 08:39:16 [INFO] [*.edgedns.zone] acme: Waiting for DNS record propagation.
2020/07/06 08:39:47 [INFO] [*.edgedns.zone] acme: Waiting for DNS record propagation.
2020/07/06 08:40:24 [INFO] [*.edgedns.zone] The server validated our request
2020/07/06 08:40:24 [INFO] [*.edgedns.zone] acme: Cleaning DNS-01 challenge
2020/07/06 08:40:26 [INFO] [DEBUG] Deleting TxtRecord
2020/07/06 08:40:26 [INFO] sequence: wait for 5m0s
2020/07/06 08:45:26 [INFO] [edgedns.zone] acme: Preparing to solve DNS-01
2020/07/06 08:45:29 [INFO] [edgedns.zone] acme: Trying to solve DNS-01
2020/07/06 08:45:29 [INFO] [edgedns.zone] acme: Checking DNS record propagation using [10.0.2.2:53]
2020/07/06 08:45:59 [INFO] Wait for propagation [timeout: 5m0s, interval: 30s]
2020/07/06 08:46:00 [INFO] [edgedns.zone] acme: Waiting for DNS record propagation.
2020/07/06 08:46:33 [INFO] [edgedns.zone] acme: Waiting for DNS record propagation.
2020/07/06 08:47:10 [INFO] [edgedns.zone] The server validated our request
2020/07/06 08:47:10 [INFO] [edgedns.zone] acme: Cleaning DNS-01 challenge
2020/07/06 08:47:12 [INFO] [DEBUG] Deleting TxtRecord
2020/07/06 08:47:13 [INFO] [*.edgedns.zone, edgedns.zone] acme: Validations succeeded; requesting certificates
2020/07/06 08:47:13 [INFO] [*.edgedns.zone] Server responded with a certificate.
[elynes@RHEL02 lego]$ 

elynes@RHEL02 lego]$ make
BIN_OUTPUT: dist/lego
rm -rf dist/ builds/ cover.out
go generate ./...
Documentation for 79 DNS providers has been generated.
golangci-lint run
go test -v -cover ./...

**Comment by ldez** [comment]
> The API is based on recordsets, necessitating a sequential approach to challenges as TXT targets can have multiple values.

The sequential approach is for DNS providers that don't support multiples TXT records for one domain.
This approach is lower than the "parallel" approach.

I don't think that you need it in your case.

**Comment by edglynes** [comment]
I couldn’t find a way to make the required test case, “-d *.example.zone -d example.zone” to run correctly with out it. The challenges run in parallel so the same txt record name is used concurrently by each go routine. I figured out how to manage the creation, updates and removal of the txt record, however, the auth check to the Lego server fails because it has BOTH values.

Th failure is at https://github.com/go-acme/lego/blob/master/challenge/resolver/solver_manager.go#L115

The ACME server can’t handle record sets (with multiple values) when dealing with keys. Can you help me track down further? I can provide additional debug info but I tore thru the lego
Pretty deeply and found nowhere I could catch and correct.

E.g.

[elynes@RHEL02 lego]$ dist/lego --server=https://acme-staging-v02.api.letsencrypt.org/directory --domains="edgedns.zone" --email="elynes@akamai.com" --dns="edgedns" --dns.disable-cp=true -a run
2020/06/26 10:36:07 [INFO] [edgedns.zone] acme: Obtaining bundled SAN certificate
2020/06/26 10:36:07 [INFO] [edgedns.zone] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/68973572
2020/06/26 10:36:07 [INFO] [edgedns.zone] acme: Could not find solver for: tls-alpn-01
2020/06/26 10:36:07 [INFO] [edgedns.zone] acme: Could not find solver for: http-01
2020/06/26 10:36:07 [INFO] [edgedns.zone] acme: use dns-01 solver
2020/06/26 10:36:07 [INFO] [edgedns.zone] acme: Preparing to solve DNS-01
2020/06/26 10:36:10 [INFO] [edgedns.zone] acme: Trying to solve DNS-01
2020/06/26 10:36:10 [INFO] [edgedns.zone] acme: Checking DNS record propagation using [10.0.2.2:53]
2020/06/26 10:36:10 [INFO] [Challenge]: &{0xc0001bc000 0x806c90 0xc00000e1b8 {<nil> false} 10000000000}
2020/06/26 10:36:10 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2020/06/26 10:36:10 [INFO] DEBUG: dbsQuery. fqdn: _acme-challenge.edgedns.zone., recursiveNS: [10.0.2.2:53]
2020/06/26 10:36:16 [INFO] [edgedns.zone] acme: Cleaning DNS-01 challenge
2020/06/26 10:36:17 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/68973572
2020/06/26 10:36:17 [INFO] Unable to deactivate the authorization: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/68973572
2020/06/26 10:36:17 Could not obtain certificates:
              error: one or more domains had a problem:
[edgedns.zone] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.edgedns.zone - check that a DNS record exists for this domain, url:

Ed

**Comment by edglynes** [comment]
I couldn’t find a way to make the required test case, “-d *.example.zone -d example.zone” to run correctly with out it. The challenges run in parallel so the same txt record name is used concurrently by each go routine. I figured out how to manage the creation, updates and removal of the txt record, however, the auth check to the Lego server fails because it has BOTH values.

Th failure is at https://github.com/go-acme/lego/blob/master/challenge/resolver/solver_manager.go#L115

The ACME server can’t handle record sets (with multiple values) when dealing with keys. Can you help me track down further? I can provide additional debug info but I tore thru the lego 
Pretty deeply and found nowhere I could catch and correct.

E.g.

[elynes@RHEL02 lego]$ dist/lego --server=https://acme-staging-v02.api.letsencrypt.org/directory --domains="edgedns.zone" --email="elynes@akamai.com" --dns="edgedns" --dns.disable-cp=true -a run
2020/06/26 10:36:07 [INFO] [edgedns.zone] acme: Obtaining bundled SAN certificate
2020/06/26 10:36:07 [INFO] [edgedns.zone] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/68973572
2020/06/26 10:36:07 [INFO] [edgedns.zone] acme: Could not find solver for: tls-alpn-01
2020/06/26 10:36:07 [INFO] [edgedns.zone] acme: Could not find solver for: http-01
2020/06/26 10:36:07 [INFO] [edgedns.zone] acme: use dns-01 solver
2020/06/26 10:36:07 [INFO] [edgedns.zone] acme: Preparing to solve DNS-01
2020/06/26 10:36:10 [INFO] [edgedns.zone] acme: Trying to solve DNS-01
2020/06/26 10:36:10 [INFO] [edgedns.zone] acme: Checking DNS record propagation using [10.0.2.2:53]
2020/06/26 10:36:10 [INFO] [Challenge]: &{0xc0001bc000 0x806c90 0xc00000e1b8 {<nil> false} 10000000000}
2020/06/26 10:36:10 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2020/06/26 10:36:10 [INFO] DEBUG: dbsQuery. fqdn: _acme-challenge.edgedns.zone., recursiveNS: [10.0.2.2:53]
2020/06/26 10:36:16 [INFO] [edgedns.zone] acme: Cleaning DNS-01 challenge
2020/06/26 10:36:17 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/68973572
2020/06/26 10:36:17 [INFO] Unable to deactivate the authorization: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/68973572
2020/06/26 10:36:17 Could not obtain certificates:
              error: one or more domains had a problem:
[edgedns.zone] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.edgedns.zone - check that a DNS record exists for this domain, url:

Ed

**Comment by ldez** [comment]
> The challenges run in parallel so the same txt record name is used concurrently by each go routine

`parallel`, in the case of a challenge in lego, don't mean "go routine".

> The ACME server can’t handle record sets (with multiple values) when dealing with keys.

The LE server **can** handle record sets (with multiple values).

---

I will help you, I just need a time to review this implement and check the API client behavior.

**Comment by ldez** [comment]
Could you explain why you are trying to put all the TXT records in only one entry of the `rdata`?

If I understand the [doc](https://developer.akamai.com/api/cloud_security/edge_dns_zone_management/v2.html#recordset), `rdata` is a slice/array of value, those values must be surrounded by `"`.

So for me you can put one TXT records by entry:
```json
{
  "rdata": [
    "\"val01\"",
    "\"val02\"",
    "\"val03\""
  ]
}
```

**Comment by edglynes** [comment]
The Edgedns is a little quirky. It doesn’t deal with embedded quotes well currently. There is an internal Akamai bug against it but not fixed yet. I figured given that, it was just as easy to manage in one slice entry. Do you think the Lego client and Auth servers will behave better with separate slice entries? I can try that.  The logic in the fore loop at https://github.com/go-acme/lego/blob/master/challenge/dns01/precheck.go#L111 will need to be modified to deal with a slice with multiple entries.

Ed

**Comment by edglynes** [comment]
The Edgedns API is a little quirky. It doesn’t deal with embedded quotes well currently. There is an internal Akamai bug against it but not fixed yet. I figured given that, it was just as easy to manage in one slice entry. Do you think the Lego client and Auth servers will behave better with separate slice entries? I can try that.  The logic in the fore loop at https://github.com/go-acme/lego/blob/master/challenge/dns01/precheck.go#L111 will need to be modified to deal with a slice with multiple entries.

Ed

**Comment by ldez** [comment]
> The logic in the for loop at https://github.com/go-acme/lego/blob/master/challenge/dns01/precheck.go#L111 will need to be modified to deal with a slice with multiple entries.

You don't have to change the core code, there are already some DNS provider that use rset without any issue.

**Comment by edglynes** [comment]
Ok, I'll go back and refector the logic to use multiple slice entries and see if that makes a difference. Can I assume all entries in a single slice entry will not work [ever]

**Comment by ldez** [comment]
I created a quick implementation:

<details>
<summary>sample</summary>

```go

// Present creates a TXT record to fulfill the dns-01 challenge.
func (d *DNSProvider) Present(domain, token, keyAuth string) error {
	fqdn, value := dns01.GetRecord(domain, keyAuth)

	zoneName, recordName, err := findZoneAndRecordName(fqdn, domain)
	if err != nil {
		return fmt.Errorf("edgedns: %w", err)
	}

	recordName = recordName + "." + zoneName

	record, err := configdns.GetRecord(zoneName, recordName, "TXT")
	if err != nil &&
		!configdns.IsConfigDNSError(err) || !err.(configdns.ConfigDNSError).NotFound() {
		return fmt.Errorf("edgedns: %w", err)
	}

	if record != nil {
		log.Infof("TXT record already exists. Updating target")

		if len(record.Target) == 0 {
			return fmt.Errorf("TXT record is invalid")
		}

		if containsValue(record.Target, value) {
			// have a record and have entry already
			return nil
		}

		record.Target = append(record.Target, `"`+value+`"`)
		record.TTL = d.config.TTL

		err = record.Update(zoneName)
		if err != nil {
			return fmt.Errorf("edgedns: %w", err)
		}

		return nil
	}

	record = &configdns.RecordBody{
		Name:       recordName,
		RecordType: "TXT",
		TTL:        d.config.TTL,
		Target:     []string{`"` + value + `"`},
	}

	err = record.Save(zoneName)
	if err != nil {
		return fmt.Errorf("edgedns: %w", err)
	}

	return nil
}

// CleanUp removes the record matching the specified parameters.
func (d *DNSProvider) CleanUp(domain, token, keyAuth string) error {
	fqdn, value := dns01.GetRecord(domain, keyAuth)

	zoneName, recordName, err := findZoneAndRecordName(fqdn, domain)
	if err != nil {
		return fmt.Errorf("edgedns: %w", err)
	}

	recordName = recordName + "." + zoneName

	existingRec, err := configdns.GetRecord(zoneName, recordName, "TXT")
	if err != nil {
		if cde, ok := err.(configdns.ConfigDNSError); ok && cde.NotFound() {
			return nil
		}

		return fmt.Errorf("edgedns: %w", err)
	}

	if existingRec == nil {
		return nil
	}

	if len(existingRec.Target) == 0 {
		return fmt.Errorf("edgedns: TXT record is invalid")
	}

	if !containsValue(existingRec.Target, value) {
		return nil
	}

	var newRData []string
	for _, val := range existingRec.Target {
		newRData = append(newRData, val)
	}

	if len(newRData) > 0 {
		existingRec.Target = newRData

		err = existingRec.Update(zoneName)
		if err != nil {
			return fmt.Errorf("edgedns: %w", err)
		}
	}

	err = existingRec.Delete(zoneName)
	if err != nil {
		return fmt.Errorf("edgedns: %w", err)
	}

	return nil
}

func findZoneAndRecordName(fqdn, domain string) (string, string, error) {
	zone, err := dns01.FindZoneByFqdn(dns01.ToFqdn(domain))
	if err != nil {
		return "", "", err
	}

	zone = dns01.UnFqdn(zone)

	name := dns01.UnFqdn(fqdn)
	name = name[:len(name)-len("."+zone)]

	return zone, name, nil
}

func containsValue(values []string, value string) bool {
	for _, val := range values {
		if val == `""`+value+`""` {
			return true
		}
	}

	return false
}
```

</details>

I don't an Akamai account so I cannot test it.

**Comment by edglynes** [comment]
Thx. I'll review and test. I may need to add some addtl logic to work around the bug I mentioned prior. Might be a day or two.

**Comment by ldez** [comment]
after a second read of the doc, it seems you don't really need to add `"`, but it's not really clear to me.

**Comment by edglynes** [comment]
Refactored recordset processing. Supports asynchronous challenges.

BIN_OUTPUT: dist/lego
rm -rf dist/ builds/ cover.out
go generate ./...
Documentation for 79 DNS providers has been generated.
golangci-lint run
go test -v -cover ./...
?       github.com/go-acme/lego/v3/acme [no test files]

...
=== RUN   TestNewDNSProvider
=== RUN   TestNewDNSProvider/success
=== RUN   TestNewDNSProvider/missing_credentials
=== RUN   TestNewDNSProvider/missing_host
=== RUN   TestNewDNSProvider/missing_client_token
=== RUN   TestNewDNSProvider/missing_client_secret
=== RUN   TestNewDNSProvider/missing_access_token
--- PASS: TestNewDNSProvider (0.00s)
    --- PASS: TestNewDNSProvider/success (0.00s)
    --- PASS: TestNewDNSProvider/missing_credentials (0.00s)
    --- PASS: TestNewDNSProvider/missing_host (0.00s)
    --- PASS: TestNewDNSProvider/missing_client_token (0.00s)
    --- PASS: TestNewDNSProvider/missing_client_secret (0.00s)
    --- PASS: TestNewDNSProvider/missing_access_token (0.00s)
=== RUN   TestNewDNSProviderConfig
=== RUN   TestNewDNSProviderConfig/success
=== RUN   TestNewDNSProviderConfig/missing_credentials
=== RUN   TestNewDNSProviderConfig/missing_host
=== RUN   TestNewDNSProviderConfig/missing_client_token
=== RUN   TestNewDNSProviderConfig/missing_client_secret
=== RUN   TestNewDNSProviderConfig/missing_access_token
--- PASS: TestNewDNSProviderConfig (0.00s)
    --- PASS: TestNewDNSProviderConfig/success (0.00s)
    --- PASS: TestNewDNSProviderConfig/missing_credentials (0.00s)
    --- PASS: TestNewDNSProviderConfig/missing_host (0.00s)
    --- PASS: TestNewDNSProviderConfig/missing_client_token (0.00s)
    --- PASS: TestNewDNSProviderConfig/missing_client_secret (0.00s)
    --- PASS: TestNewDNSProviderConfig/missing_access_token (0.00s)
=== RUN   TestDNSProvider_findZoneAndRecordName
=== RUN   TestDNSProvider_findZoneAndRecordName/Extract_root_record_name
=== PAUSE TestDNSProvider_findZoneAndRecordName/Extract_root_record_name
=== RUN   TestDNSProvider_findZoneAndRecordName/Extract_sub_record_name
=== PAUSE TestDNSProvider_findZoneAndRecordName/Extract_sub_record_name
=== CONT  TestDNSProvider_findZoneAndRecordName/Extract_root_record_name
=== CONT  TestDNSProvider_findZoneAndRecordName/Extract_sub_record_name
--- PASS: TestDNSProvider_findZoneAndRecordName (0.00s)
    --- PASS: TestDNSProvider_findZoneAndRecordName/Extract_root_record_name (0.18s)
    --- PASS: TestDNSProvider_findZoneAndRecordName/Extract_sub_record_name (0.41s)
=== RUN   TestLivePresent
    TestLivePresent: edgedns_test.go:239: skipping live test
--- SKIP: TestLivePresent (0.00s)
=== RUN   TestLiveCleanUp
    TestLiveCleanUp: edgedns_test.go:256: skipping live test
--- SKIP: TestLiveCleanUp (0.00s)
PASS
coverage: 21.2% of statements
ok      github.com/go-acme/lego/v3/providers/dns/edgedns        0.601s  coverage: 21.2% of statements


[elynes@RHEL02 lego]$ dist/lego --server=https://acme-staging-v02.api.letsencrypt.org/directory --domains=*.edgedns.zone --domains=edgedns.zone --email="elynes@akamai.com" --dns="edgedns" -a run
2020/07/08 11:36:59 No key found for account elynes@akamai.com. Generating a P384 key.
2020/07/08 11:36:59 Saved key to /workdev/src/github.com/edglynes/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/elynes@akamai.com/keys/elynes@akamai.com.key
2020/07/08 11:36:59 [INFO] acme: Registering account for elynes@akamai.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/workdev/src/github.com/edglynes/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2020/07/08 11:37:00 [INFO] [*.edgedns.zone, edgedns.zone] acme: Obtaining bundled SAN certificate
2020/07/08 11:37:01 [INFO] [*.edgedns.zone] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/74307298
2020/07/08 11:37:01 [INFO] [edgedns.zone] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/74307299
2020/07/08 11:37:01 [INFO] [*.edgedns.zone] acme: use dns-01 solver
2020/07/08 11:37:01 [INFO] [edgedns.zone] acme: Could not find solver for: tls-alpn-01
2020/07/08 11:37:01 [INFO] [edgedns.zone] acme: Could not find solver for: http-01
2020/07/08 11:37:01 [INFO] [edgedns.zone] acme: use dns-01 solver
2020/07/08 11:37:01 [INFO] [*.edgedns.zone] acme: Preparing to solve DNS-01
2020/07/08 11:37:03 [INFO] [edgedns.zone] acme: Preparing to solve DNS-01
2020/07/08 11:37:04 [INFO] TXT record already exists. Updating target
2020/07/08 11:37:04 [INFO] [DEBUG] Update target: [["PJAXKYUQ0kGtpipeYx5AiTZx_-TZVVTBv-a-psrWK_4" "3PqLbgiR6_4k5y0KJMH0KhC9dF1yi4h9XwcvBbIFlcY"]]
2020/07/08 11:37:04 [INFO] [DEBUG] Updating TxtRecord: ["PJAXKYUQ0kGtpipeYx5AiTZx_-TZVVTBv-a-psrWK_4" "3PqLbgiR6_4k5y0KJMH0KhC9dF1yi4h9XwcvBbIFlcY"]
2020/07/08 11:37:05 [INFO] [*.edgedns.zone] acme: Trying to solve DNS-01
2020/07/08 11:37:05 [INFO] [*.edgedns.zone] acme: Checking DNS record propagation using [10.0.2.2:53]
2020/07/08 11:37:35 [INFO] Wait for propagation [timeout: 5m0s, interval: 30s]
2020/07/08 11:37:36 [INFO] [*.edgedns.zone] acme: Waiting for DNS record propagation.
2020/07/08 11:38:13 [INFO] [*.edgedns.zone] The server validated our request
2020/07/08 11:38:13 [INFO] [edgedns.zone] acme: Trying to solve DNS-01
2020/07/08 11:38:13 [INFO] [edgedns.zone] acme: Checking DNS record propagation using [10.0.2.2:53]
2020/07/08 11:38:43 [INFO] Wait for propagation [timeout: 5m0s, interval: 30s]
2020/07/08 11:38:51 [INFO] [edgedns.zone] The server validated our request
2020/07/08 11:38:51 [INFO] [*.edgedns.zone] acme: Cleaning DNS-01 challenge
2020/07/08 11:38:53 [INFO] [DEBUG] Updating TxtRecord: [3PqLbgiR6_4k5y0KJMH0KhC9dF1yi4h9XwcvBbIFlcY]
2020/07/08 11:38:55 [INFO] [edgedns.zone] acme: Cleaning DNS-01 challenge
2020/07/08 11:38:56 [INFO] [DEBUG] Deleting TxtRecord
2020/07/08 11:38:57 [INFO] [*.edgedns.zone, edgedns.zone] acme: Validations succeeded; requesting certificates
2020/07/08 11:38:57 [INFO] [*.edgedns.zone] Server responded with a certificate.
[elynes@RHEL02 lego]$

**Comment by edglynes** [comment]
@ldez  Thank you for all your help. Any sense of when 3.9.0 will be released?

**Comment by ldez** [comment]
We create a release after 10-20 PRs or after 1-2 months.

https://github.com/go-acme/lego/milestones?state=closed

**Pull request merged**
