### PR TITLE
dynu: fix subdomain support

### PR DESCRIPTION
**Pull request by SMHRambo**
Hi,

Fixes https://github.com/go-acme/lego/issues/1672

It should fix the subdomain issue.
Hope it helps.

### CODE REVIEW

**Review by SMHRambo — COMMENTED** [review]
I tested your code change but I get the error "dynu: could not find root domain".
I also tested it with a CNAME recorde, with the same result.
The old code accepted CNAME records without problems.
That being said, DYNU's API or the GetRootDomain function don't seem to like the dot at the end of the fqdn.
I'm not very good at reading go code, it's my second day with go.

**Comment by ldez** [comment]
Thank you for the feedback :+1: 

The old code wasn't working with CNAME, I'm 100% sure.
I think I have to trim the `_acme-challenge` prefix from the FQDN.

**Comment by ldez** [comment]
I changed the code, can you try it?

**Comment by SMHRambo** [comment]
The problem is the dot at the end.
I tested the code and added the string "_acme-challenge" before the domain without a problem.

**Comment by ldez** [comment]
So my latest change fixes the problem.

**Review by SMHRambo — COMMENTED** [review]
This is working!

**Review by ldez — APPROVED** [review]
Thank you :+1:

**Pull request merged**
