### PR TITLE
chore: update to go1.22

### PR DESCRIPTION
**Pull request by ldez**
- update linter to v1.57.0

https://tip.golang.org/doc/go1.22

### CODE REVIEW

**Review by dmke — APPROVED** [review]
LGTM

We should also update `docs/content/installation/_index.md` (which still mentions Go 1.17), as the new `range` semantics require 1.22+.

**Review by dmke — APPROVED** [review]

**Comment by iwind** [comment]
Is it realy worth to do this? it's a expensive decision, and gain less benifits.

**Comment by dmke** [comment]
Expensive in terms of... what exactly? I find the tests *much* easier to read and maintain without the line noise in `for`-loops.

Sure, we loose support for Go 1.21. But since Lego follows the Go support cycle (i.e. the only the current and previous Go releases are supported), and Go 1.23 is slated for release in August, we *could* have waited until then. Using 1.22 *now* however is not a huge ask.

**Comment by iwind** [comment]
To improve some (maybe 4-5) for loops, you forced thousands projects to upgrade their Go version to 1.22. Okay, maybe you are right, and everyone should and MUST fork the repository and change the go version in their go.mod file. It seems not a big problem, but it's still EXPENSIVE in my own opinion. 

And, at last, i sincerely  thank you for your work.

**Comment by dmke** [comment]
Again, not merging this PR now would have delayed the 1.22 upgrade only by a few months.

Also note that this commit is not yet part of any release. If you want to use the development version, you need to keep up with the project dependencies :)

**Comment by ldez** [comment]
> you forced thousands projects to upgrade their Go version to 1.22

Can you provide a list of those thousands projects?

Those thousands projects that use unreleased version of lego should think to sponsor lego if it's critical for them.

https://github.com/sponsors/ldez

**Pull request merged**
