### PR TITLE
Add DNS provider for Sonic

### PR DESCRIPTION
**Pull request by alexeiser**
Add support for SONIC as a DNS provider.

https://www.sonic.com/

### CODE REVIEW

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests (units)
```shell
make test
```
- [ ] add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help, documentation, and readme.
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`

**Comment by alexeiser** [comment]
Sample multi request & * request.
```
go run cmd/lego/main.go --email XXXXX@YYYY.com  --dns sonic  -d *.AAAA.example.com   -d AAAA.example.com    -s https://acme-staging-v02.api.letsencrypt.org/directory run 
2021/04/24 12:05:42 [INFO] [*.AAAA.example.com, AAAA.example.com] acme: Obtaining bundled SAN certificate
2021/04/24 12:05:44 [INFO] [*.AAAA.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/34183628
2021/04/24 12:05:44 [INFO] [AAAA.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/34183636
2021/04/24 12:05:44 [INFO] [*.AAAA.example.com] acme: use dns-01 solver
2021/04/24 12:05:44 [INFO] [AAAA.example.com] acme: Could not find solver for: tls-alpn-01
2021/04/24 12:05:44 [INFO] [AAAA.example.com] acme: Could not find solver for: http-01
2021/04/24 12:05:44 [INFO] [AAAA.example.com] acme: use dns-01 solver
2021/04/24 12:05:44 [INFO] [*.AAAA.example.com] acme: Preparing to solve DNS-01
2021/04/24 12:05:44 [INFO] [*.AAAA.example.com] acme: Trying to solve DNS-01
2021/04/24 12:05:44 [INFO] [*.AAAA.example.com] acme: Checking DNS record propagation using [192.168.120.1:53]
2021/04/24 12:05:46 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2021/04/24 12:05:52 [INFO] [*.AAAA.example.com] The server validated our request
2021/04/24 12:05:52 [INFO] [*.AAAA.example.com] acme: Cleaning DNS-01 challenge
2021/04/24 12:05:52 [INFO] sequence: wait for 1m0s
2021/04/24 12:06:52 [INFO] [AAAA.example.com] acme: Preparing to solve DNS-01
2021/04/24 12:06:52 [INFO] [AAAA.example.com] acme: Trying to solve DNS-01
2021/04/24 12:06:52 [INFO] [AAAA.example.com] acme: Checking DNS record propagation using [192.168.120.1:53]
2021/04/24 12:06:54 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2021/04/24 12:06:55 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:06:57 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:06:59 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:01 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:03 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:05 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:07 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:09 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:11 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:13 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:15 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:17 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:19 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:21 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:23 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:25 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:27 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:29 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:31 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:34 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:36 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:38 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:40 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:42 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:44 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:46 [INFO] [AAAA.example.com] acme: Waiting for DNS record propagation.
2021/04/24 12:07:50 [INFO] [AAAA.example.com] The server validated our request
2021/04/24 12:07:50 [INFO] [AAAA.example.com] acme: Cleaning DNS-01 challenge
2021/04/24 12:07:50 [INFO] [*.AAAA.example.com, AAAA.example.com] acme: Validations succeeded; requesting certificates
2021/04/24 12:07:51 [INFO] [*.AAAA.example.com] Server responded with a certificate.
```

**Comment by alexeiser** [comment]
> * [ ]  be able to maintain this provider
> * [ ]  have a homogeneous design with the other providers

How can I provide details with respect to these items.

**Comment by ldez** [comment]
> be able to maintain this provider

This means that you have to explain a bit who you are (a Sonic customer, a Sonic employee, ...).

**Comment by alexeiser** [comment]
> > be able to maintain this provider
> 
> This means that you have to explain a bit who you are (a Sonic customer, a Sonic employee, ...).

I am a Sonic customer - there has been an open request for them to provide an API for their DNS services for a couple of years. They finally added it.

**Comment by alexeiser** [comment]
Thanks for removing that insecure_https flag - copy paste fail.

Verified the updated diff still works well with actual API keys.

**Review by ldez — APPROVED** [review]
Thanks :+1:

**Pull request merged**
