### PR TITLE
Add DNS provider for HyperOne

### PR DESCRIPTION
**Pull request by kuskoman**
Adds integration with [HyperOne](https://www.hyperone.com/) provider.
E2e tests for this repo are currently available on my private namespace ([github.com/kuskoman/h1-lego-e2e](https://github.com/kuskoman/h1-lego-e2e)), if the PR gets merged they will be moved to [github.com/hyperonecom/h1-lego-e2e](https://github.com/hyperonecom/h1-lego-e2e).
Logs from obtaining certificates are can be found on [TravisCI](https://travis-ci.com/github/kuskoman/h1-lego-e2e/builds/).

### CODE REVIEW

**Comment by ad-m** [comment]
As a permanent collaborator of HyperOne, I would like to declare that we intend to keep this provider and treat it as officially available.

To this end, we intend to take steps to ensure the good condition of integration:
- daily - using the "master" branch from the "lego" repository - perform system tests (the relevant code of system tests mentioned earlier), which will confirm the permanent, correct operation of the integration,
- document the solution on the official HyperOne website, along with usage guides,
- provide HyperOne customers with information through other available channels, at the time of the release of the "Lego" library, about the possibility of using the new solution and the purpose of the "Lego" library
- respond in a reasonable time to any integration issues.

I would like to confirm that the integration was verified by HyperOne engineers, both responsible for the Platform API and DNS service development. They accepted the way of developing integration.

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests (units)
```shell
make test
```
- [ ] add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help, documentation, and readme.
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`

**Comment by ldez** [comment]
Otherwise, could you squash your commits, thanks.

**Comment by ldez** [comment]
After a quick review, the tests in https://github.com/kuskoman/h1-lego-e2e need to be updated to create a wildcard certificate for `*.jakub.dwa-skladniki.pl` and not `*.wildcard.jakub.dwa-skladniki.pl` (to be clear `-d jakub.dwa-skladniki.pl -d *.jakub.dwa-skladniki.pl`)

I will help you to fit our code requirements, but you have to squash your commits first and take a look to our checklist.

**Comment by ldez** [comment]
Could you squash and rebase instead of creating a merge commit, thanks.

I can help you on that if you want.

**Comment by kuskoman** [comment]
@ldez sorry, previously i used reset --soft instead of "real" rebase, should be good now.

> add tests ("live")

as far as i understand, the test you linked into your comment checks if provider is checking if all required environment variables are set, however there are no required env vars for HyperOne provider- instead we are using passport file generated using h1-cli

**Comment by ldez** [comment]
the "live" tests are not related to env vars but provide a way to test the methods `Cleanup` and `Present` in a real context.

**Comment by ldez** [comment]
I reviewed your PR and updated the code, if you have questions don't hesitate to ask me.

I created a test example in `providers/dns/hyperone/internal/client_test.go`, could update the fixture file with some more real values and add, at least, one test for each exported methods of the `Client`.

Thanks you.

**Comment by ldez** [comment]
Extract from [TravisCI](https://travis-ci.com/github/kuskoman/h1-lego-e2e/builds/181005948):

```
2020/08/23 16:35:23 No key found for account foo@bar.com. Generating a P384 key.
2020/08/23 16:35:23 Saved key to /lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/foo@bar.com/keys/foo@bar.com.key
2020/08/23 16:35:24 [INFO] acme: Registering account for foo@bar.com
!!!! HEADS UP !!!!
Your account credentials have been saved in your Let's Encrypt
configuration directory at "/lego/.lego/accounts".
You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2020/08/23 16:35:24 [INFO] [jakub.dwa-skladniki.pl, *.jakub.dwa-skladniki.pl] acme: Obtaining bundled SAN certificate
2020/08/23 16:35:26 [INFO] [*.jakub.dwa-skladniki.pl] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/98843980
2020/08/23 16:35:26 [INFO] [jakub.dwa-skladniki.pl] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/98843981
2020/08/23 16:35:26 [INFO] [*.jakub.dwa-skladniki.pl] acme: use dns-01 solver
2020/08/23 16:35:26 [INFO] [jakub.dwa-skladniki.pl] acme: Could not find solver for: tls-alpn-01
2020/08/23 16:35:26 [INFO] [jakub.dwa-skladniki.pl] acme: Could not find solver for: http-01
2020/08/23 16:35:26 [INFO] [jakub.dwa-skladniki.pl] acme: use dns-01 solver
2020/08/23 16:35:26 [INFO] [*.jakub.dwa-skladniki.pl] acme: Preparing to solve DNS-01
2020/08/23 16:35:29 [INFO] [jakub.dwa-skladniki.pl] acme: Preparing to solve DNS-01
2020/08/23 16:35:32 [INFO] [*.jakub.dwa-skladniki.pl] acme: Trying to solve DNS-01
2020/08/23 16:35:32 [INFO] [*.jakub.dwa-skladniki.pl] acme: Checking DNS record propagation using [ns-01.hyperone-dns.com:53]
2020/08/23 16:35:34 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2020/08/23 16:35:40 [INFO] [*.jakub.dwa-skladniki.pl] The server validated our request
2020/08/23 16:35:40 [INFO] [jakub.dwa-skladniki.pl] acme: Trying to solve DNS-01
2020/08/23 16:35:40 [INFO] [jakub.dwa-skladniki.pl] acme: Checking DNS record propagation using [ns-01.hyperone-dns.com:53]
2020/08/23 16:35:42 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2020/08/23 16:35:47 [INFO] [jakub.dwa-skladniki.pl] The server validated our request
2020/08/23 16:35:47 [INFO] [*.jakub.dwa-skladniki.pl] acme: Cleaning DNS-01 challenge
2020/08/23 16:35:50 [INFO] [jakub.dwa-skladniki.pl] acme: Cleaning DNS-01 challenge
2020/08/23 16:35:54 [INFO] [jakub.dwa-skladniki.pl, *.jakub.dwa-skladniki.pl] acme: Validations succeeded; requesting certificates
2020/08/23 16:35:55 [INFO] [jakub.dwa-skladniki.pl] Server responded with a certificate.
Successfully got certificate for jakub.dwa-skladniki.pl and *.jakub.dwa-skladniki.pl
2020/08/23 16:35:55 [INFO] [jakub2.dwa-skladniki.pl, *.jakub2.dwa-skladniki.pl] acme: Obtaining bundled SAN certificate
2020/08/23 16:35:56 [INFO] [*.jakub2.dwa-skladniki.pl] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/98844280
2020/08/23 16:35:56 [INFO] [jakub2.dwa-skladniki.pl] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/98844281
2020/08/23 16:35:56 [INFO] [*.jakub2.dwa-skladniki.pl] acme: use dns-01 solver
2020/08/23 16:35:56 [INFO] [jakub2.dwa-skladniki.pl] acme: Could not find solver for: tls-alpn-01
2020/08/23 16:35:56 [INFO] [jakub2.dwa-skladniki.pl] acme: Could not find solver for: http-01
2020/08/23 16:35:56 [INFO] [jakub2.dwa-skladniki.pl] acme: use dns-01 solver
2020/08/23 16:35:56 [INFO] [*.jakub2.dwa-skladniki.pl] acme: Preparing to solve DNS-01
2020/08/23 16:35:59 [INFO] [jakub2.dwa-skladniki.pl] acme: Preparing to solve DNS-01
2020/08/23 16:36:01 [INFO] [*.jakub2.dwa-skladniki.pl] acme: Trying to solve DNS-01
2020/08/23 16:36:02 [INFO] [*.jakub2.dwa-skladniki.pl] acme: Checking DNS record propagation using [ns-01.hyperone-dns.com:53]
2020/08/23 16:36:04 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2020/08/23 16:36:09 [INFO] [*.jakub2.dwa-skladniki.pl] The server validated our request
2020/08/23 16:36:09 [INFO] [jakub2.dwa-skladniki.pl] acme: Trying to solve DNS-01
2020/08/23 16:36:09 [INFO] [jakub2.dwa-skladniki.pl] acme: Checking DNS record propagation using [ns-01.hyperone-dns.com:53]
2020/08/23 16:36:11 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2020/08/23 16:36:17 [INFO] [jakub2.dwa-skladniki.pl] The server validated our request
2020/08/23 16:36:17 [INFO] [*.jakub2.dwa-skladniki.pl] acme: Cleaning DNS-01 challenge
2020/08/23 16:36:21 [INFO] [jakub2.dwa-skladniki.pl] acme: Cleaning DNS-01 challenge
2020/08/23 16:36:24 [INFO] [jakub2.dwa-skladniki.pl, *.jakub2.dwa-skladniki.pl] acme: Validations succeeded; requesting certificates
2020/08/23 16:36:24 [INFO] [jakub2.dwa-skladniki.pl] Server responded with a certificate.
Successfully got certificate for jakub2.dwa-skladniki.pl and *.jakub2.dwa-skladniki.pl
Getting certificates finished. Failed 0, total 2.
/lego/.lego/certificates/jakub.dwa-skladniki.pl.crt: OK
Successfully verified certificate for jakub.dwa-skladniki.pl
/lego/.lego/certificates/jakub2.dwa-skladniki.pl.crt: OK
Successfully verified certificate for jakub2.dwa-skladniki.pl
```

The implementation seems good now, I'm going to leave myself a day before merging in order to have a more neutral review.

**Comment by kuskoman** [comment]
@ldez big thanks for your help with this pull request, and sorry for my slow responses

**Review by ldez — APPROVED** [review]
Thanks :+1:

**Pull request merged**
