### PR TITLE
Add DNS provider for Regfish

### LINKED ISSUE #2319: Support for provider: regfish
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [X] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Library

### Link to the DNS provider

https://regfish.de

### Link to the API documentation

https://regfish.readme.io

### Additional Notes

I would love it if you could include [regfish](https://regfish.de) in the project. [A Go library is already available](https://github.com/regfish/regfish-dnsapi-go)

### PR DESCRIPTION
**Pull request by ldez**
- [x] adds a description to your PR
- [x] have a homogeneous design with the other providers
- [x] add tests (units)
- [x] add tests ("live")
- [x] add a provider descriptor
- [x] generate CLI help, documentation, and readme.
- [x] be able to do: _(and put the output of this command to a comment)_
  ```bash
  make build
  rm -rf .lego

  REGFISH_API_KEY="xxx" \
  ./dist/lego -m your_email@example.com --dns regfish -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
  ```
  **Note the wildcard domain is important.**
- [x] pass the linter
- [x] do `go mod tidy`

Ping @amallek, can you run the command (with your domain, email, credentials, etc.)?

-> https://github.com/go-acme/lego/pull/2320#issuecomment-2455926731

Closes #2319

### CODE REVIEW

**Comment by amallek** [comment]
@ldez confirmed, I was able to run and obtain a certificate (acme: Validations succeeded; requesting certificates... Server responded with a certificate.)

**Comment by ldez** [comment]
Can you put the output of this command to a comment?

**Comment by amallek** [comment]
Sure - of course, I replace the real domain with example.com.

2024/11/05 00:34:18 [INFO] [*.example.com, example.com] acme: Obtaining bundled SAN certificate
2024/11/05 00:34:19 [INFO] [*.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/14748925633
2024/11/05 00:34:19 [INFO] [example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/14748925643
2024/11/05 00:34:19 [INFO] [*.example.com] acme: use dns-01 solver
2024/11/05 00:34:19 [INFO] [example.com] acme: Could not find solver for: tls-alpn-01
2024/11/05 00:34:19 [INFO] [example.com] acme: Could not find solver for: http-01
2024/11/05 00:34:19 [INFO] [example.com] acme: use dns-01 solver
2024/11/05 00:34:19 [INFO] [*.example.com] acme: Preparing to solve DNS-01
2024/11/05 00:34:20 [INFO] [example.com] acme: Preparing to solve DNS-01
2024/11/05 00:34:20 [INFO] [*.example.com] acme: Trying to solve DNS-01
2024/11/05 00:34:20 [INFO] [*.example.com] acme: Checking DNS record propagation. [nameservers=1.1.1.1:53,1.0.0.1:53,8.8.8.8:53]
2024/11/05 00:34:22 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2024/11/05 00:34:22 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2024/11/05 00:34:38 [INFO] [*.example.com] The server validated our request
2024/11/05 00:34:38 [INFO] [example.com] acme: Trying to solve DNS-01
2024/11/05 00:34:38 [INFO] [example.com] acme: Checking DNS record propagation. [nameservers=1.1.1.1:53,1.0.0.1:53,8.8.8.8:53]
2024/11/05 00:34:40 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2024/11/05 00:34:51 [INFO] [example.com] The server validated our request
2024/11/05 00:34:51 [INFO] [*.example.com] acme: Cleaning DNS-01 challenge
2024/11/05 00:34:52 [INFO] [example.com] acme: Cleaning DNS-01 challenge
2024/11/05 00:34:52 [INFO] [*.example.com, example.com] acme: Validations succeeded; requesting certificates
2024/11/05 00:34:52 [INFO] Wait for certificate [timeout: 30s, interval: 500ms]
2024/11/05 00:34:54 [INFO] [*.example.com] Server responded with a certificate.

**Review by dmke — APPROVED** [review]
LGTM

**Pull request merged**
