### PR TITLE
Update CertID format as per draft-ietf-acme-ari-02

### PR DESCRIPTION
**Pull request by beautifulentropy**
- Implemented the updated CertID format as specified in draft-ietf-acme-ari-02.
- Removed the `--ari-hash-name` flag, which is no longer necessary with the updated format.
- Enabled ARI usage for users with `--no-bundle` option. Previously, this was not possible as the draft-ietf-acme-ari-01 format required metadata available only in the issuer.

---

ATTENTION: this must NOT be merged and should remain in draft until https://github.com/letsencrypt/boulder/pull/7184 is merged and deployed.

UPDATE: this change has been merged, but it will not be deployed to Production until a few days into the new year. I'll update this issue when that's the case.

### CODE REVIEW

**Comment by beautifulentropy** [comment]
Failing test:

```
Error: cmd/cmd_renew.go:128:1: cyclomatic complexity 15 of func `renewForDomains` is high (> 12) (gocyclo)
func renewForDomains(ctx *cli.Context, client *lego.Client, certsStorage *CertificatesStorage, bundle bool, meta map[string]string) error {
^
make: *** [Makefile:36: checks] Error 1
Error: Process completed with exit code 2.
```

**Comment by ldez** [comment]
for now, you can ignore the linter about cyclomatic complexity, I will look at the best way to handle that.

**Comment by ldez** [comment]
I fixed the problem of cyclomatic complexity.
Just waiting for the deployment to Production.

**Comment by beautifulentropy** [comment]
> I fixed the problem of cyclomatic complexity. Just waiting for the deployment to Production.

Thanks for fixing this. Just checked our SRE team and support for this portion of draft-ietf-acme-ari-02 has been successfully deployed to both staging and production.

**Comment by ldez** [comment]
Maybe you can set the PR as "Ready for review"?

**Review by ldez — APPROVED** [review]
LGTM

Note: this change is breaking but it's expected of a draft. So we will not create a major version only for this change.

**Pull request merged**
