### PR TITLE
Add Infomaniak DNS provider

### PR DESCRIPTION
**Pull request by L3o-pold**
Add Infomaniak DNS provider. Infomaniak in an important hosting provider in Switzerland.

### CODE REVIEW

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests (units)
```shell
make test
```
- [ ] add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help, documentation, and readme.
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`

**Comment by L3o-pold** [comment]
```bash
 INFOMANIAK_ACCESS_TOKEN=***** \
INFOMANIAK_ENDPOINT=https://api.infomaniak.com \
INFOMANIAK_TTL=300 \
dist/lego --dns infomaniak --domains leopez.ch --email leopold.jacquot@****.com run
2020/10/26 17:14:06 [INFO] [leopez.ch] acme: Obtaining bundled SAN certificate
2020/10/26 17:14:07 [INFO] [leopez.ch] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/8156939486
2020/10/26 17:14:07 [INFO] [leopez.ch] acme: Could not find solver for: tls-alpn-01
2020/10/26 17:14:07 [INFO] [leopez.ch] acme: Could not find solver for: http-01
2020/10/26 17:14:07 [INFO] [leopez.ch] acme: use dns-01 solver
2020/10/26 17:14:07 [INFO] [leopez.ch] acme: Preparing to solve DNS-01
2020/10/26 17:14:07 [INFO] [leopez.ch] acme: Trying to solve DNS-01
2020/10/26 17:14:07 [INFO] [leopez.ch] acme: Checking DNS record propagation using [84.16.67.69:53 84.16.67.70:53]
2020/10/26 17:14:09 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2020/10/26 17:14:09 [INFO] [leopez.ch] acme: Waiting for DNS record propagation.
2020/10/26 17:14:11 [INFO] [leopez.ch] acme: Waiting for DNS record propagation.
2020/10/26 17:14:50 [INFO] [leopez.ch] The server validated our request
2020/10/26 17:14:50 [INFO] [leopez.ch] acme: Cleaning DNS-01 challenge
2020/10/26 17:14:51 [INFO] [leopez.ch] acme: Validations succeeded; requesting certificates
2020/10/26 17:14:51 [INFO] [leopez.ch] Server responded with a certificate.
```

**Comment by ldez** [comment]
Note the wildcard domain is important for the command test, could you do another run, thank you.

**Comment by L3o-pold** [comment]
Sure:

```bash
INFOMANIAK_ACCESS_TOKEN=****\
INFOMANIAK_ENDPOINT=https://api.infomaniak.com \
INFOMANIAK_TTL=300 \
dist/lego --dns infomaniak --domains *.leopez.ch --email leopold.jacquot@gmail.com run
2020/10/26 17:20:27 No key found for account leopold.jacquot@gmail.com. Generating a P256 key.
2020/10/26 17:20:27 Saved key to /Users/leopoldjacquot/go/src/github.com/go-acme/lego/.lego/accounts/acme-v02.api.letsencrypt.org/leopold.jacquot@gmail.com/keys/leopold.jacquot@gmail.com.key
2020/10/26 17:20:28 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
Y
2020/10/26 17:20:32 [INFO] acme: Registering account for leopold*****
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/Users/****/go/src/github.com/go-acme/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2020/10/26 17:20:33 [INFO] [*.leopez.ch] acme: Obtaining bundled SAN certificate
2020/10/26 17:20:33 [INFO] [*.leopez.ch] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/8157068729
2020/10/26 17:20:33 [INFO] [*.leopez.ch] acme: use dns-01 solver
2020/10/26 17:20:33 [INFO] [*.leopez.ch] acme: Preparing to solve DNS-01
2020/10/26 17:20:34 [INFO] [*.leopez.ch] acme: Trying to solve DNS-01
2020/10/26 17:20:34 [INFO] [*.leopez.ch] acme: Checking DNS record propagation using [84.16.67.69:53 84.16.67.70:53]
2020/10/26 17:20:36 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2020/10/26 17:20:36 [INFO] [*.leopez.ch] acme: Waiting for DNS record propagation.
2020/10/26 17:20:38 [INFO] [*.leopez.ch] acme: Waiting for DNS record propagation.
2020/10/26 17:20:40 [INFO] [*.leopez.ch] acme: Waiting for DNS record propagation.
2020/10/26 17:20:47 [INFO] [*.leopez.ch] The server validated our request
2020/10/26 17:20:47 [INFO] [*.leopez.ch] acme: Cleaning DNS-01 challenge
2020/10/26 17:20:47 [INFO] [*.leopez.ch] acme: Validations succeeded; requesting certificates
2020/10/26 17:20:48 [INFO] [*.leopez.ch] Server responded with a certificate.
```

**Comment by ldez** [comment]
Could you execute this command (2 domains with one wildcard domain):

```
rm -rf .lego

./lego -m leopold.jacquot@gmail.com --dns infomaniak -d *.leopez.ch -d leopez.ch -s https://acme-staging-v02.api.letsencrypt.org/directory run
```

**Comment by L3o-pold** [comment]
Sure,

```bash
INFOMANIAK_ACCESS_TOKEN=**** \
INFOMANIAK_ENDPOINT=https://api.infomaniak.com \
INFOMANIAK_TTL=300 \
dist/lego -m leopold.jacquot@gmail.com --dns infomaniak -d *.leopez.ch -d leopez.ch -s https://acme-staging-v02.api.letsencrypt.org/directory run
2020/10/26 17:27:08 No key found for account leopold.jacquot@gmail.com. Generating a P256 key.
2020/10/26 17:27:08 Saved key to /Users/leopoldjacquot/go/src/github.com/go-acme/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/leopold.jacquot@gmail.com/keys/leopold.jacquot@gmail.com.key
2020/10/26 17:27:08 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
Y
2020/10/26 17:27:11 [INFO] acme: Registering account for leopold.jacquot@gmail.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/Users/leopoldjacquot/go/src/github.com/go-acme/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2020/10/26 17:27:11 [INFO] [*.leopez.ch, leopez.ch] acme: Obtaining bundled SAN certificate
2020/10/26 17:27:12 [INFO] [*.leopez.ch] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/140587488
2020/10/26 17:27:12 [INFO] [leopez.ch] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/140587489
2020/10/26 17:27:12 [INFO] [*.leopez.ch] acme: use dns-01 solver
2020/10/26 17:27:12 [INFO] [leopez.ch] acme: Could not find solver for: tls-alpn-01
2020/10/26 17:27:12 [INFO] [leopez.ch] acme: Could not find solver for: http-01
2020/10/26 17:27:12 [INFO] [leopez.ch] acme: use dns-01 solver
2020/10/26 17:27:12 [INFO] [*.leopez.ch] acme: Preparing to solve DNS-01
2020/10/26 17:27:12 [INFO] [leopez.ch] acme: Preparing to solve DNS-01
2020/10/26 17:27:13 [INFO] [*.leopez.ch] acme: Trying to solve DNS-01
2020/10/26 17:27:13 [INFO] [*.leopez.ch] acme: Checking DNS record propagation using [84.16.67.69:53 84.16.67.70:53]
2020/10/26 17:27:15 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2020/10/26 17:27:15 [INFO] [*.leopez.ch] acme: Waiting for DNS record propagation.
2020/10/26 17:27:17 [INFO] [*.leopez.ch] acme: Waiting for DNS record propagation.
2020/10/26 17:27:24 [INFO] [*.leopez.ch] The server validated our request
2020/10/26 17:27:24 [INFO] [leopez.ch] acme: Trying to solve DNS-01
2020/10/26 17:27:24 [INFO] [leopez.ch] acme: Checking DNS record propagation using [84.16.67.69:53 84.16.67.70:53]
2020/10/26 17:27:26 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2020/10/26 17:27:30 [INFO] [leopez.ch] The server validated our request
2020/10/26 17:27:30 [INFO] [*.leopez.ch] acme: Cleaning DNS-01 challenge
2020/10/26 17:27:30 [INFO] [leopez.ch] acme: Cleaning DNS-01 challenge
2020/10/26 17:27:31 [INFO] [*.leopez.ch, leopez.ch] acme: Validations succeeded; requesting certificates
2020/10/26 17:27:32 [INFO] [*.leopez.ch] Server responded with a certificate.
```

**Comment by L3o-pold** [comment]
The `INFOMANIAK_ENDPOINT` config is now optional and not mandatory as it seems the most common use case.

**Comment by L3o-pold** [comment]
@ldez can you trigger the Travis-CI pipeline please, the fail seems not related to this MR.

**Comment by L3o-pold** [comment]
@ldez do you need other changes to be made? I see that `have a homogeneous design with the other providers` is not checked.

**Comment by L3o-pold** [comment]
awesome @ldez thanks for the review and the homogeneous design!

**Review by ldez — APPROVED** [review]
Thank you :+1:

**Pull request merged**
