### PR TITLE
Add DNS provider for Variomedia

### LINKED ISSUE #1637: Support for provider: Variomedia
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Through Traefik

### Link to the DNS provider

https://www.variomedia.de

### Link to the API documentation

- https://api.variomedia.de/docs/dns-records.html
- https://www.variomedia.de/faq/Wie-kann-ich-die-API-fuer-den-Lets-Encrypt-Certbot-nutzen/article/327

### Additional Notes

The site is entirely in german, the "docs" can be found in the google translated version [here](https://api-variomedia-de.translate.goog/docs/dns-records.html?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=fr&_x_tr_pto=wapp) and [here](https://www-variomedia-de.translate.goog/faq/Wie-kann-ich-die-API-fuer-den-Lets-Encrypt-Certbot-nutzen/article/327?_x_tr_sl=de&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=sc)

The shell script version is [here](https://www.variomedia.de/tools/certbot/certbot-dns-master.zip)

### PR DESCRIPTION
**Pull request by ldez**
- [x] have a homogeneous design with the other providers
- [x] pass the linter
- [x] do `go mod tidy`
- [x] add tests (units)
- [x] add tests ("live")
- [x] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [x] generate CLI help, documentation, and readme.
- [x] be able to do: _(and put the output of this command to a comment)_
```bash
rm -rf .lego/

VARIOMEDIA_API_TOKEN=xxx ./lego -m your_email@example.com --dns variomedia -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.

@SIMULATAN could you test by running the previous command (you have to use a real domain and email)?

Closes #1637

### CODE REVIEW

**Comment by SIMULATAN** [comment]
I'll do that real quick!

One quick question: I found some of my placeholder values in the code, is that on purpose?
For example here: https://github.com/go-acme/lego/pull/1654/files#diff-964f1c0847ff2e18a14c04de7e463833ef723fff9e5dd8d6dd399b15cbe4db60R100-R101

**Comment by SIMULATAN** [comment]
It ran through and the last log line includes `Server responded with a certificate`, so it seems good!
I uploaded the full log here: https://gist.github.com/SIMULATAN/c753f8a225d61d2cbd963c3596609417

**Comment by ldez** [comment]
Can you give me the full output of the command? (hide your domain, email, token)

**Comment by ldez** [comment]
I fixed the log problem `variomedia: [example.com] 131313: dns-record%!(EXTRA string=done)`.

The log seems right, I see 2 creates and 2 deletes.

**Comment by SIMULATAN** [comment]
I just checked the certificate and it seems like it covers both domains, even though the json only states one.
It seems like the full cert gets stored in a file with the name of the **first** domain passed via the `-d` flag. This makes sense, but it just confused me.
cert

**Review by dmke — APPROVED** [review]
LGTM

**Pull request merged**
