### PR TITLE
Add support for versio.nl

### PR DESCRIPTION
**Pull request by fjmk**
- [x] add a description to your PR  
This PR adds DNS-01 support for dutch provider https://www.versio.nl/domeinnamen
I am a user of this provider.

- [x] be able to maintain this provider  
Yes, I am willing to maintain this provider

- [x] have a homogeneous design with the other providers
- [x] have tests ("live" and units)  
ok      github.com/go-acme/lego/providers/dns/versio    0.033s  coverage: 85.8% of statements

- [x] added the provider to the readme.md
- [x] added a provider descriptor
- [x] generated CLI help and documentation
- [x] be able to do: 

lego --email="me@example.com" --domains="\*.fjmk.eu" --domains="fjmk.eu" --dns="versio" --pem run
2019/06/21 10:34:56 [INFO] [\*.fjmk.eu, fjmk.eu] acme: Obtaining bundled SAN certificate
<.... snip ...>
2019/06/21 10:38:38 [INFO] [\*.fjmk.eu, fjmk.eu] acme: Validations succeeded; requesting certificates
2019/06/21 10:38:38 [INFO] [\*.fjmk.eu] Server responded with a certificate.

### CODE REVIEW

**Comment by ldez** [comment]
thanks, could you provide the full logs of the command execution?

**Comment by fjmk** [comment]
No problem.
```
lego --email="me@example.com" --domains="*.fjmk.eu" --domains="fjmk.eu" --dns="versio" --pem run
2019/06/21 10:34:56 [INFO] [*.fjmk.eu, fjmk.eu] acme: Obtaining bundled SAN certificate
2019/06/21 10:34:56 [INFO] [\*.fjmk.eu, fjmk.eu] acme: Obtaining bundled SAN certificate
2019/06/21 10:34:57 [INFO] [*.fjmk.eu] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/AIgVm-3XHy4e74h1H-n-YQiltPZfLdcJDGOWbakFPNo
2019/06/21 10:34:57 [INFO] [fjmk.eu] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/_EkNMGj9tACrvIT7z7Gf6XDnHXJJL5vbFXln0RLaAbQ
2019/06/21 10:34:57 [INFO] [*.fjmk.eu] acme: use dns-01 solver
2019/06/21 10:34:57 [INFO] [fjmk.eu] acme: Could not find solver for: tls-alpn-01
2019/06/21 10:34:57 [INFO] [fjmk.eu] acme: Could not find solver for: http-01
2019/06/21 10:34:57 [INFO] [fjmk.eu] acme: use dns-01 solver
2019/06/21 10:34:57 [INFO] [*.fjmk.eu] acme: Preparing to solve DNS-01
2019/06/21 10:35:20 [INFO] [*.fjmk.eu] acme: Trying to solve DNS-01
2019/06/21 10:35:20 [INFO] [*.fjmk.eu] acme: Checking DNS record propagation using [127.0.0.1:53 192.168.178.1:53 [fd00::3631:c4ff:fe57:8332]:53]
2019/06/21 10:35:20 [INFO] Wait for propagation [timeout: 1m0s, interval: 5s]
2019/06/21 10:35:30 [INFO] [*.fjmk.eu] acme: Waiting for DNS record propagation.
2019/06/21 10:35:45 [INFO] [*.fjmk.eu] acme: Waiting for DNS record propagation.
2019/06/21 10:36:00 [INFO] [*.fjmk.eu] acme: Waiting for DNS record propagation.
2019/06/21 10:36:13 [INFO] [*.fjmk.eu] The server validated our request
2019/06/21 10:36:13 [INFO] [*.fjmk.eu] acme: Cleaning DNS-01 challenge
2019/06/21 10:36:16 [INFO] sequence: wait for 1m0s
2019/06/21 10:37:16 [INFO] [fjmk.eu] acme: Preparing to solve DNS-01
2019/06/21 10:37:20 [INFO] [fjmk.eu] acme: Trying to solve DNS-01
2019/06/21 10:37:20 [INFO] [fjmk.eu] acme: Checking DNS record propagation using [127.0.0.1:53 192.168.178.1:53 [fd00::3631:c4ff:fe57:8332]:53]
2019/06/21 10:37:20 [INFO] Wait for propagation [timeout: 1m0s, interval: 5s]
2019/06/21 10:37:42 [INFO] [fjmk.eu] acme: Waiting for DNS record propagation.
2019/06/21 10:37:58 [INFO] [fjmk.eu] acme: Waiting for DNS record propagation.
2019/06/21 10:38:15 [INFO] [fjmk.eu] acme: Waiting for DNS record propagation.
2019/06/21 10:38:35 [INFO] [fjmk.eu] The server validated our request
2019/06/21 10:38:35 [INFO] [fjmk.eu] acme: Cleaning DNS-01 challenge
2019/06/21 10:38:38 [INFO] [*.fjmk.eu, fjmk.eu] acme: Validations succeeded; requesting certificates
2019/06/21 10:38:38 [INFO] [*.fjmk.eu] Server responded with a certificate.
```

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [x] add a description to your PR
- [ ] be able to maintain this provider
- [x] have a homogeneous design with the other providers
- [ ] add tests ("live" and units)
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [x] add the provider to the [readme.md](https://github.com/go-acme/lego#dns-providers)
- [x] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [x] generate CLI help and documentation
```bash
make generate-dns
```
- [x] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [x] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```

**Comment by ldez** [comment]
1. live tests are missing
2. could you explain why you are running the challenge into the sequential mode `func (d *DNSProvider) Sequential() time.Duration {`?

**Comment by ldez** [comment]
now you removed the sequential constraints, could you run once again the following command (and give the output):
```
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```

**Comment by fjmk** [comment]
Thank you for your review and changes, as a starter with golang I learned a lot!

1. I have added live tests, tested them and they are working.
2. I have removed Sequential() because it seems to work without it?

The reason I did it because versio.nl API allows a minimum TTL of 300 seconds. So I thougth I needed to wait maybe about 310 seconds for the second challenge. (but I never needed it...)

Still don't understand how it is working...
Now we add 2 different challenge TXT records with the **same** fqdn before we test for the first DNS propagation. But the first challenge is overwritten by the second immediately. So LE can only test against the second challenge?

**Comment by fjmk** [comment]
And a new output:
```
lego --email="me@example.com" --domains="*.t01.fjmk.eu" --domains="t01.fjmk.eu" --dns="versio" --pem --server=https://acme-staging-v02.api.letsencrypt.org/directory run
2019/06/23 17:38:58 [INFO] [*.t01.fjmk.eu, t01.fjmk.eu] acme: Obtaining bundled SAN certificate
2019/06/23 17:38:59 [INFO] [*.t01.fjmk.eu] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/4keHKH7SyishpOCkbZR73Vrv3KXkL7wW-pTW79FYew8
2019/06/23 17:38:59 [INFO] [t01.fjmk.eu] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/qli4fZ4BRWVbsxooHz7WIy81T49O9-ghTm_dHFz5NUw
2019/06/23 17:38:59 [INFO] [*.t01.fjmk.eu] acme: use dns-01 solver
2019/06/23 17:38:59 [INFO] [t01.fjmk.eu] acme: Could not find solver for: tls-alpn-01
2019/06/23 17:38:59 [INFO] [t01.fjmk.eu] acme: Could not find solver for: http-01
2019/06/23 17:38:59 [INFO] [t01.fjmk.eu] acme: use dns-01 solver
2019/06/23 17:38:59 [INFO] [*.t01.fjmk.eu] acme: Preparing to solve DNS-01
2019/06/23 17:39:01 [INFO] [t01.fjmk.eu] acme: Preparing to solve DNS-01
2019/06/23 17:39:05 [INFO] [*.t01.fjmk.eu] acme: Trying to solve DNS-01
2019/06/23 17:39:05 [INFO] [*.t01.fjmk.eu] acme: Checking DNS record propagation using [127.0.0.1:53 192.168.178.1:53 [fd00::3631:c4ff:fe57:8332]:53]
2019/06/23 17:39:05 [INFO] Wait for propagation [timeout: 1m0s, interval: 5s]
2019/06/23 17:39:05 [INFO] [*.t01.fjmk.eu] acme: Waiting for DNS record propagation.
2019/06/23 17:39:10 [INFO] [*.t01.fjmk.eu] acme: Waiting for DNS record propagation.
2019/06/23 17:39:15 [INFO] [*.t01.fjmk.eu] acme: Waiting for DNS record propagation.
2019/06/23 17:39:27 [INFO] [*.t01.fjmk.eu] The server validated our request
2019/06/23 17:39:27 [INFO] [t01.fjmk.eu] acme: Trying to solve DNS-01
2019/06/23 17:39:27 [INFO] [t01.fjmk.eu] acme: Checking DNS record propagation using [127.0.0.1:53 192.168.178.1:53 [fd00::3631:c4ff:fe57:8332]:53]
2019/06/23 17:39:27 [INFO] Wait for propagation [timeout: 1m0s, interval: 5s]
2019/06/23 17:39:28 [INFO] [t01.fjmk.eu] The server validated our request
2019/06/23 17:39:28 [INFO] [*.t01.fjmk.eu] acme: Cleaning DNS-01 challenge
2019/06/23 17:39:30 [INFO] [t01.fjmk.eu] acme: Cleaning DNS-01 challenge
2019/06/23 17:39:32 [INFO] [*.t01.fjmk.eu, t01.fjmk.eu] acme: Validations succeeded; requesting certificates
2019/06/23 17:39:34 [INFO] [*.t01.fjmk.eu] Server responded with a certificate.

```

**Comment by ldez** [comment]
If there are 2 TXT records, LE choose the good one.

In the "parallel" mode:
1. all the records are added/appended
2. lego try to solve the both challenge.
3. lego clean the records.

**Pull request merged**
