### PR TITLE
Add DNS provider for Simply.com

### PR DESCRIPTION
**Pull request by zraexy**
Add support for Simply.com as a DNS provider.

https://www.simply.com/en/domains/

<details>

* [x]  add a description to your PR
* [x]  be able to maintain this provider
        (I am a customer of Simply.com)
* [x]  have a homogeneous design with the other providers
* [x]  add tests (units)
```shell
make test
 ```
* [x]  add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151
```shell
make test
```
* [x]  add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
* [x]  generate CLI help, documentation, and readme.
```shell
make generate-dns
```
* [x]  be able to do: _(and put the output of this command to a comment in your PR)_
```shell
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
* [x]  pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
* [x]  do `go mod tidy`

</details>

### CODE REVIEW

**Comment by zraexy** [comment]
Running:
```shell
rm -rf .lego

SIMPLY_API_KEY=xxx SIMPLY_ACCOUNT_NAME=yyy ./lego -m your@email.com --dns simply -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Outputs:
```shell
2021/06/01 15:52:52 No key found for account your@email.com. Generating a P256 key.
2021/06/01 15:52:52 Saved key to /home/me/profiles/nixos/custompackages/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/your@email.com/keys/your@email.com.key
2021/06/01 15:52:52 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
y
2021/06/01 15:52:54 [INFO] acme: Registering account for your@email.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/home/me/profiles/nixos/custompackages/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2021/06/01 15:52:55 [INFO] [*.example.com, example.com] acme: Obtaining bundled SAN certificate
2021/06/01 15:52:57 [INFO] [*.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/60420824
2021/06/01 15:52:57 [INFO] [example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/60420825
2021/06/01 15:52:57 [INFO] [*.example.com] acme: use dns-01 solver
2021/06/01 15:52:57 [INFO] [example.com] acme: Could not find solver for: tls-alpn-01
2021/06/01 15:52:57 [INFO] [example.com] acme: Could not find solver for: http-01
2021/06/01 15:52:57 [INFO] [example.com] acme: use dns-01 solver
2021/06/01 15:52:57 [INFO] [*.example.com] acme: Preparing to solve DNS-01
2021/06/01 15:52:58 [INFO] [example.com] acme: Preparing to solve DNS-01
2021/06/01 15:52:58 [INFO] [*.example.com] acme: Trying to solve DNS-01
2021/06/01 15:52:58 [INFO] [*.example.com] acme: Checking DNS record propagation using [192.168.85.1:53 [fdf2:ff1d:d2b::1]:53]
2021/06/01 15:53:08 [INFO] Wait for propagation [timeout: 5m0s, interval: 10s]
2021/06/01 15:53:08 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/06/01 15:53:19 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/06/01 15:53:29 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/06/01 15:53:39 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/06/01 15:53:50 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/06/01 15:54:01 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/06/01 15:54:12 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2021/06/01 15:54:28 [INFO] [*.example.com] The server validated our request
2021/06/01 15:54:28 [INFO] [example.com] acme: Trying to solve DNS-01
2021/06/01 15:54:28 [INFO] [example.com] acme: Checking DNS record propagation using [192.168.85.1:53 [fdf2:ff1d:d2b::1]:53]
2021/06/01 15:54:38 [INFO] Wait for propagation [timeout: 5m0s, interval: 10s]
2021/06/01 15:54:47 [INFO] [example.com] The server validated our request
2021/06/01 15:54:47 [INFO] [*.example.com] acme: Cleaning DNS-01 challenge
2021/06/01 15:54:48 [INFO] [example.com] acme: Cleaning DNS-01 challenge
2021/06/01 15:54:48 [INFO] [*.example.com, example.com] acme: Validations succeeded; requesting certificates
2021/06/01 15:54:49 [INFO] [*.example.com] Server responded with a certificate.
```

**Comment by ldez** [comment]
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests (units)
```shell
make test
```
- [ ] add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help, documentation, and readme.
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`

**Review by ldez — APPROVED** [review]
I really appreciate that you took the time to look at the design of the other providers, as well as the other PRs introducing a provider.

This is a very good quality PR, thank you :+1: :+1: :+1:

**Comment by zraexy** [comment]
I guess it's not that good quality. I just noticed I missed a few comments:
https://github.com/go-acme/lego/blob/1af3abd16e31bf79e569df7a2fb95cadd4a726ad/providers/dns/simply/simply.go#L61-L62
https://github.com/go-acme/lego/blob/1af3abd16e31bf79e569df7a2fb95cadd4a726ad/providers/dns/simply/simply.go#L76

**Comment by ldez** [comment]
Not a major issue, it's just some comments, you can open a PR to fix that.

**Pull request merged**
