### PR TITLE
route53: avoid unexpected records deletion

### LINKED ISSUE #1756: route53: lego deleted all TXT records for root domain
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

We are using the latest traefik, and we were testing some new services and deployed traefik with docker-compose. Our setup looks like this:

<details>

```yml
traefik:
  image: traefik
  ports:
   - 80:80
   - 8080:8080
   - 443:443
  command:
   - "--api.insecure=true"
   - "--providers.docker=true"
   - "--providers.docker.exposedbydefault=false"
   - "--entrypoints.web.address=:80"
   - "--entrypoints.web-secure.address=:443"
   - "--serverstransport.insecureskipverify=true"
   - "--certificatesresolvers.dnsresolver.acme.email=devops+letsencrypt@somedomain.com"
   - "--certificatesresolvers.dnsresolver.acme.storage=acme.json"
   - "--certificatesresolvers.dnsresolver.acme.dnschallenge.provider=route53"
   - "--certificatesresolvers.dnsresolver.acme.dnschallenge.delaybeforecheck=10"
   - "--certificatesresolvers.dnsresolver.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
```

</details>

And these are service labels:

<details>

```yml
labels:
   - "app=grafana"
   - "traefik.enable=true"
   - "traefik.docker.network=web"
   - "traefik.http.routers.grafana-somedomain.entrypoints=web"
   - "traefik.http.routers.grafana-somedomain.rule=Host(`logs.test.somedomain.com`)"
   - "traefik.http.routers.grafana-somedomain-https.rule=Host(`logs.test.somedomain.com`)"
   - "traefik.http.routers.grafana-somedomain-https.entrypoints=web-secure"
   - "traefik.http.routers.grafana-somedomain-https.tls=true"
   - "traefik.http.routers.grafana-somedomain-https.tls.certResolver=dnsresolver"
   - "traefik.http.routers.grafana-somedomain-https.tls.domains[0].main=logs.test.somedomain.com"
   - "traefik.http.services.grafana-somedomain-https.loadbalancer.server.port=3000"
```

</details>

We noticed that we are missing our root domain TXT records. Lego added the record that it needs, and after it verified the domain, it deleted all the others root domain TXT records. Just to mention, as you see from the labels, we didn't ask for the root domain certificate, nor any wildcard one, just for that one subdomain.
We caught that it was the lego library from the Cloudtrail logs:

<details>

```json
{
  "eventVersion": "1.08",
  "userIdentity": {
    "type": "AssumedRole",
    "principalId": "XXX",
    "arn": "arn:aws:sts::XXX:assumed-role/XXX/XXX",
    "accountId": "XXX",
    "accessKeyId": "XXX",
    "sessionContext": {
      "sessionIssuer": {
        "type": "Role",
        "principalId": "XXX",
        "arn": "arn:aws:iam::XXX:role/XXX",
        "accountId": "XXX",
        "userName": "XXX"
      },
      "webIdFederationData": {},
      "attributes": {
        "creationDate": "2022-11-15T10:50:05Z",
        "mfaAuthenticated": "false"
      },
      "ec2RoleDelivery": "1.0"
    }
  },
  "eventTime": "2022-11-15T10:52:31Z",
  "eventSource": "route53.amazonaws.com",
  "eventName": "ChangeResourceRecordSets",
  "awsRegion": "us-east-1",
  "sourceIPAddress": "XXX",
  "userAgent": "aws-sdk-go/1.44.47 (go1.19.2; linux; arm64)",
  "requestParameters": {
    "hostedZoneId": "XXX",
    "changeBatch": {
      "comment": "Managed by Lego",
      "changes": [
        {
          "action": "UPSERT",
          "resourceRecordSet": {
            "name": "somedomain.com.",
            "type": "TXT",
            "tTL": 10,
            "resourceRecords": [
              {
                "value": "\"v=spf1 include:_spf.google.com include:mail.zendesk.com include:spf.mandrillapp.com include:amazonses.com -all\""
              },
              {
                "value": "\"XXX""
              },
              {
                "value": "\"google-site-verification=XXX\""
              },
              {
                "value": "\"yandex-verification: XXX\""
              },
              {
                "value": "\"stripe-verification=XXX\""
              },
              {
                "value": "\"MS=XXX\""
              },
              {
                "value": "\"google-site-verification=XXX\""
              },
              {
                "value": "\"apple-domain-verification=XXX\""
              },
              {
                "value": "\"google-site-verification=XXX\""
              },
              {
                "value": "\"facebook-domain-verification=XXX\""
              },
              {
                "value": "\"XXX\""
              }
            ]
          }
        }
      ]
    }
  },
  "responseElements": {
    "changeInfo": {
      "id": "/change/XXX",
      "status": "PENDING",
      "submittedAt": "Nov 15, 2022 10:52:31 AM",
      "comment": "Managed by Lego"
    }
  },
  "additionalEventData": {
    "Note": "Do not use to reconstruct hosted zone"
  },
  "requestID": "e5448e23-fed7-4438-a592-XXX",
  "eventID": "9b30b976-9176-491d-b16a-XXX",
  "readOnly": false,
  "eventType": "AwsApiCall",
  "apiVersion": "2013-04-01",
  "managementEvent": true,
  "recipientAccountId": "XXX",
  "eventCategory": "Management",
  "tlsDetails": {
    "tlsVersion": "TLSv1.2",
    "cipherSuite": "ECDHE-RSA-AES128-GCM-SHA256",
    "clientProvidedHostHeader": "route53.amazonaws.com"
  }
},
```
</details>

And this is where it deleted it all:

<details>

```json
{
      "eventVersion": "1.08",
      "userIdentity": {
        "type": "AssumedRole",
        "principalId": "XXX",
        "arn": "arn:aws:sts::XXX:assumed-role/XXX/XXX",
        "accountId": "XXX",
        "accessKeyId": "XXX",
        "sessionContext": {
          "sessionIssuer": {
            "type": "Role",
            "principalId": "XXX",
            "arn": "arn:aws:iam::XXX:role/XXX",
            "accountId": "XXX",
            "userName": "XXX"
          },
          "webIdFederationData": {},
          "attributes": {
            "creationDate": "2022-11-15T10:50:05Z",
            "mfaAuthenticated": "false"
          },
          "ec2RoleDelivery": "1.0"
        }
      },
      "eventTime": "2022-11-15T10:53:40Z",
      "eventSource": "route53.amazonaws.com",
      "eventName": "ChangeResourceRecordSets",
      "awsRegion": "us-east-1",
      "sourceIPAddress": "XXX",
      "userAgent": "aws-sdk-go/1.44.47 (go1.19.2; linux; arm64)",
      "requestParameters": {
        "hostedZoneId": "XXX",
        "changeBatch": {
          "comment": "Managed by Lego",
          "changes": [
            {
              "action": "DELETE",
              "resourceRecordSet": {
                "name": "somedomain.com.",
                "type": "TXT",
                "tTL": 10,
                "resourceRecords": [
                  {
                    "value": "\"v=spf1 include:_spf.google.com include:mail.zendesk.com include:spf.mandrillapp.com include:amazonses.com -all\""
                  },
                  {
                    "value": "\"ahrefs-site-XXX\""
                  },
                  {
                    "value": "\"google-site-verification=XXX\""
                  },
                  {
                    "value": "\"yandex-verification: XXX\""
                  },
                  {
                    "value": "\"stripe-verification=XXX\""
                  },
                  {
                    "value": "\"MS=XXX\""
                  },
                  {
                    "value": "\"google-site-verification=XXX\""
                  },
                  {
                    "value": "\"apple-domain-verification=XXX\""
                  },
                  {
                    "value": "\"google-site-verification=XXX\""
                  },
                  {
                    "value": "\"facebook-domain-verification=XXX\""
                  },
                  {
                    "value": "\"XXX\""
                  }
                ]
              }
            }
          ]
        }
      },
      "responseElements": {
        "changeInfo": {
          "id": "/change/XXX",
          "status": "PENDING",
          "submittedAt": "Nov 15, 2022 10:53:40 AM",
          "comment": "Managed by Lego"
        }
      },
      "additionalEventData": {
        "Note": "Do not use to reconstruct hosted zone"
      },
      "requestID": "210676d7-7a39-48ed-8604-XXX",
      "eventID": "c97381f8-3b1a-484c-a881-XXX",
      "readOnly": false,
      "eventType": "AwsApiCall",
      "apiVersion": "2013-04-01",
      "managementEvent": true,
      "recipientAccountId": "XXX",
      "eventCategory": "Management",
      "tlsDetails": {
        "tlsVersion": "TLSv1.2",
        "cipherSuite": "ECDHE-RSA-AES128-GCM-SHA256",
        "clientProvidedHostHeader": "route53.amazonaws.com"
      }
    },
```
</details>

Luckily we had a backup of everything and we added those records back. This is really serious issue...

### What did you see instead?

That Lego deletes only what it adds to TXT record.

### How do you use lego?

Through Traefik

### Reproduction steps

Traefik configuration is in "What did you expect to see"

### Version of lego

```console
Traefik v2.9.4
```

### Logs

<details>

Cloudtrail logs are in What did you expect to see

</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

### PR DESCRIPTION
**Pull request by ldez**
Fixes #1756

### CODE REVIEW

**Comment by ldez** [comment]
@kingcdavid can you try this PR?

**Comment by kingcdavid** [comment]
Int Tests passed
```console
➜  lego git:(fix/route53-protect-records) go test -v -run TestLiveTTL github.com/go-acme/lego/v4/providers/dns/route53
=== RUN   TestLiveTTL
2023/07/27 13:48:37 [INFO] Wait for route53 [timeout: 2m0s, interval: 4s]
2023/07/27 13:49:15 [INFO] Wait for route53 [timeout: 2m0s, interval: 4s]
--- PASS: TestLiveTTL (74.20s)
PASS
ok  	github.com/go-acme/lego/v4/providers/dns/route53	74.205s
```

But i can't actually re-create the original issue to see if it's fixed, What CNAME needs to be implemented?

**Comment by ldez** [comment]
I think it's a wildcard CNAME.

**Comment by kingcdavid** [comment]
so was able to recreate but it now errors when trying to delete the records:
```console
2023/07/27 15:38:08 [WARN] [<redacted>] acme: cleaning up failed: route53: failed to change record set: operation error Route 53: ChangeResourceRecordSets, https response error StatusCode: 400, RequestID: <redacted>, InvalidChangeBatch: [Tried to delete resource record set [name='<redacted>', type='TXT'] but the values provided do not match the current values] 
```

i think we need to do something like this (tested as working)
```diff
diff --git a/providers/dns/route53/route53.go b/providers/dns/route53/route53.go
index d48fd3b6..862cdd51 100644
--- a/providers/dns/route53/route53.go
+++ b/providers/dns/route53/route53.go
@@ -185,14 +185,19 @@ func (d *DNSProvider) CleanUp(domain, token, keyAuth string) error {
                return nil
        }
 
-       var toDelete []awstypes.ResourceRecord
+       var toChange []awstypes.ResourceRecord
        for _, record := range records {
-               if deref(record.Value) == `"`+info.Value+`"` {
-                       toDelete = append(toDelete, record)
+               if deref(record.Value) != `"`+info.Value+`"` {
+                       toChange = append(toChange, record)
                }
        }
+       action := awstypes.ChangeActionUpsert
+       if len(toChange) == 0 {
+               toChange = records
+               action = awstypes.ChangeActionDelete
+       }
 
-       if len(toDelete) == 0 {
+       if len(toChange) == 0 {
                return nil
        }
 
@@ -200,10 +205,10 @@ func (d *DNSProvider) CleanUp(domain, token, keyAuth string) error {
                Name:            aws.String(info.EffectiveFQDN),
                Type:            "TXT",
                TTL:             aws.Int64(int64(d.config.TTL)),
-               ResourceRecords: toDelete,
+               ResourceRecords: toChange,
        }
 
-       err = d.changeRecord(ctx, awstypes.ChangeActionDelete, hostedZoneID, recordSet)
+       err = d.changeRecord(ctx, action, hostedZoneID, recordSet)
        if err != nil {
                return fmt.Errorf("route53: %w", err)
        }

```

**Comment by ldez** [comment]
Thank you, I adapted the algorithm and rename some variables to improve the readability.

Offtopic: I recommend you add your company email (xxxxx.xxxx@glxxxxxxxn.com) to your GiHub profile to avoid this weird behavior https://github.com/go-acme/lego/pull/1970/commits

**Review by dmke — APPROVED** [review]

**Pull request merged**
