### PR TITLE
pdns: get exact zone instead of all zones

### LINKED ISSUE #817: New Error with DNS-01 update (powerdns 4.1.5 & 4.1.6)
error presenting token: pdns: unexpected HTTP status code 404 when fetching 'http://127.0.0.1:8081/api/v1/'

Seems that they changed borked the trailing slash?

```
curl -H 'Content-Type: application/json' -H 'X-API-Key: secretsource' http://127.0.0.1:8081/api
[{"url": "/api/v1", "version": 1}]
```

```
curl -H 'Content-Type: application/json' -H 'X-API-Key: secretsource' http://127.0.0.1:8081/api/
Not Found
```

### PR DESCRIPTION
**Pull request by mrpk1906**
Hello,

When trying obtain a certificate, I got an error message

```
acme: error presenting token: pdns: error talking to PDNS API: Get "http://pdns-server:8081/api/v1/servers/localhost/zones": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

My PDNS server has > 5k zones, to get all zones it takes >30s. I can increase timeout by using `PDNS_HTTP_TIMEOUT` but I think we can get exact zone instead of all zones ( for single zone, it takes only ~50ms )

Fixes #817

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

could you provide run the following command and put the output of this command to a comment:

```bash
rm -rf .lego

./lego -m your@email.com --dns pdns -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```

**Comment by mrpk1906** [comment]
Hi @ldez 

This is output: (personal info has been replaced)

```
myuser@mycomputer:~$ PDNS_API_URL="http://pdns-server:8081/" PDNS_API_KEY="API_KEY" ./lego -m myuser@email.com --dns pdns -d '*.mydomain.com' -d mydomain.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
2020/11/25 09:09:59 No key found for account myuser@email.com. Generating a P256 key.
2020/11/25 09:09:59 Saved key to /Users/myuser/go/src/github.com/go-acme/lego/cmd/lego/.lego/accounts/acme-staging-v02.api.letsencrypt.org/myuser@email.com/keys/myuser@email.com.key
2020/11/25 09:10:01 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n
y
2020/11/25 09:10:04 [INFO] acme: Registering account for myuser@email.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/Users/myuser/go/src/github.com/go-acme/lego/cmd/lego/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2020/11/25 09:10:04 [INFO] [*.mydomain.com, mydomain.com] acme: Obtaining bundled SAN certificate
2020/11/25 09:10:05 [INFO] [*.mydomain.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/161527632
2020/11/25 09:10:05 [INFO] [mydomain.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/161527633
2020/11/25 09:10:05 [INFO] [*.mydomain.com] acme: use dns-01 solver
2020/11/25 09:10:05 [INFO] [mydomain.com] acme: Could not find solver for: tls-alpn-01
2020/11/25 09:10:05 [INFO] [mydomain.com] acme: Could not find solver for: http-01
2020/11/25 09:10:05 [INFO] [mydomain.com] acme: use dns-01 solver
2020/11/25 09:10:05 [INFO] [*.mydomain.com] acme: Preparing to solve DNS-01
2020/11/25 09:10:08 [INFO] [mydomain.com] acme: Preparing to solve DNS-01
2020/11/25 09:10:10 [INFO] [*.mydomain.com] acme: Trying to solve DNS-01
2020/11/25 09:10:10 [INFO] [*.mydomain.com] acme: Checking DNS record propagation using [8.8.8.8:53]
2020/11/25 09:10:12 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
2020/11/25 09:10:14 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/11/25 09:10:17 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/11/25 09:10:20 [INFO] [*.mydomain.com] acme: Waiting for DNS record propagation.
2020/11/25 09:10:30 [INFO] [*.mydomain.com] The server validated our request
2020/11/25 09:10:30 [INFO] [mydomain.com] acme: Trying to solve DNS-01
2020/11/25 09:10:30 [INFO] [mydomain.com] acme: Checking DNS record propagation using [8.8.8.8:53]
2020/11/25 09:10:32 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
2020/11/25 09:10:41 [INFO] [mydomain.com] The server validated our request
2020/11/25 09:10:41 [INFO] [*.mydomain.com] acme: Cleaning DNS-01 challenge
2020/11/25 09:10:43 [INFO] [mydomain.com] acme: Cleaning DNS-01 challenge
2020/11/25 09:10:44 [WARN] [mydomain.com] acme: cleaning up failed: pdns: no existing record found for _acme-challenge.mydomain.com. 
2020/11/25 09:10:44 [INFO] [*.mydomain.com, mydomain.com] acme: Validations succeeded; requesting certificates
2020/11/25 09:10:45 [INFO] [*.mydomain.com] Server responded with a certificate.
```

**Comment by ldez** [comment]
Hello,

I checked the API documentations, and it's not really clear for me.

PowerDNS 4.0 doc:
- [endpoint](https://doc.powerdns.com/md/httpapi/api_spec/#url-apiv1serversserver95idzoneszone95id)
- [zone object](https://doc.powerdns.com/md/httpapi/api_spec/#zones)

Authoritative Server:
- [endpoint](https://doc.powerdns.com/authoritative/http-api/zone.html#get--servers-server_id-zones-zone_id)
- [zone object](https://doc.powerdns.com/authoritative/http-api/zone.html#zone)

Recursor:
- [endpoint](https://doc.powerdns.com/recursor/http-api/endpoint-zones.html#get--api-v1-servers--server_id-zones--zone_id)
- [zone object](https://doc.powerdns.com/recursor/http-api/zone.html#zone)

The endpoint `/api/v1/servers/:server_id/zones/:zone_id` uses the zone ID (`zone_id`), what is exactly the zone ID and the relation between the zone ID and the zone name ? It's not clear to me.

In the Authoritative Server doc, I see that the endpoint [`/servers/{server_id}/zones`](https://doc.powerdns.com/authoritative/http-api/zone.html#get--servers-server_id-zones) can be filtered by a zone name.
But it's a not documented or not possible with PowerDNS 4.0 or the Recursor.

Those information need to be clarify.

**Comment by ldez** [comment]
@dmke do you have some experiences with that API?

**Comment by dmke** [comment]
> @dmke do you have some experiences with that API?

Sorry, no. When I asked about the REST API on their mailing list a few years back, I was quickly directed to their RFC2136 API.

**Comment by mrpk1906** [comment]
@dmke Thanks for your commit,

@ldez

> The endpoint /api/v1/servers/:server_id/zones/:zone_id uses the zone ID (zone_id), what is exactly the zone ID and the relation between the zone ID and the zone name? It's not clear to me.

`zone_id` has been described in [PDNS Auth API spec](https://raw.githubusercontent.com/PowerDNS/pdns/master/docs/http-api/swagger/authoritative-api-swagger.yaml)

> Opaque zone id (string), assigned by the server, should not be interpreted by the application. Guaranteed to be safe for embedding in URLs.

`zone_id` is `zone name` encoded by using [URL encode](https://en.wikipedia.org/wiki/Percent-encoding)

> In the PDNS doc, I see that the endpoint /servers/{server_id}/zones can be filtered by a zone name.
> But it's a not documented or not possible with PowerDNS 4.0 or the Recursor.

We can by `zone name`, eg: `/api/v1/servers/localhost/zones?zone={zone_name}.` (ending with a dot)
But i saw it only supported from PDNS 4.2 and above ( I tested on 4.1.14 and 4.4.0 alpha)

**Review by ldez — APPROVED** [review]
It's still not really clear, but I will trust you.

Thanks :+1:

**Pull request merged**
