### PR TITLE
feat: ease operation behind proxy servers

### LINKED ISSUE #973: Running behind a reverse proxy (http-01)
Hi,

when lego runs behind a reverse proxy, [its DNS rebind attack prevention](https://github.com/go-acme/lego/blob/v3.0.2/challenge/http01/http_challenge_server.go#L67) causes the ACME validation to fail:

```console
$ lego ... --http --http.port 127.0.0.1:402
...
[WARN] Received request for domain 127.0.0.1 with method GET but the
  domain did not match any challenge. Please ensure your are passing the
  HOST header properly.
...
```

This is because a typical proxy directive for Apache will pass the [original `Host` header as `X-Forwarded-Host`](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#x-headers), and change the pass a new `Host` header containing the host of the proxied URL:

```apache
ProxyPass "/.well-known/acme-challenge/" "http://127.0.0.1:402/.well-known/acme-challenge/"
```

(NGINX does the same, other servers might behave similiar).

For Apache, there's a workaround in form of the [`ProxyPreserveHost`](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypreservehost), but that might confuse some legacy applications.

In this particular setup I'd like to have the option to change the header name used to implement DNS rebind prevention, i.e. sth. similar to:

```console
$ lego ... --http --http.port 127.0.0.1:402 --http.proxy-header X-Forwarded-Host
``` 

To make matters worse (or [better?](https://xkcd.com/927/)), [RFC 7239](https://tools.ietf.org/html/rfc7239) tries to standardize the various proxy/forwarding headers into a single `Forwarded` header, but with different semantics.

I'm currently working on a PR addressing this issue ([WIP here](https://github.com/go-acme/lego/compare/master...digineo:http01-proxy)), but that's not finished/polished yet. I would like to have some early feedback though (in particular, whether I should move the `Fowarded` header parsing into a separate package) :-)

### PR DESCRIPTION
**Pull request by dmke**
fixes #973

### CODE REVIEW

**Comment by mholt** [comment]
This looks like a high-quality PR, esp. with the tests.

I've been traveling this week so I haven't reviewed it in much detail, but so far I like what I see. I'll leave it up to @ldez to decide if the integration with the existing code is satisfactory.

**Comment by dmke** [comment]
I'm updating the docs a bit, hang on.

**Comment by dmke** [comment]
@ldez: What's needs to be done to merge this PR?

If you're worried about maintainership, I'm happy to tackle issues arising with this code. It is also already deployed on an number of hosts and working fine.

**Comment by ldez** [comment]
I'm on vacation, I'll look later

**Comment by ldez** [comment]
@dmke could you check the box to "Allow edits from maintainers. "

**Comment by dmke** [comment]
It is already checked?

Screenshot from 2019-10-05 12-57-40

**Comment by ldez** [comment]
```
 ERROR: Permission to digineo/lego.git denied to ldez.
```

**Comment by dmke** [comment]
Hm, I can grant you temporary access to digineo/lego, maybe that helps.

**Comment by ldez** [comment]
I tried to re-checkout the PR but I still have the problem, there is something weird with your repo :thinking:

**Comment by ldez** [comment]
I accepted the invitation, but it's not normal.

**Comment by dmke** [comment]
Hm. Let me reopen the PR from my private account...

**Comment by ldez** [comment]
let's the PR open for now, I will merge it soon.

**Comment by dmke** [comment]
Please try to merge #982 if this PR keeps failing.

**Pull request merged**
