### PR TITLE
lego: add method to expose API core

### PR DESCRIPTION
**Pull request by vancluever**
This adds the Core function to the lego client object, allowing
access to the lower-level core API when it's needed.

### CODE REVIEW

**Comment by ldez** [comment]
Could you explain why you need this?

**Comment by vancluever** [comment]
Background: A [recent issue ](https://github.com/terraform-providers/terraform-provider-acme/issues/54)in the Terraform ACME provider has caused local copies of certificates to be deleted. As far as I know, there's currently no function to recover a certificate resource from the API via its certificate URL right now, which will be necessary to repair the states once I address the actual bug.

If it's not optimal to expose the API, maybe a method can be added to Certifier to retrieve a certificate resource from CertURL? It should be pretty easy for me to pivot to that instead.

**Comment by ldez** [comment]
I prefer to not expose the core, then your idea to add a method to the  `Certifier` seems better.

**Comment by vancluever** [comment]
Closing this and will re-submit with the higher-level method on Certifier.

**Pull request closed without merging**
